/**
 * Cultural style configurations for each template.
 * Defines unique decorative elements, greetings, ornaments, and patterns
 * that reflect the cultural identity of each template design.
 */

export type AnimationPreset = 'default' | 'celestial' | 'architectural' | 'chromatic' | 'elemental';

export interface TemplateCulturalStyle {
  greeting: string;
  closingText: string;
  ornamentEmoji: string;
  cornerMotif: 'floral' | 'geometric' | 'wave' | 'tribal' | 'islamic' | 'royal' | 'none';
  dividerStyle: 'ornate' | 'simple' | 'dotted' | 'wave' | 'diamond' | 'arrow' | 'leaf';
  borderStyle: 'double' | 'solid' | 'dashed' | 'ornate' | 'none';
  patternOverlay: string | null;
  sectionRadius: string;
  fontAccent: 'serif' | 'sans' | 'script';
  culturalMotifs: string[];
  backgroundPattern: string | null;
  /** Cultural icons displayed as subtle background decorations */
  culturalIcons?: { emoji: string; label: string }[];
  /** Animation preset for unique enter/exit animations */
  animationPreset?: AnimationPreset;
}

const defaultStyle: TemplateCulturalStyle = {
  greeting: 'Dengan memohon rahmat Tuhan Yang Maha Esa',
  closingText: 'Merupakan kehormatan bagi kami apabila Bapak/Ibu/Saudara/i berkenan hadir',
  ornamentEmoji: '✦',
  cornerMotif: 'none',
  dividerStyle: 'simple',
  borderStyle: 'none',
  patternOverlay: null,
  sectionRadius: '0.75rem',
  fontAccent: 'serif',
  culturalMotifs: [],
  backgroundPattern: null,
};

export const templateCulturalStyles: Record<string, TemplateCulturalStyle> = {
  // ══════════════════ WEDDING TEMPLATES ══════════════════

  'wedding-classic-gold': {
    ...defaultStyle,
    greeting: 'Dengan memohon rahmat Tuhan Yang Maha Esa',
    closingText: 'Merupakan suatu kehormatan bagi kami apabila Bapak/Ibu/Saudara/i berkenan hadir',
    ornamentEmoji: '❧',
    cornerMotif: 'floral',
    dividerStyle: 'ornate',
    borderStyle: 'double',
    fontAccent: 'serif',
    culturalMotifs: ['⚜', '❦', '❧'],
    backgroundPattern: 'radial-gradient(circle at 20% 80%, rgba(201,169,98,0.05) 0%, transparent 50%), radial-gradient(circle at 80% 20%, rgba(201,169,98,0.05) 0%, transparent 50%)',
  },

  'wedding-modern-blush': {
    ...defaultStyle,
    greeting: 'Together with our families',
    closingText: 'We would be honored by your presence',
    ornamentEmoji: '◇',
    cornerMotif: 'geometric',
    dividerStyle: 'simple',
    borderStyle: 'solid',
    fontAccent: 'sans',
    culturalMotifs: ['◇', '▽', '△'],
    backgroundPattern: 'linear-gradient(135deg, rgba(212,165,165,0.03) 25%, transparent 25%, transparent 75%, rgba(212,165,165,0.03) 75%)',
  },

  'wedding-elegant-navy': {
    ...defaultStyle,
    greeting: 'With the blessing of the Almighty',
    closingText: 'Your gracious presence would be a great honor',
    ornamentEmoji: '⚜',
    cornerMotif: 'royal',
    dividerStyle: 'ornate',
    borderStyle: 'double',
    fontAccent: 'serif',
    culturalMotifs: ['⚜', '♔', '✧'],
    backgroundPattern: 'repeating-linear-gradient(45deg, transparent, transparent 35px, rgba(30,58,95,0.02) 35px, rgba(30,58,95,0.02) 70px)',
  },

  'wedding-rustic-sage': {
    ...defaultStyle,
    greeting: 'Dengan penuh syukur dan bahagia',
    closingText: 'Kehadiran Anda akan menjadi kebahagiaan tersendiri bagi kami',
    ornamentEmoji: '🌿',
    cornerMotif: 'floral',
    dividerStyle: 'leaf',
    borderStyle: 'none',
    fontAccent: 'serif',
    culturalMotifs: ['🌿', '🍃', '☘'],
    backgroundPattern: 'radial-gradient(ellipse at 10% 90%, rgba(122,158,126,0.06) 0%, transparent 50%)',
  },

  'wedding-minimalist-mono': {
    ...defaultStyle,
    greeting: 'We invite you to celebrate',
    closingText: 'Your presence is the greatest gift',
    ornamentEmoji: '—',
    cornerMotif: 'geometric',
    dividerStyle: 'simple',
    borderStyle: 'solid',
    fontAccent: 'sans',
    culturalMotifs: ['—', '|', '·'],
    backgroundPattern: null,
  },

  // ── Suku Templates ──

  'wedding-jawa-classic': {
    ...defaultStyle,
    greeting: 'Assalamu\'alaikum Wr. Wb.\nNgaturaken sedaya puji syukur dhumateng Gusti Allah SWT',
    closingText: 'Wonten pangajab kula, mugi Bapak/Ibu/Saudara kersa rawuh ing pawiwahan punika',
    ornamentEmoji: '꧁',
    cornerMotif: 'floral',
    dividerStyle: 'ornate',
    borderStyle: 'double',
    fontAccent: 'serif',
    culturalMotifs: ['꧁', '꧂', '❁'],
    backgroundPattern: 'repeating-conic-gradient(rgba(139,105,20,0.03) 0% 25%, transparent 0% 50%) 0 0 / 40px 40px',
    sectionRadius: '0.25rem',
    culturalIcons: [
      { emoji: '🏯', label: 'Candi Borobudur' },
      { emoji: '👘', label: 'Batik' },
      { emoji: '🎭', label: 'Wayang Kulit' },
    ],
  },

  'wedding-sunda-elegant': {
    ...defaultStyle,
    greeting: 'Assalamu\'alaikum Wr. Wb.\nKu berkahna Allah SWT, sim kuring ngahaturkeun',
    closingText: 'Hatur nuhun tina kasumpingan Bapa/Ibu/Saudara sadayana',
    ornamentEmoji: '❋',
    cornerMotif: 'floral',
    dividerStyle: 'leaf',
    borderStyle: 'double',
    fontAccent: 'serif',
    culturalMotifs: ['❋', '✿', '❁'],
    backgroundPattern: 'radial-gradient(circle at 50% 0%, rgba(46,125,50,0.05) 0%, transparent 60%)',
    sectionRadius: '1rem',
    culturalIcons: [
      { emoji: '🎶', label: 'Angklung' },
      { emoji: '🏔️', label: 'Gunung Tangkuban Parahu' },
      { emoji: '👘', label: 'Batik Sunda' },
    ],
  },

  'wedding-madura-bold': {
    ...defaultStyle,
    greeting: 'Bismillahirrahmanirrahim\nSanambhi asokkor ka Gusti Allah SWT',
    closingText: 'Kasokan kaula bileh Bapak/Ibu/Saudara kersa rabuwe',
    ornamentEmoji: '✦',
    cornerMotif: 'geometric',
    dividerStyle: 'diamond',
    borderStyle: 'ornate',
    fontAccent: 'serif',
    culturalMotifs: ['✦', '◆', '✧'],
    backgroundPattern: 'repeating-linear-gradient(0deg, transparent, transparent 20px, rgba(183,28,28,0.03) 20px, rgba(183,28,28,0.03) 21px)',
    sectionRadius: '0.5rem',
    culturalIcons: [
      { emoji: '🐂', label: 'Karapan Sapi' },
      { emoji: '🛶', label: 'Perahu Madura' },
      { emoji: '👘', label: 'Batik Madura' },
    ],
  },

  'wedding-batak-megah': {
    ...defaultStyle,
    greeting: 'Dalam nama Tuhan Yang Maha Kuasa\nHoras! Dengan penuh sukacita',
    closingText: 'Mauliate godang di hamu sude na boi ro mangalehen pasu-pasu',
    ornamentEmoji: '⊞',
    cornerMotif: 'geometric',
    dividerStyle: 'diamond',
    borderStyle: 'double',
    fontAccent: 'serif',
    culturalMotifs: ['⊞', '⊟', '◈'],
    backgroundPattern: 'repeating-linear-gradient(90deg, transparent, transparent 30px, rgba(139,0,0,0.02) 30px, rgba(139,0,0,0.02) 31px), repeating-linear-gradient(0deg, transparent, transparent 30px, rgba(139,0,0,0.02) 30px, rgba(139,0,0,0.02) 31px)',
    sectionRadius: '0.25rem',
    culturalIcons: [
      { emoji: '🏠', label: 'Rumah Bolon' },
      { emoji: '🎶', label: 'Gondang Batak' },
      { emoji: '🧣', label: 'Ulos' },
    ],
  },

  'wedding-minang-indah': {
    ...defaultStyle,
    greeting: 'Bismillahirrahmanirrahim\nAssalamu\'alaikum Warahmatullahi Wabarakatuh',
    closingText: 'Kahadiran Ibuk/Apak/Sudaro/i sangaik kami harokkan',
    ornamentEmoji: '▲',
    cornerMotif: 'geometric',
    dividerStyle: 'arrow',
    borderStyle: 'ornate',
    fontAccent: 'serif',
    culturalMotifs: ['▲', '△', '◆'],
    backgroundPattern: 'linear-gradient(60deg, rgba(198,40,40,0.03) 25%, transparent 25%, transparent 75%, rgba(198,40,40,0.03) 75%), linear-gradient(-60deg, rgba(198,40,40,0.03) 25%, transparent 25%, transparent 75%, rgba(198,40,40,0.03) 75%)',
    sectionRadius: '0.5rem',
    culturalIcons: [
      { emoji: '🏠', label: 'Rumah Gadang' },
      { emoji: '🗡️', label: 'Keris Minang' },
      { emoji: '🍽️', label: 'Rendang' },
    ],
  },

  'wedding-betawi-meriah': {
    ...defaultStyle,
    greeting: 'Bismillahirrahmanirrahim\nAssalamu\'alaikum Wr. Wb.',
    closingText: 'Aye ame keluarga ngundang ente semua buat dateng ye!',
    ornamentEmoji: '⊛',
    cornerMotif: 'floral',
    dividerStyle: 'ornate',
    borderStyle: 'ornate',
    fontAccent: 'serif',
    culturalMotifs: ['⊛', '❀', '✿'],
    backgroundPattern: 'radial-gradient(circle at 15% 15%, rgba(230,81,0,0.05) 0%, transparent 40%), radial-gradient(circle at 85% 85%, rgba(230,81,0,0.05) 0%, transparent 40%)',
    sectionRadius: '1rem',
    culturalIcons: [
      { emoji: '🎭', label: 'Ondel-ondel' },
      { emoji: '🎶', label: 'Gambang Kromong' },
      { emoji: '👕', label: 'Baju Sadariah' },
    ],
  },

  'wedding-bugis-megah': {
    ...defaultStyle,
    greeting: 'Bismillahirrahmanirrahim\nAssalamu\'alaikum Warahmatullahi Wabarakatuh',
    closingText: 'Tarima kasi loppo ri lao-laongnge nenniya',
    ornamentEmoji: '◈',
    cornerMotif: 'royal',
    dividerStyle: 'ornate',
    borderStyle: 'double',
    fontAccent: 'serif',
    culturalMotifs: ['◈', '❖', '✧'],
    backgroundPattern: 'repeating-linear-gradient(135deg, transparent, transparent 40px, rgba(136,14,79,0.02) 40px, rgba(136,14,79,0.02) 41px)',
    sectionRadius: '0.5rem',
    culturalIcons: [
      { emoji: '⛵', label: 'Perahu Pinisi' },
      { emoji: '🗡️', label: 'Badik' },
      { emoji: '📜', label: 'Lontara' },
    ],
  },

  'wedding-banten-klasik': {
    ...defaultStyle,
    greeting: 'Bismillahirrahmanirrahim\nAssalamu\'alaikum Wr. Wb.',
    closingText: 'Mugi-mugi Allah SWT ngalebetkeun berkah ka urang sadaya',
    ornamentEmoji: '⬡',
    cornerMotif: 'geometric',
    dividerStyle: 'diamond',
    borderStyle: 'solid',
    fontAccent: 'serif',
    culturalMotifs: ['⬡', '⬢', '◇'],
    backgroundPattern: 'radial-gradient(circle at 50% 50%, rgba(93,64,55,0.04) 0%, transparent 70%)',
    sectionRadius: '0.25rem',
    culturalIcons: [
      { emoji: '🕌', label: 'Masjid Agung Banten' },
      { emoji: '🗡️', label: 'Golok' },
      { emoji: '👘', label: 'Batik Banten' },
    ],
  },

  'wedding-banjar-indah': {
    ...defaultStyle,
    greeting: 'Bismillahirrahmanirrahim\nAssalamu\'alaikum Warahmatullahi Wabarakatuh',
    closingText: 'Terima kasih lawan kehadiran Pian sekalian',
    ornamentEmoji: '✦',
    cornerMotif: 'royal',
    dividerStyle: 'wave',
    borderStyle: 'double',
    fontAccent: 'serif',
    culturalMotifs: ['✦', '❋', '✧'],
    backgroundPattern: 'linear-gradient(180deg, rgba(249,168,37,0.05) 0%, transparent 30%), linear-gradient(0deg, rgba(249,168,37,0.05) 0%, transparent 30%)',
    sectionRadius: '0.75rem',
    culturalIcons: [
      { emoji: '🏠', label: 'Rumah Bubungan Tinggi' },
      { emoji: '🚣', label: 'Jukung' },
      { emoji: '👘', label: 'Sasirangan' },
    ],
  },

  'wedding-bali-sakral': {
    ...defaultStyle,
    greeting: 'Om Swastiastu\nAtas Asung Kertha Wara Nugraha Ida Sang Hyang Widhi Wasa',
    closingText: 'Om Shanti, Shanti, Shanti Om',
    ornamentEmoji: '☸',
    cornerMotif: 'floral',
    dividerStyle: 'ornate',
    borderStyle: 'ornate',
    fontAccent: 'serif',
    culturalMotifs: ['☸', '❁', '✿'],
    backgroundPattern: 'radial-gradient(circle at 50% 0%, rgba(78,52,46,0.06) 0%, transparent 50%), radial-gradient(circle at 50% 100%, rgba(78,52,46,0.06) 0%, transparent 50%)',
    sectionRadius: '0.25rem',
    culturalIcons: [
      { emoji: '🛕', label: 'Pura' },
      { emoji: '💃', label: 'Tari Kecak' },
      { emoji: '👘', label: 'Kain Kamen' },
    ],
  },

  'wedding-sasak-anggun': {
    ...defaultStyle,
    greeting: 'Bismillahirrahmanirrahim\nAssalamu\'alaikum Wr. Wb.',
    closingText: 'Tampaq side dateng jari penggembira hati kami',
    ornamentEmoji: '✧',
    cornerMotif: 'geometric',
    dividerStyle: 'diamond',
    borderStyle: 'double',
    fontAccent: 'serif',
    culturalMotifs: ['✧', '◇', '❖'],
    backgroundPattern: 'repeating-linear-gradient(45deg, rgba(106,27,154,0.02) 0px, rgba(106,27,154,0.02) 1px, transparent 1px, transparent 20px), repeating-linear-gradient(-45deg, rgba(106,27,154,0.02) 0px, rgba(106,27,154,0.02) 1px, transparent 1px, transparent 20px)',
    sectionRadius: '0.5rem',
    culturalIcons: [
      { emoji: '🏡', label: 'Bale Tani' },
      { emoji: '🧣', label: 'Tenun Lombok' },
      { emoji: '🎶', label: 'Gendang Beleq' },
    ],
  },

  'wedding-aceh-mulia': {
    ...defaultStyle,
    greeting: 'Bismillahirrahmanirrahim\nAssalamu\'alaikum Warahmatullahi Wabarakatuh',
    closingText: 'Ureueng nyang kamoe peumulia, lon teurimong gaseh that mandum na hadir',
    ornamentEmoji: '✦',
    cornerMotif: 'islamic',
    dividerStyle: 'diamond',
    borderStyle: 'double',
    fontAccent: 'serif',
    culturalMotifs: ['✦', '✶', '✸'],
    backgroundPattern: 'repeating-conic-gradient(rgba(27,94,32,0.03) 0% 25%, transparent 0% 50%) 0 0 / 30px 30px',
    sectionRadius: '0.5rem',
    culturalIcons: [
      { emoji: '🕌', label: 'Masjid Raya Baiturrahman' },
      { emoji: '🗡️', label: 'Rencong' },
      { emoji: '💃', label: 'Tari Saman' },
    ],
  },

  'wedding-dayak-agung': {
    ...defaultStyle,
    greeting: 'Tabe Salamat\nDengan mengucap syukur kepada Jubata/Tuhan Yang Maha Esa',
    closingText: 'Terima kasih atas kehadiran Saudara/i dalam perayaan ini',
    ornamentEmoji: '⟐',
    cornerMotif: 'tribal',
    dividerStyle: 'arrow',
    borderStyle: 'ornate',
    fontAccent: 'serif',
    culturalMotifs: ['⟐', '⏣', '⬡'],
    backgroundPattern: 'repeating-linear-gradient(90deg, rgba(216,67,21,0.03) 0px, rgba(216,67,21,0.03) 2px, transparent 2px, transparent 15px)',
    sectionRadius: '0.25rem',
    culturalIcons: [
      { emoji: '🗿', label: 'Patung Totem' },
      { emoji: '🪶', label: 'Hiasan Bulu' },
      { emoji: '🏠', label: 'Rumah Panjang' },
    ],
  },

  'wedding-makassar-gagah': {
    ...defaultStyle,
    greeting: 'Bismillahirrahmanirrahim\nAssalamu\'alaikum Warahmatullahi Wabarakatuh',
    closingText: 'Tarima kasi maega ri sininna tau battu mannyame',
    ornamentEmoji: '❖',
    cornerMotif: 'royal',
    dividerStyle: 'ornate',
    borderStyle: 'double',
    fontAccent: 'serif',
    culturalMotifs: ['❖', '◆', '✦'],
    backgroundPattern: 'radial-gradient(circle at 0% 50%, rgba(198,40,40,0.04) 0%, transparent 50%), radial-gradient(circle at 100% 50%, rgba(198,40,40,0.04) 0%, transparent 50%)',
    sectionRadius: '0.5rem',
    culturalIcons: [
      { emoji: '⛵', label: 'Perahu Phinisi' },
      { emoji: '🗡️', label: 'Badik' },
      { emoji: '🧢', label: 'Passapu' },
    ],
  },

  'wedding-melayu-pesona': {
    ...defaultStyle,
    greeting: 'Bismillahirrahmanirrahim\nAssalamu\'alaikum Warahmatullahi Wabarakatuh',
    closingText: 'Sembah sujud dan setinggi-tinggi terima kasih atas kehadiran Tuan/Puan',
    ornamentEmoji: '♛',
    cornerMotif: 'royal',
    dividerStyle: 'ornate',
    borderStyle: 'double',
    fontAccent: 'serif',
    culturalMotifs: ['♛', '❦', '⚜'],
    backgroundPattern: 'linear-gradient(45deg, rgba(251,192,45,0.04) 25%, transparent 25%, transparent 75%, rgba(251,192,45,0.04) 75%), linear-gradient(-45deg, rgba(251,192,45,0.04) 25%, transparent 25%, transparent 75%, rgba(251,192,45,0.04) 75%)',
    sectionRadius: '0.75rem',
    culturalIcons: [
      { emoji: '👑', label: 'Tanjak' },
      { emoji: '🕌', label: 'Masjid Melayu' },
      { emoji: '🎶', label: 'Zapin' },
    ],
  },

  'wedding-toraja-sakral': {
    ...defaultStyle,
    greeting: 'Puang Matua umbai makarorroi\nDengan berkat dari Yang Maha Kuasa',
    closingText: 'Kurre sumanga\' na lan tu battu mangrara tondok',
    ornamentEmoji: '▽',
    cornerMotif: 'tribal',
    dividerStyle: 'arrow',
    borderStyle: 'ornate',
    fontAccent: 'serif',
    culturalMotifs: ['▽', '△', '◈'],
    backgroundPattern: 'repeating-linear-gradient(0deg, transparent, transparent 25px, rgba(183,28,28,0.03) 25px, rgba(183,28,28,0.03) 26px), repeating-linear-gradient(90deg, transparent, transparent 25px, rgba(33,33,33,0.03) 25px, rgba(33,33,33,0.03) 26px)',
    sectionRadius: '0.25rem',
    culturalIcons: [
      { emoji: '🏠', label: 'Tongkonan' },
      { emoji: '🐃', label: 'Kerbau' },
      { emoji: '🗿', label: 'Patung Tau-Tau' },
    ],
  },

  'wedding-ambon-cerah': {
    ...defaultStyle,
    greeting: 'Salam Sejahtera\nDengan mengucap syukur kepada Tuhan Yang Maha Esa',
    closingText: 'Katong samua berharap Bapa/Mama/Saudara datang par kasi berkat',
    ornamentEmoji: '🐚',
    cornerMotif: 'wave',
    dividerStyle: 'wave',
    borderStyle: 'solid',
    fontAccent: 'sans',
    culturalMotifs: ['〰', '≋', '∿'],
    backgroundPattern: 'radial-gradient(ellipse at 50% 100%, rgba(2,119,189,0.06) 0%, transparent 60%)',
    sectionRadius: '1rem',
    culturalIcons: [
      { emoji: '🎵', label: 'Tifa' },
      { emoji: '🎶', label: 'Musik Totobuang' },
      { emoji: '⚓', label: 'Budaya Bahari' },
    ],
  },

  'wedding-papua-mulia': {
    ...defaultStyle,
    greeting: 'Nabeluk! Wa... Wa... Wa...\nDengan berkat Tuhan Yang Maha Esa',
    closingText: 'Terima kasih. Kami menanti kehadiran Bapak/Ibu/Saudara/i',
    ornamentEmoji: '◈',
    cornerMotif: 'tribal',
    dividerStyle: 'arrow',
    borderStyle: 'ornate',
    fontAccent: 'serif',
    culturalMotifs: ['◈', '⬡', '⏣'],
    backgroundPattern: 'repeating-linear-gradient(60deg, rgba(109,76,65,0.03) 0px, rgba(109,76,65,0.03) 2px, transparent 2px, transparent 12px)',
    sectionRadius: '0.25rem',
    culturalIcons: [
      { emoji: '🪶', label: 'Koteka' },
      { emoji: '🎵', label: 'Tifa Papua' },
      { emoji: '🏞️', label: 'Pegunungan Papua' },
    ],
  },

  'wedding-tionghoa-harmoni': {
    ...defaultStyle,
    greeting: '囍 Shuāngxǐ 囍\nDengan penuh sukacita dan syukur',
    closingText: 'Xièxiè — Terima kasih atas kehadiran dan doa restu',
    ornamentEmoji: '囍',
    cornerMotif: 'geometric',
    dividerStyle: 'ornate',
    borderStyle: 'double',
    fontAccent: 'serif',
    culturalMotifs: ['囍', '福', '❀'],
    backgroundPattern: 'radial-gradient(circle at 10% 10%, rgba(211,47,47,0.05) 0%, transparent 40%), radial-gradient(circle at 90% 90%, rgba(211,47,47,0.05) 0%, transparent 40%)',
    sectionRadius: '0.5rem',
    culturalIcons: [
      { emoji: '🧧', label: 'Lampion Merah' },
      { emoji: '🐉', label: 'Barongsai' },
      { emoji: '🧨', label: 'Imlek' },
    ],
  },

  'wedding-lampung-agung': {
    ...defaultStyle,
    greeting: 'Bismillahirrahmanirrahim\nTabik pun, ngiring kilu ampun',
    closingText: 'Tabik pun, terima kasih atas kehadiran Bapak/Ibu/Saudara',
    ornamentEmoji: '⬢',
    cornerMotif: 'geometric',
    dividerStyle: 'diamond',
    borderStyle: 'double',
    fontAccent: 'serif',
    culturalMotifs: ['⬢', '◆', '✧'],
    backgroundPattern: 'repeating-linear-gradient(120deg, transparent, transparent 35px, rgba(141,110,99,0.03) 35px, rgba(141,110,99,0.03) 36px)',
    sectionRadius: '0.5rem',
    culturalIcons: [
      { emoji: '👑', label: 'Siger' },
      { emoji: '👘', label: 'Kain Tapis' },
      { emoji: '🏠', label: 'Nuwo Sesat' },
    ],
  },

  // ══════════════════ NEW WEDDING TEMPLATES ══════════════════

  // ── Religion Niche ──

  'wedding-islami-mewah': {
    ...defaultStyle,
    greeting: 'بِسْمِ اللَّهِ الرَّحْمَنِ الرَّحِيمِ\nAssalamu\'alaikum Warahmatullahi Wabarakatuh',
    closingText: 'Jazakumullahu khairan katsiran atas doa dan kehadirannya',
    ornamentEmoji: '☪',
    cornerMotif: 'islamic',
    dividerStyle: 'ornate',
    borderStyle: 'double',
    fontAccent: 'serif',
    culturalMotifs: ['☪', '✦', '✶'],
    backgroundPattern: 'repeating-conic-gradient(rgba(27,94,32,0.04) 0% 25%, transparent 0% 50%) 0 0 / 25px 25px',
    sectionRadius: '0.5rem',
    culturalIcons: [
      { emoji: '🕌', label: 'Masjid' },
      { emoji: '🌙', label: 'Bulan Sabit' },
      { emoji: '📖', label: 'Al-Quran' },
    ],
  },

  'wedding-kristen-sakral': {
    ...defaultStyle,
    greeting: 'Salam Sejahtera dalam Kasih Kristus\nDengan mengucap syukur kepada Tuhan',
    closingText: 'Tuhan memberkati. Terima kasih atas kehadiran dan doa restu Saudara/i',
    ornamentEmoji: '✝',
    cornerMotif: 'floral',
    dividerStyle: 'ornate',
    borderStyle: 'double',
    fontAccent: 'serif',
    culturalMotifs: ['✝', '🕊', '❦'],
    backgroundPattern: 'radial-gradient(circle at 50% 10%, rgba(92,107,192,0.05) 0%, transparent 50%), radial-gradient(circle at 50% 90%, rgba(92,107,192,0.03) 0%, transparent 50%)',
    sectionRadius: '0.75rem',
    culturalIcons: [
      { emoji: '⛪', label: 'Gereja' },
      { emoji: '🕊', label: 'Merpati Damai' },
      { emoji: '🔔', label: 'Lonceng Gereja' },
    ],
  },

  'wedding-katolik-agung': {
    ...defaultStyle,
    greeting: 'In Nomine Patris et Filii et Spiritus Sancti\nDengan rahmat Tuhan Yang Maha Esa',
    closingText: 'Semoga Tuhan senantiasa memberkati pernikahan kami. Terima kasih atas doa restu',
    ornamentEmoji: '⚜',
    cornerMotif: 'royal',
    dividerStyle: 'ornate',
    borderStyle: 'double',
    fontAccent: 'serif',
    culturalMotifs: ['⚜', '✝', '❦'],
    backgroundPattern: 'repeating-linear-gradient(45deg, transparent, transparent 40px, rgba(109,76,65,0.02) 40px, rgba(109,76,65,0.02) 41px)',
    sectionRadius: '0.5rem',
    culturalIcons: [
      { emoji: '⛪', label: 'Katedral' },
      { emoji: '📿', label: 'Rosario' },
      { emoji: '🕯', label: 'Lilin Sakral' },
    ],
  },

  'wedding-hindu-suci': {
    ...defaultStyle,
    greeting: 'Om Swastiastu 🙏\nDengan berkat Ida Sang Hyang Widhi Wasa',
    closingText: 'Om Shanti Shanti Shanti Om. Terima kasih atas kehadiran dan doa restu',
    ornamentEmoji: '🕉',
    cornerMotif: 'floral',
    dividerStyle: 'ornate',
    borderStyle: 'ornate',
    fontAccent: 'serif',
    culturalMotifs: ['🕉', '☸', '✿'],
    backgroundPattern: 'radial-gradient(circle at 50% 50%, rgba(230,81,0,0.04) 0%, transparent 50%), radial-gradient(circle at 20% 20%, rgba(230,81,0,0.03) 0%, transparent 30%), radial-gradient(circle at 80% 80%, rgba(230,81,0,0.03) 0%, transparent 30%)',
    sectionRadius: '0.75rem',
    culturalIcons: [
      { emoji: '🕉', label: 'Simbol Om' },
      { emoji: '🪷', label: 'Bunga Teratai' },
      { emoji: '🛕', label: 'Pura Hindu' },
    ],
  },

  'wedding-buddha-harmoni': {
    ...defaultStyle,
    greeting: 'Namo Buddhaya 🙏\nDengan penuh sukacita dan syukur',
    closingText: 'Sadhu Sadhu Sadhu. Semoga kebahagiaan ini membawa kedamaian',
    ornamentEmoji: '☸',
    cornerMotif: 'floral',
    dividerStyle: 'wave',
    borderStyle: 'double',
    fontAccent: 'serif',
    culturalMotifs: ['☸', '🪷', '✦'],
    backgroundPattern: 'radial-gradient(circle at 50% 0%, rgba(249,168,37,0.05) 0%, transparent 50%), radial-gradient(circle at 50% 100%, rgba(249,168,37,0.03) 0%, transparent 40%)',
    sectionRadius: '1rem',
    culturalIcons: [
      { emoji: '☸', label: 'Roda Dharma' },
      { emoji: '🪷', label: 'Teratai' },
      { emoji: '🏯', label: 'Vihara' },
    ],
  },

  // ── Famous City Niche ──

  'wedding-paris-romantis': {
    ...defaultStyle,
    greeting: 'Avec amour et joie\nDengan cinta dan kebahagiaan',
    closingText: 'Merci beaucoup — Terima kasih atas kehadiran dan doa restu Anda',
    ornamentEmoji: '🗼',
    cornerMotif: 'floral',
    dividerStyle: 'ornate',
    borderStyle: 'double',
    fontAccent: 'script',
    culturalMotifs: ['🗼', '❀', '💜'],
    backgroundPattern: 'linear-gradient(180deg, rgba(126,87,194,0.04) 0%, transparent 40%), radial-gradient(circle at 80% 70%, rgba(126,87,194,0.03) 0%, transparent 50%)',
    sectionRadius: '1rem',
    culturalIcons: [
      { emoji: '🗼', label: 'Eiffel Tower' },
      { emoji: '🌹', label: 'Mawar Prancis' },
      { emoji: '🥐', label: 'Croissant' },
    ],
  },

  'wedding-tokyo-sakura': {
    ...defaultStyle,
    greeting: 'ご結婚おめでとうございます\nDengan penuh sukacita',
    closingText: 'Arigatou gozaimasu — Terima kasih atas kehadiran Anda',
    ornamentEmoji: '🌸',
    cornerMotif: 'none',
    dividerStyle: 'simple',
    borderStyle: 'solid',
    fontAccent: 'sans',
    culturalMotifs: ['🌸', '🎋', '🏯'],
    backgroundPattern: 'radial-gradient(circle at 80% 15%, rgba(233,30,99,0.05) 0%, transparent 40%), radial-gradient(circle at 20% 85%, rgba(233,30,99,0.03) 0%, transparent 40%)',
    sectionRadius: '0.25rem',
    culturalIcons: [
      { emoji: '🌸', label: 'Bunga Sakura' },
      { emoji: '⛩', label: 'Torii Gate' },
      { emoji: '🎎', label: 'Boneka Tradisional' },
    ],
  },

  'wedding-istanbul-megah': {
    ...defaultStyle,
    greeting: 'Bismillahirrahmanirrahim\nDengan penuh sukacita dan syukur',
    closingText: 'Teşekkürler — Terima kasih atas kehadiran dan doa restu',
    ornamentEmoji: '🕌',
    cornerMotif: 'islamic',
    dividerStyle: 'ornate',
    borderStyle: 'ornate',
    fontAccent: 'serif',
    culturalMotifs: ['🕌', '✦', '◈'],
    backgroundPattern: 'repeating-conic-gradient(rgba(0,131,143,0.03) 0% 25%, transparent 0% 50%) 0 0 / 30px 30px, radial-gradient(circle at 50% 50%, rgba(0,131,143,0.02) 0%, transparent 60%)',
    sectionRadius: '0.75rem',
    culturalIcons: [
      { emoji: '🕌', label: 'Hagia Sophia' },
      { emoji: '🧿', label: 'Nazar Boncuğu' },
      { emoji: '🌷', label: 'Tulip Turki' },
    ],
  },

  'wedding-jogja-heritage': {
    ...defaultStyle,
    greeting: 'Assalamu\'alaikum Wr. Wb.\nKanthi raos syukur dhumateng Gusti Allah SWT',
    closingText: 'Maturnuwun sanget dhumateng sedaya tamu ingkang sampun rawuh',
    ornamentEmoji: '꧁',
    cornerMotif: 'floral',
    dividerStyle: 'ornate',
    borderStyle: 'double',
    fontAccent: 'serif',
    culturalMotifs: ['꧁', '꧂', '◈'],
    backgroundPattern: 'repeating-conic-gradient(rgba(121,85,72,0.03) 0% 25%, transparent 0% 50%) 0 0 / 35px 35px',
    sectionRadius: '0.25rem',
    culturalIcons: [
      { emoji: '🏯', label: 'Keraton Jogja' },
      { emoji: '🎭', label: 'Wayang' },
      { emoji: '👘', label: 'Batik Parang' },
    ],
  },

  'wedding-venice-elegan': {
    ...defaultStyle,
    greeting: 'Con amore e gioia\nDengan cinta dan kebahagiaan',
    closingText: 'Grazie — Terima kasih telah hadir merayakan bersama kami',
    ornamentEmoji: '⚓',
    cornerMotif: 'royal',
    dividerStyle: 'wave',
    borderStyle: 'double',
    fontAccent: 'serif',
    culturalMotifs: ['⚓', '🎭', '✧'],
    backgroundPattern: 'linear-gradient(135deg, rgba(21,101,192,0.04) 0%, transparent 50%), linear-gradient(-135deg, rgba(21,101,192,0.03) 0%, transparent 50%)',
    sectionRadius: '0.75rem',
    culturalIcons: [
      { emoji: '🚣', label: 'Gondola' },
      { emoji: '🎭', label: 'Topeng Venesia' },
      { emoji: '🌉', label: 'Jembatan Rialto' },
    ],
  },

  // ── Climate/Nature Niche ──

  'wedding-garden-boho': {
    ...defaultStyle,
    greeting: 'With love and wildflowers\nDengan cinta dan bunga liar',
    closingText: 'Your presence blooms our happiness — Kehadiran Anda menyempurnakan kebahagiaan',
    ornamentEmoji: '🌻',
    cornerMotif: 'floral',
    dividerStyle: 'leaf',
    borderStyle: 'none',
    fontAccent: 'serif',
    culturalMotifs: ['🌻', '🌾', '🍂'],
    backgroundPattern: 'radial-gradient(ellipse at 10% 90%, rgba(141,110,99,0.06) 0%, transparent 50%), radial-gradient(ellipse at 90% 10%, rgba(141,110,99,0.04) 0%, transparent 50%)',
    sectionRadius: '1rem',
    culturalIcons: [
      { emoji: '🌻', label: 'Bunga Matahari' },
      { emoji: '🌿', label: 'Daun Eucalyptus' },
      { emoji: '🪶', label: 'Bulu Bohemian' },
    ],
  },

  'wedding-pantai-sunset': {
    ...defaultStyle,
    greeting: 'Under the golden sky\nDi bawah langit keemasan',
    closingText: 'Like the ocean meets the shore — Seperti laut bertemu pantai, cinta kami abadi',
    ornamentEmoji: '🐚',
    cornerMotif: 'wave',
    dividerStyle: 'wave',
    borderStyle: 'none',
    fontAccent: 'sans',
    culturalMotifs: ['🐚', '🌊', '🌅'],
    backgroundPattern: 'linear-gradient(180deg, rgba(230,81,0,0.05) 0%, transparent 30%), linear-gradient(0deg, rgba(21,101,192,0.03) 0%, transparent 30%)',
    sectionRadius: '1.5rem',
    culturalIcons: [
      { emoji: '🌅', label: 'Sunset' },
      { emoji: '🐚', label: 'Kerang Laut' },
      { emoji: '🌴', label: 'Kelapa Pantai' },
    ],
  },

  'wedding-winter-frost': {
    ...defaultStyle,
    greeting: 'In the magic of winter\nDalam pesona musim dingin',
    closingText: 'Our love is warm even in the coldest days — Cinta kami hangat di hari yang paling dingin',
    ornamentEmoji: '❄',
    cornerMotif: 'geometric',
    dividerStyle: 'dotted',
    borderStyle: 'solid',
    fontAccent: 'sans',
    culturalMotifs: ['❄', '✧', '❆'],
    backgroundPattern: 'radial-gradient(circle at 20% 20%, rgba(79,195,247,0.06) 0%, transparent 40%), radial-gradient(circle at 80% 80%, rgba(79,195,247,0.04) 0%, transparent 40%), radial-gradient(circle at 50% 50%, rgba(79,195,247,0.02) 0%, transparent 60%)',
    sectionRadius: '0.75rem',
    culturalIcons: [
      { emoji: '❄', label: 'Kristal Es' },
      { emoji: '⛄', label: 'Manusia Salju' },
      { emoji: '🌨', label: 'Salju Turun' },
    ],
  },

  'wedding-autumn-warm': {
    ...defaultStyle,
    greeting: 'As the leaves turn golden\nSaat dedaunan berubah keemasan',
    closingText: 'Fall in love with us — Rayakan cinta kami di musim yang indah ini',
    ornamentEmoji: '🍂',
    cornerMotif: 'floral',
    dividerStyle: 'leaf',
    borderStyle: 'none',
    fontAccent: 'serif',
    culturalMotifs: ['🍂', '🍁', '🌾'],
    backgroundPattern: 'linear-gradient(180deg, rgba(230,74,25,0.05) 0%, transparent 40%), radial-gradient(ellipse at 80% 80%, rgba(230,74,25,0.04) 0%, transparent 50%)',
    sectionRadius: '0.75rem',
    culturalIcons: [
      { emoji: '🍁', label: 'Daun Maple' },
      { emoji: '🎃', label: 'Labu Musim Gugur' },
      { emoji: '🌾', label: 'Gandum Emas' },
    ],
  },

  // ── Identity/Culture Niche ──

  'wedding-nusantara-fusion': {
    ...defaultStyle,
    greeting: 'Bhinneka Tunggal Ika\nDengan penuh rasa syukur dan kebahagiaan',
    closingText: 'Satu dalam keberagaman — Terima kasih atas kehadiran dan doa restu',
    ornamentEmoji: '🦅',
    cornerMotif: 'geometric',
    dividerStyle: 'ornate',
    borderStyle: 'ornate',
    fontAccent: 'serif',
    culturalMotifs: ['🦅', '◈', '✦'],
    backgroundPattern: 'repeating-linear-gradient(60deg, rgba(198,40,40,0.02) 0px, rgba(198,40,40,0.02) 1px, transparent 1px, transparent 25px), repeating-linear-gradient(-60deg, rgba(198,40,40,0.02) 0px, rgba(198,40,40,0.02) 1px, transparent 1px, transparent 25px)',
    sectionRadius: '0.5rem',
    culturalIcons: [
      { emoji: '🦅', label: 'Garuda Pancasila' },
      { emoji: '🗺', label: 'Peta Nusantara' },
      { emoji: '🎶', label: 'Gamelan' },
    ],
  },

  'wedding-arab-luxury': {
    ...defaultStyle,
    greeting: 'بِسْمِ اللَّهِ الرَّحْمَنِ الرَّحِيمِ\nDengan Nama Allah Yang Maha Pengasih',
    closingText: 'بارك الله لكما — Semoga Allah memberkahi pernikahan ini',
    ornamentEmoji: '✧',
    cornerMotif: 'islamic',
    dividerStyle: 'ornate',
    borderStyle: 'double',
    fontAccent: 'serif',
    culturalMotifs: ['✧', '◈', '❖'],
    backgroundPattern: 'repeating-conic-gradient(rgba(201,169,98,0.05) 0% 25%, transparent 0% 50%) 0 0 / 20px 20px',
    sectionRadius: '0.5rem',
    culturalIcons: [
      { emoji: '🕌', label: 'Masjid Megah' },
      { emoji: '🌴', label: 'Kurma' },
      { emoji: '✨', label: 'Bintang Arab' },
    ],
  },

  'wedding-india-bollywood': {
    ...defaultStyle,
    greeting: 'शुभ विवाह 💐\nDengan penuh sukacita dan kebahagiaan',
    closingText: 'Dhanyavaad — Terima kasih atas kehadiran dan restu Anda',
    ornamentEmoji: '🪷',
    cornerMotif: 'floral',
    dividerStyle: 'ornate',
    borderStyle: 'ornate',
    fontAccent: 'serif',
    culturalMotifs: ['🪷', '✦', '◈'],
    backgroundPattern: 'radial-gradient(circle at 20% 20%, rgba(173,20,87,0.05) 0%, transparent 40%), radial-gradient(circle at 80% 80%, rgba(173,20,87,0.04) 0%, transparent 40%), radial-gradient(circle at 50% 50%, rgba(173,20,87,0.02) 0%, transparent 60%)',
    sectionRadius: '0.75rem',
    culturalIcons: [
      { emoji: '🪷', label: 'Teratai India' },
      { emoji: '💃', label: 'Tari Bollywood' },
      { emoji: '🐘', label: 'Gajah Suci' },
    ],
  },

  'wedding-korea-hanbok': {
    ...defaultStyle,
    greeting: '축하합니다 — Selamat!\nDengan kebahagiaan yang membara',
    closingText: '감사합니다 — Kamsahamnida, terima kasih atas kehadiran Anda',
    ornamentEmoji: '🌸',
    cornerMotif: 'none',
    dividerStyle: 'simple',
    borderStyle: 'solid',
    fontAccent: 'sans',
    culturalMotifs: ['🌸', '🏮', '✧'],
    backgroundPattern: 'radial-gradient(circle at 50% 0%, rgba(216,27,96,0.04) 0%, transparent 40%), radial-gradient(circle at 50% 100%, rgba(216,27,96,0.03) 0%, transparent 40%)',
    sectionRadius: '0.5rem',
    culturalIcons: [
      { emoji: '👘', label: 'Hanbok' },
      { emoji: '🏮', label: 'Lentera Korea' },
      { emoji: '🎎', label: 'Couple Figure' },
    ],
  },

  // ── Modern Lifestyle Niche ──

  'wedding-industrial-chic': {
    ...defaultStyle,
    greeting: 'You + Me = Forever\nDengan penuh cinta',
    closingText: 'Your presence means the world to us — Kehadiran Anda sangat berarti',
    ornamentEmoji: '⚙',
    cornerMotif: 'geometric',
    dividerStyle: 'simple',
    borderStyle: 'solid',
    fontAccent: 'sans',
    culturalMotifs: ['⚙', '◇', '·'],
    backgroundPattern: 'repeating-linear-gradient(90deg, rgba(121,85,72,0.03) 0px, rgba(121,85,72,0.03) 1px, transparent 1px, transparent 30px), repeating-linear-gradient(0deg, rgba(121,85,72,0.03) 0px, rgba(121,85,72,0.03) 1px, transparent 1px, transparent 30px)',
    sectionRadius: '0.25rem',
    culturalIcons: [
      { emoji: '⚙', label: 'Gear' },
      { emoji: '💡', label: 'Edison Bulb' },
      { emoji: '🧱', label: 'Exposed Brick' },
    ],
  },

  'wedding-art-deco-gatsby': {
    ...defaultStyle,
    greeting: 'The Roaring Romance\nSebuah perayaan cinta yang megah',
    closingText: 'Old sport — Terima kasih telah hadir merayakan malam yang penuh kemewahan ini',
    ornamentEmoji: '◈',
    cornerMotif: 'geometric',
    dividerStyle: 'diamond',
    borderStyle: 'double',
    fontAccent: 'serif',
    culturalMotifs: ['◈', '▽', '◇'],
    backgroundPattern: 'repeating-linear-gradient(45deg, transparent, transparent 20px, rgba(201,169,98,0.04) 20px, rgba(201,169,98,0.04) 21px), repeating-linear-gradient(-45deg, transparent, transparent 20px, rgba(201,169,98,0.04) 20px, rgba(201,169,98,0.04) 21px)',
    sectionRadius: '0.25rem',
    culturalIcons: [
      { emoji: '🥂', label: 'Champagne' },
      { emoji: '🎷', label: 'Jazz Saxophone' },
      { emoji: '💎', label: 'Art Deco Diamond' },
    ],
  },

  // ══════════════════ KHITANAN TEMPLATES ══════════════════

  'khitanan-festive-blue': {
    ...defaultStyle,
    greeting: 'Bismillahirrahmanirrahim\nAssalamu\'alaikum Wr. Wb.',
    closingText: 'Semoga Allah SWT memberikan keberkahan',
    ornamentEmoji: '⭐',
    cornerMotif: 'geometric',
    dividerStyle: 'dotted',
    borderStyle: 'solid',
    fontAccent: 'sans',
    culturalMotifs: ['⭐', '✦', '◇'],
    backgroundPattern: 'radial-gradient(circle at 80% 20%, rgba(33,150,243,0.06) 0%, transparent 50%)',
    sectionRadius: '1rem',
  },

  'khitanan-islamic-green': {
    ...defaultStyle,
    greeting: 'Bismillahirrahmanirrahim\nAssalamu\'alaikum Warahmatullahi Wabarakatuh',
    closingText: 'Jazakumullahu khairan atas doa dan kehadiran',
    ornamentEmoji: '☪',
    cornerMotif: 'islamic',
    dividerStyle: 'ornate',
    borderStyle: 'double',
    fontAccent: 'serif',
    culturalMotifs: ['☪', '✦', '✶'],
    backgroundPattern: 'repeating-conic-gradient(rgba(46,125,50,0.03) 0% 25%, transparent 0% 50%) 0 0 / 35px 35px',
    sectionRadius: '0.5rem',
  },

  'khitanan-golden-festive': {
    ...defaultStyle,
    greeting: 'Bismillahirrahmanirrahim\nDengan mengharap ridho Allah SWT',
    closingText: 'Terima kasih atas doa dan kehadirannya',
    ornamentEmoji: '✨',
    cornerMotif: 'royal',
    dividerStyle: 'ornate',
    borderStyle: 'double',
    fontAccent: 'serif',
    culturalMotifs: ['✨', '⚜', '✦'],
    backgroundPattern: 'linear-gradient(180deg, rgba(212,160,23,0.05) 0%, transparent 40%)',
    sectionRadius: '0.75rem',
  },

  'khitanan-playful-teal': {
    ...defaultStyle,
    greeting: 'Assalamu\'alaikum Wr. Wb.\nDengan rasa syukur dan bahagia',
    closingText: 'Kehadiran Anda sangat berarti bagi kami',
    ornamentEmoji: '🎊',
    cornerMotif: 'geometric',
    dividerStyle: 'dotted',
    borderStyle: 'solid',
    fontAccent: 'sans',
    culturalMotifs: ['◇', '△', '○'],
    backgroundPattern: 'radial-gradient(circle at 20% 80%, rgba(0,137,123,0.05) 0%, transparent 50%)',
    sectionRadius: '1rem',
  },

  // ══════════════════ HAJATAN TEMPLATES ══════════════════

  'hajatan-warm-earth': {
    ...defaultStyle,
    greeting: 'Alhamdulillah\nDengan penuh rasa syukur',
    closingText: 'Kehadiran Bapak/Ibu menjadi kebahagiaan tersendiri',
    ornamentEmoji: '🌾',
    cornerMotif: 'floral',
    dividerStyle: 'leaf',
    borderStyle: 'none',
    fontAccent: 'serif',
    culturalMotifs: ['🌾', '🍂', '🌻'],
    backgroundPattern: 'radial-gradient(ellipse at 50% 100%, rgba(141,110,99,0.05) 0%, transparent 60%)',
    sectionRadius: '0.75rem',
  },

  'hajatan-simple-sage': {
    ...defaultStyle,
    greeting: 'Dengan penuh rasa syukur',
    closingText: 'Terima kasih atas kehadiran dan doa restu',
    ornamentEmoji: '✿',
    cornerMotif: 'floral',
    dividerStyle: 'simple',
    borderStyle: 'none',
    fontAccent: 'sans',
    culturalMotifs: ['✿', '❀', '·'],
    backgroundPattern: null,
    sectionRadius: '1rem',
  },

  'hajatan-classic-maroon': {
    ...defaultStyle,
    greeting: 'Bismillahirrahmanirrahim\nAlhamdulillahi Rabbil \'Alamin',
    closingText: 'Jazakumullahu khairan katsiran atas kehadiran Bapak/Ibu',
    ornamentEmoji: '❦',
    cornerMotif: 'floral',
    dividerStyle: 'ornate',
    borderStyle: 'double',
    fontAccent: 'serif',
    culturalMotifs: ['❦', '❧', '✦'],
    backgroundPattern: 'radial-gradient(circle at 50% 0%, rgba(123,31,58,0.04) 0%, transparent 50%)',
    sectionRadius: '0.5rem',
  },

  'hajatan-modern-teal': {
    ...defaultStyle,
    greeting: 'Dengan rasa syukur dan bahagia',
    closingText: 'Terima kasih atas kehadiran dan doa terbaik Anda',
    ornamentEmoji: '◆',
    cornerMotif: 'geometric',
    dividerStyle: 'simple',
    borderStyle: 'solid',
    fontAccent: 'sans',
    culturalMotifs: ['◆', '◇', '·'],
    backgroundPattern: 'linear-gradient(135deg, rgba(0,121,107,0.03) 0%, transparent 50%)',
    sectionRadius: '1rem',
  },

  // ══════════════════ BIRTHDAY TEMPLATES ══════════════════

  'birthday-colorful-party': {
    ...defaultStyle,
    greeting: '🎉 You\'re Invited! 🎉',
    closingText: 'Can\'t wait to celebrate with you!',
    ornamentEmoji: '🎈',
    cornerMotif: 'geometric',
    dividerStyle: 'dotted',
    borderStyle: 'solid',
    fontAccent: 'sans',
    culturalMotifs: ['🎈', '🎁', '🎊'],
    backgroundPattern: 'radial-gradient(circle at 10% 20%, rgba(156,39,176,0.05) 0%, transparent 40%), radial-gradient(circle at 90% 80%, rgba(156,39,176,0.05) 0%, transparent 40%)',
    sectionRadius: '1.5rem',
  },

  'birthday-elegant-rose': {
    ...defaultStyle,
    greeting: 'Dengan penuh sukacita',
    closingText: 'Kehadiran Anda menjadi hadiah terindah',
    ornamentEmoji: '🌹',
    cornerMotif: 'floral',
    dividerStyle: 'ornate',
    borderStyle: 'double',
    fontAccent: 'serif',
    culturalMotifs: ['🌹', '❀', '✿'],
    backgroundPattern: 'radial-gradient(circle at 80% 20%, rgba(194,24,91,0.04) 0%, transparent 50%)',
    sectionRadius: '0.75rem',
  },

  'birthday-tropical-fun': {
    ...defaultStyle,
    greeting: '🌴 Let\'s Party! 🌴',
    closingText: 'Ayo rayakan bersama di bawah langit tropis!',
    ornamentEmoji: '🌺',
    cornerMotif: 'wave',
    dividerStyle: 'wave',
    borderStyle: 'none',
    fontAccent: 'sans',
    culturalMotifs: ['🌺', '🌴', '🍹'],
    backgroundPattern: 'linear-gradient(180deg, rgba(255,111,0,0.04) 0%, transparent 30%), linear-gradient(0deg, rgba(255,111,0,0.04) 0%, transparent 30%)',
    sectionRadius: '1.5rem',
  },

  'birthday-pastel-dream': {
    ...defaultStyle,
    greeting: '✨ Selamat Datang di Pesta Impian ✨',
    closingText: 'Kehadiran Anda membuat hari ini semakin spesial',
    ornamentEmoji: '🦋',
    cornerMotif: 'floral',
    dividerStyle: 'dotted',
    borderStyle: 'solid',
    fontAccent: 'sans',
    culturalMotifs: ['🦋', '✨', '💜'],
    backgroundPattern: 'radial-gradient(circle at 30% 70%, rgba(171,71,188,0.04) 0%, transparent 50%)',
    sectionRadius: '1.5rem',
  },

  // ══════════════════ FAMILY TEMPLATES ══════════════════

  'family-warm-orange': {
    ...defaultStyle,
    greeting: 'Dengan penuh kebahagiaan',
    closingText: 'Kebersamaan kita adalah harta yang paling berharga',
    ornamentEmoji: '🏡',
    cornerMotif: 'geometric',
    dividerStyle: 'simple',
    borderStyle: 'solid',
    fontAccent: 'sans',
    culturalMotifs: ['🏡', '❤', '🌟'],
    backgroundPattern: 'radial-gradient(circle at 50% 50%, rgba(230,81,0,0.04) 0%, transparent 60%)',
    sectionRadius: '1rem',
  },

  'family-classic-brown': {
    ...defaultStyle,
    greeting: 'Dengan penuh rasa syukur dan cinta',
    closingText: 'Keluarga adalah tempat cinta bertumbuh',
    ornamentEmoji: '🌳',
    cornerMotif: 'floral',
    dividerStyle: 'ornate',
    borderStyle: 'double',
    fontAccent: 'serif',
    culturalMotifs: ['🌳', '🍂', '❦'],
    backgroundPattern: 'radial-gradient(ellipse at 50% 0%, rgba(121,85,72,0.05) 0%, transparent 50%)',
    sectionRadius: '0.5rem',
  },

  'family-garden-green': {
    ...defaultStyle,
    greeting: 'Alhamdulillah, dengan rasa syukur',
    closingText: 'Berkumpul bersama di taman kebahagiaan',
    ornamentEmoji: '🌻',
    cornerMotif: 'floral',
    dividerStyle: 'leaf',
    borderStyle: 'none',
    fontAccent: 'serif',
    culturalMotifs: ['🌻', '🌿', '🍃'],
    backgroundPattern: 'radial-gradient(ellipse at 20% 80%, rgba(56,142,60,0.05) 0%, transparent 50%)',
    sectionRadius: '0.75rem',
  },

  'family-sunset-gold': {
    ...defaultStyle,
    greeting: 'Dengan kehangatan dan cinta keluarga',
    closingText: 'Bersama kita merajut kenangan indah',
    ornamentEmoji: '🌅',
    cornerMotif: 'royal',
    dividerStyle: 'ornate',
    borderStyle: 'double',
    fontAccent: 'serif',
    culturalMotifs: ['🌅', '✦', '⚜'],
    backgroundPattern: 'linear-gradient(180deg, rgba(245,124,0,0.05) 0%, transparent 40%)',
    sectionRadius: '0.75rem',
  },

  // ══════════════════ AQIQAH TEMPLATES ══════════════════

  'aqiqah-soft-pink': {
    ...defaultStyle,
    greeting: 'Bismillahirrahmanirrahim\nAssalamu\'alaikum Wr. Wb.',
    closingText: 'Semoga Allah SWT memberikan keberkahan pada putra/putri kami',
    ornamentEmoji: '👶',
    cornerMotif: 'floral',
    dividerStyle: 'dotted',
    borderStyle: 'solid',
    fontAccent: 'sans',
    culturalMotifs: ['👶', '🌸', '✿'],
    backgroundPattern: 'radial-gradient(circle at 80% 20%, rgba(233,30,99,0.04) 0%, transparent 50%)',
    sectionRadius: '1rem',
  },

  'aqiqah-islamic-teal': {
    ...defaultStyle,
    greeting: 'Bismillahirrahmanirrahim\nDengan mengharap ridho Allah SWT',
    closingText: 'Jazakumullahu khairan atas doa dan kehadirannya',
    ornamentEmoji: '☪',
    cornerMotif: 'islamic',
    dividerStyle: 'ornate',
    borderStyle: 'double',
    fontAccent: 'serif',
    culturalMotifs: ['☪', '✦', '❁'],
    backgroundPattern: 'repeating-conic-gradient(rgba(0,105,92,0.03) 0% 25%, transparent 0% 50%) 0 0 / 35px 35px',
    sectionRadius: '0.5rem',
  },

  // ══════════════════ TAHLILAN TEMPLATES ══════════════════

  'tahlilan-serene-green': {
    ...defaultStyle,
    greeting: 'Innaa lillaahi wa innaa ilaihi raaji\'uun\nAssalamu\'alaikum Wr. Wb.',
    closingText: 'Semoga amal ibadah almarhum/ah diterima di sisi Allah SWT',
    ornamentEmoji: '☪',
    cornerMotif: 'islamic',
    dividerStyle: 'simple',
    borderStyle: 'solid',
    fontAccent: 'serif',
    culturalMotifs: ['☪', '✦', '·'],
    backgroundPattern: 'radial-gradient(circle at 50% 50%, rgba(46,125,50,0.04) 0%, transparent 60%)',
    sectionRadius: '0.5rem',
  },

  'tahlilan-calm-grey': {
    ...defaultStyle,
    greeting: 'Innaa lillaahi wa innaa ilaihi raaji\'uun',
    closingText: 'Semoga Allah SWT mengampuni dan merahmati almarhum/ah',
    ornamentEmoji: '·',
    cornerMotif: 'none',
    dividerStyle: 'simple',
    borderStyle: 'solid',
    fontAccent: 'sans',
    culturalMotifs: ['·', '—', '·'],
    backgroundPattern: null,
    sectionRadius: '0.75rem',
  },

  // ══════════════════ PENGAJIAN TEMPLATES ══════════════════

  'pengajian-green-gold': {
    ...defaultStyle,
    greeting: 'Bismillahirrahmanirrahim\nAssalamu\'alaikum Warahmatullahi Wabarakatuh',
    closingText: 'Jazakumullahu khairan katsiran',
    ornamentEmoji: '☪',
    cornerMotif: 'islamic',
    dividerStyle: 'ornate',
    borderStyle: 'double',
    fontAccent: 'serif',
    culturalMotifs: ['☪', '✶', '✦'],
    backgroundPattern: 'repeating-conic-gradient(rgba(27,94,32,0.03) 0% 25%, transparent 0% 50%) 0 0 / 30px 30px',
    sectionRadius: '0.5rem',
  },

  'pengajian-royal-blue': {
    ...defaultStyle,
    greeting: 'Bismillahirrahmanirrahim\nAssalamu\'alaikum Wr. Wb.',
    closingText: 'Kehadiran Bapak/Ibu sangat kami harapkan',
    ornamentEmoji: '🕌',
    cornerMotif: 'islamic',
    dividerStyle: 'diamond',
    borderStyle: 'double',
    fontAccent: 'serif',
    culturalMotifs: ['🕌', '☪', '✦'],
    backgroundPattern: 'radial-gradient(circle at 50% 0%, rgba(21,101,192,0.05) 0%, transparent 50%)',
    sectionRadius: '0.5rem',
  },

  // ══════════════════ WISUDA TEMPLATES ══════════════════

  'wisuda-navy-gold': {
    ...defaultStyle,
    greeting: 'Dengan penuh kebahagiaan dan rasa syukur',
    closingText: 'Terima kasih atas doa dan dukungan yang telah diberikan',
    ornamentEmoji: '🎓',
    cornerMotif: 'royal',
    dividerStyle: 'ornate',
    borderStyle: 'double',
    fontAccent: 'serif',
    culturalMotifs: ['🎓', '⚜', '✦'],
    backgroundPattern: 'repeating-linear-gradient(45deg, transparent, transparent 40px, rgba(26,35,126,0.02) 40px, rgba(26,35,126,0.02) 41px)',
    sectionRadius: '0.5rem',
  },

  'wisuda-maroon-classic': {
    ...defaultStyle,
    greeting: 'Dengan rasa syukur kepada Tuhan Yang Maha Esa',
    closingText: 'Dukungan dan doa Anda sangat berarti bagi kami',
    ornamentEmoji: '📜',
    cornerMotif: 'floral',
    dividerStyle: 'ornate',
    borderStyle: 'double',
    fontAccent: 'serif',
    culturalMotifs: ['📜', '❦', '✦'],
    backgroundPattern: 'radial-gradient(circle at 50% 0%, rgba(123,31,58,0.04) 0%, transparent 50%)',
    sectionRadius: '0.5rem',
  },

  // ══════════════════ LAMARAN TEMPLATES ══════════════════

  'lamaran-rose-gold': {
    ...defaultStyle,
    greeting: 'Dengan memohon rahmat Tuhan Yang Maha Esa',
    closingText: 'Merupakan kehormatan bagi kami apabila Bapak/Ibu berkenan hadir memberikan doa restu',
    ornamentEmoji: '💍',
    cornerMotif: 'floral',
    dividerStyle: 'ornate',
    borderStyle: 'double',
    fontAccent: 'serif',
    culturalMotifs: ['💍', '❦', '✿'],
    backgroundPattern: 'radial-gradient(circle at 20% 80%, rgba(183,110,121,0.05) 0%, transparent 50%)',
    sectionRadius: '0.75rem',
  },

  'lamaran-sage-romantic': {
    ...defaultStyle,
    greeting: 'Dengan penuh sukacita dan bahagia',
    closingText: 'Kehadiran Anda akan melengkapi kebahagiaan kami',
    ornamentEmoji: '🌿',
    cornerMotif: 'floral',
    dividerStyle: 'leaf',
    borderStyle: 'none',
    fontAccent: 'serif',
    culturalMotifs: ['🌿', '🍃', '💍'],
    backgroundPattern: 'radial-gradient(ellipse at 10% 90%, rgba(122,158,126,0.06) 0%, transparent 50%)',
    sectionRadius: '0.75rem',
  },

  // ══════════════════ SYUKURAN RUMAH TEMPLATES ══════════════════

  'syukuran-rumah-warm': {
    ...defaultStyle,
    greeting: 'Alhamdulillah\nDengan penuh rasa syukur',
    closingText: 'Kehadiran Bapak/Ibu menjadi berkah tersendiri bagi kami',
    ornamentEmoji: '🏠',
    cornerMotif: 'geometric',
    dividerStyle: 'simple',
    borderStyle: 'solid',
    fontAccent: 'sans',
    culturalMotifs: ['🏠', '✦', '🌟'],
    backgroundPattern: 'radial-gradient(circle at 50% 50%, rgba(191,54,12,0.04) 0%, transparent 60%)',
    sectionRadius: '1rem',
  },

  'syukuran-rumah-green': {
    ...defaultStyle,
    greeting: 'Bismillahirrahmanirrahim\nAlhamdulillahi Rabbil \'Alamin',
    closingText: 'Semoga rumah/usaha ini menjadi berkah bagi kami dan sekitar',
    ornamentEmoji: '🌿',
    cornerMotif: 'floral',
    dividerStyle: 'leaf',
    borderStyle: 'none',
    fontAccent: 'serif',
    culturalMotifs: ['🌿', '🏡', '✿'],
    backgroundPattern: 'radial-gradient(ellipse at 50% 100%, rgba(56,142,60,0.05) 0%, transparent 50%)',
    sectionRadius: '0.75rem',
  },

  // ══════════════════ DUKA CITA TEMPLATES ══════════════════

  'duka-cita-sombre': {
    ...defaultStyle,
    greeting: 'Innaa lillaahi wa innaa ilaihi raaji\'uun',
    closingText: 'Turut berduka cita yang sedalam-dalamnya',
    ornamentEmoji: '🕊',
    cornerMotif: 'none',
    dividerStyle: 'simple',
    borderStyle: 'solid',
    fontAccent: 'serif',
    culturalMotifs: ['🕊', '·', '—'],
    backgroundPattern: null,
    sectionRadius: '0.5rem',
  },

  'duka-cita-white': {
    ...defaultStyle,
    greeting: 'Turut Berduka Cita',
    closingText: 'Semoga almarhum/ah diberikan tempat terbaik di sisi-Nya',
    ornamentEmoji: '🕊',
    cornerMotif: 'none',
    dividerStyle: 'simple',
    borderStyle: 'none',
    fontAccent: 'sans',
    culturalMotifs: ['🕊', '·', '·'],
    backgroundPattern: null,
    sectionRadius: '0.75rem',
  },

  // ══════════════════ BUKBER TEMPLATES ══════════════════

  'bukber-ramadan-gold': {
    ...defaultStyle,
    greeting: 'Marhaban Yaa Ramadhan\nAssalamu\'alaikum Wr. Wb.',
    closingText: 'Semoga ibadah puasa kita diterima. Aamiin.',
    ornamentEmoji: '🌙',
    cornerMotif: 'islamic',
    dividerStyle: 'ornate',
    borderStyle: 'double',
    fontAccent: 'serif',
    culturalMotifs: ['🌙', '☪', '✦'],
    backgroundPattern: 'linear-gradient(180deg, rgba(249,168,37,0.05) 0%, transparent 30%), linear-gradient(0deg, rgba(46,125,50,0.03) 0%, transparent 30%)',
    sectionRadius: '0.75rem',
  },

  'bukber-crescent-blue': {
    ...defaultStyle,
    greeting: 'Ramadhan Mubarak\nAssalamu\'alaikum Wr. Wb.',
    closingText: 'Mari berbuka bersama dan mempererat tali silaturahmi',
    ornamentEmoji: '🌙',
    cornerMotif: 'islamic',
    dividerStyle: 'diamond',
    borderStyle: 'solid',
    fontAccent: 'sans',
    culturalMotifs: ['🌙', '⭐', '✦'],
    backgroundPattern: 'radial-gradient(circle at 80% 10%, rgba(21,101,192,0.05) 0%, transparent 50%)',
    sectionRadius: '1rem',
  },

  // ══════════════════ ARISAN TEMPLATES ══════════════════

  'arisan-fun-coral': {
    ...defaultStyle,
    greeting: 'Hai! 👋\nAyo kumpul lagi',
    closingText: 'Ditunggu kehadirannya ya!',
    ornamentEmoji: '💰',
    cornerMotif: 'geometric',
    dividerStyle: 'dotted',
    borderStyle: 'solid',
    fontAccent: 'sans',
    culturalMotifs: ['💰', '🎉', '✦'],
    backgroundPattern: 'radial-gradient(circle at 80% 80%, rgba(255,87,34,0.04) 0%, transparent 50%)',
    sectionRadius: '1.5rem',
  },

  'arisan-soft-purple': {
    ...defaultStyle,
    greeting: 'Halo semuanya! 💜',
    closingText: 'Sampai jumpa di arisan berikutnya!',
    ornamentEmoji: '✨',
    cornerMotif: 'none',
    dividerStyle: 'dotted',
    borderStyle: 'none',
    fontAccent: 'sans',
    culturalMotifs: ['✨', '💜', '·'],
    backgroundPattern: 'radial-gradient(circle at 20% 80%, rgba(123,31,162,0.04) 0%, transparent 50%)',
    sectionRadius: '1.5rem',
  },

  // ══════════════════ ACARA UMUM TEMPLATES ══════════════════

  'acara-umum-professional': {
    ...defaultStyle,
    greeting: 'Dengan hormat',
    closingText: 'Atas perhatian dan kehadirannya, kami ucapkan terima kasih',
    ornamentEmoji: '📋',
    cornerMotif: 'geometric',
    dividerStyle: 'simple',
    borderStyle: 'solid',
    fontAccent: 'sans',
    culturalMotifs: ['📋', '◇', '·'],
    backgroundPattern: 'linear-gradient(135deg, rgba(21,101,192,0.03) 0%, transparent 50%)',
    sectionRadius: '0.75rem',
  },

  'acara-umum-casual': {
    ...defaultStyle,
    greeting: 'Halo! 👋',
    closingText: 'Ditunggu kehadirannya ya!',
    ornamentEmoji: '🎯',
    cornerMotif: 'none',
    dividerStyle: 'dotted',
    borderStyle: 'none',
    fontAccent: 'sans',
    culturalMotifs: ['🎯', '·', '·'],
    backgroundPattern: null,
    sectionRadius: '1rem',
  },

  // ══════════════════ NEW BATCH 2: ZODIAK & CELESTIAL ══════════════════

  'wedding-celestial-stars': {
    ...defaultStyle,
    greeting: 'Written in the stars\nTertulis di bintang-bintang',
    closingText: 'Our love is infinite like the universe — Cinta kami tak terbatas seperti alam semesta',
    ornamentEmoji: '✨',
    cornerMotif: 'geometric',
    dividerStyle: 'dotted',
    borderStyle: 'double',
    fontAccent: 'serif',
    culturalMotifs: ['✨', '⭐', '✧'],
    backgroundPattern: 'radial-gradient(circle at 20% 30%, rgba(255,215,0,0.06) 0%, transparent 40%), radial-gradient(circle at 80% 70%, rgba(255,215,0,0.04) 0%, transparent 40%), radial-gradient(circle at 50% 50%, rgba(255,215,0,0.02) 0%, transparent 70%)',
    sectionRadius: '0.5rem',
    animationPreset: 'celestial',
    culturalIcons: [
      { emoji: '⭐', label: 'Bintang' },
      { emoji: '✨', label: 'Gemerlap' },
      { emoji: '🌟', label: 'Bintang Bersinar' },
    ],
  },

  'wedding-moon-phase': {
    ...defaultStyle,
    greeting: 'Through every phase, with you\nDi setiap fase, bersamamu',
    closingText: 'Like the moon, our love goes through phases but never fades',
    ornamentEmoji: '🌙',
    cornerMotif: 'none',
    dividerStyle: 'dotted',
    borderStyle: 'solid',
    fontAccent: 'sans',
    culturalMotifs: ['🌑', '🌓', '🌕'],
    backgroundPattern: 'radial-gradient(circle at 75% 20%, rgba(192,192,192,0.08) 0%, transparent 50%)',
    sectionRadius: '1rem',
    animationPreset: 'celestial',
    culturalIcons: [
      { emoji: '🌙', label: 'Bulan Sabit' },
      { emoji: '🌕', label: 'Bulan Purnama' },
      { emoji: '🌑', label: 'Bulan Baru' },
    ],
  },

  'wedding-galaxy-nebula': {
    ...defaultStyle,
    greeting: 'Across galaxies, we found each other\nMelintasi galaksi, kita saling menemukan',
    closingText: 'Two stars colliding — Dua bintang yang bertemu dalam harmoni kosmis',
    ornamentEmoji: '🌌',
    cornerMotif: 'geometric',
    dividerStyle: 'wave',
    borderStyle: 'double',
    fontAccent: 'serif',
    culturalMotifs: ['🌌', '💫', '🔮'],
    backgroundPattern: 'radial-gradient(ellipse at 30% 20%, rgba(155,89,182,0.08) 0%, transparent 50%), radial-gradient(ellipse at 70% 80%, rgba(52,152,219,0.06) 0%, transparent 50%)',
    sectionRadius: '0.75rem',
    animationPreset: 'celestial',
    culturalIcons: [
      { emoji: '🌌', label: 'Nebula' },
      { emoji: '💫', label: 'Komet' },
      { emoji: '🔮', label: 'Cosmic Orb' },
    ],
  },

  'wedding-constellation': {
    ...defaultStyle,
    greeting: 'Connected by constellations\nTerhubung oleh rasi bintang',
    closingText: 'Our paths were mapped in the sky — Jalan kita telah terukir di langit',
    ornamentEmoji: '⋆',
    cornerMotif: 'none',
    dividerStyle: 'dotted',
    borderStyle: 'dashed',
    fontAccent: 'sans',
    culturalMotifs: ['⋆', '·', '✧'],
    backgroundPattern: 'radial-gradient(circle at 10% 10%, rgba(135,206,235,0.05) 0%, transparent 30%), radial-gradient(circle at 90% 90%, rgba(135,206,235,0.05) 0%, transparent 30%)',
    sectionRadius: '0.25rem',
    animationPreset: 'celestial',
    culturalIcons: [
      { emoji: '⋆', label: 'Bintang Kecil' },
      { emoji: '🌠', label: 'Bintang Jatuh' },
      { emoji: '🔭', label: 'Teleskop' },
    ],
  },

  'wedding-solar-eclipse': {
    ...defaultStyle,
    greeting: 'When sun meets moon\nSaat matahari bertemu bulan',
    closingText: 'A rare moment of perfect alignment — Momen langka keselarasan sempurna',
    ornamentEmoji: '🌗',
    cornerMotif: 'geometric',
    dividerStyle: 'diamond',
    borderStyle: 'double',
    fontAccent: 'serif',
    culturalMotifs: ['🌗', '☀', '✦'],
    backgroundPattern: 'radial-gradient(circle at 50% 40%, rgba(255,107,53,0.08) 0%, transparent 40%), radial-gradient(circle at 50% 60%, rgba(255,215,0,0.04) 0%, transparent 60%)',
    sectionRadius: '50%',
    animationPreset: 'celestial',
    culturalIcons: [
      { emoji: '🌗', label: 'Gerhana' },
      { emoji: '☀', label: 'Matahari' },
      { emoji: '🌑', label: 'Bulan' },
    ],
  },

  // ══════════════════ NEW BATCH 2: ARSITEKTUR DUNIA ══════════════════

  'wedding-gothic-cathedral': {
    ...defaultStyle,
    greeting: 'In sacred halls of love\nDi aula suci cinta',
    closingText: 'May our love stand as tall as cathedral spires — Semoga cinta kita setinggi menara katedral',
    ornamentEmoji: '⚜',
    cornerMotif: 'royal',
    dividerStyle: 'ornate',
    borderStyle: 'double',
    fontAccent: 'serif',
    culturalMotifs: ['⚜', '✝', '◈'],
    backgroundPattern: 'repeating-linear-gradient(90deg, rgba(139,0,0,0.02) 0px, rgba(139,0,0,0.02) 1px, transparent 1px, transparent 50px), repeating-linear-gradient(0deg, rgba(139,0,0,0.02) 0px, rgba(139,0,0,0.02) 1px, transparent 1px, transparent 50px)',
    sectionRadius: '0.25rem',
    animationPreset: 'architectural',
    culturalIcons: [
      { emoji: '⛪', label: 'Katedral Gothic' },
      { emoji: '🕯', label: 'Lilin' },
      { emoji: '🌹', label: 'Rose Window' },
    ],
  },

  'wedding-zen-garden': {
    ...defaultStyle,
    greeting: '和 — Harmony\nKeselarasan dan kedamaian',
    closingText: '禅 — Zen. Terima kasih atas kehadiran dan kedamaian yang Anda bawa',
    ornamentEmoji: '☯',
    cornerMotif: 'none',
    dividerStyle: 'simple',
    borderStyle: 'none',
    fontAccent: 'sans',
    culturalMotifs: ['☯', '◯', '·'],
    backgroundPattern: null,
    sectionRadius: '0.25rem',
    animationPreset: 'architectural',
    culturalIcons: [
      { emoji: '🪨', label: 'Batu Zen' },
      { emoji: '🎋', label: 'Bambu' },
      { emoji: '🍃', label: 'Daun' },
    ],
  },

  'wedding-mediterranean-villa': {
    ...defaultStyle,
    greeting: 'Under the Tuscan sun\nDi bawah matahari Tuscany',
    closingText: 'Grazie mille — Terima kasih telah berbagi keindahan ini bersama kami',
    ornamentEmoji: '🌿',
    cornerMotif: 'floral',
    dividerStyle: 'leaf',
    borderStyle: 'none',
    fontAccent: 'serif',
    culturalMotifs: ['🫒', '🌿', '🌻'],
    backgroundPattern: 'radial-gradient(ellipse at 50% 0%, rgba(204,122,62,0.05) 0%, transparent 50%)',
    sectionRadius: '1rem',
    animationPreset: 'architectural',
    culturalIcons: [
      { emoji: '🫒', label: 'Zaitun' },
      { emoji: '🏛', label: 'Kolom' },
      { emoji: '🌻', label: 'Bunga Matahari' },
    ],
  },

  'wedding-victorian-manor': {
    ...defaultStyle,
    greeting: 'With great honour and delight\nDengan penuh kehormatan dan kegembiraan',
    closingText: 'We humbly request the pleasure of your company — Kami dengan rendah hati memohon kehadiran Anda',
    ornamentEmoji: '❧',
    cornerMotif: 'floral',
    dividerStyle: 'ornate',
    borderStyle: 'double',
    fontAccent: 'serif',
    culturalMotifs: ['❧', '❦', '⚜'],
    backgroundPattern: 'repeating-linear-gradient(45deg, transparent, transparent 30px, rgba(114,47,55,0.02) 30px, rgba(114,47,55,0.02) 31px)',
    sectionRadius: '0.5rem',
    animationPreset: 'architectural',
    culturalIcons: [
      { emoji: '🏰', label: 'Manor' },
      { emoji: '🌹', label: 'Mawar Inggris' },
      { emoji: '☕', label: 'Tea Time' },
    ],
  },

  'wedding-moroccan-riad': {
    ...defaultStyle,
    greeting: 'Marhaba — Selamat datang\nDengan penuh kebahagiaan dan syukur',
    closingText: 'Shukran jazilan — Terima kasih yang sebesar-besarnya atas kehadiran Anda',
    ornamentEmoji: '✦',
    cornerMotif: 'islamic',
    dividerStyle: 'ornate',
    borderStyle: 'ornate',
    fontAccent: 'serif',
    culturalMotifs: ['✦', '◈', '❖'],
    backgroundPattern: 'repeating-conic-gradient(rgba(193,68,14,0.04) 0% 25%, transparent 0% 50%) 0 0 / 22px 22px',
    sectionRadius: '0.5rem',
    animationPreset: 'architectural',
    culturalIcons: [
      { emoji: '🕌', label: 'Riad' },
      { emoji: '🌴', label: 'Kurma' },
      { emoji: '✨', label: 'Zellige' },
    ],
  },

  // ══════════════════ NEW BATCH 2: WARNA & MOOD ══════════════════

  'wedding-midnight-noir': {
    ...defaultStyle,
    greeting: 'In the darkest night, love shines brightest\nDi malam tergelap, cinta bersinar paling terang',
    closingText: 'Thank you for illuminating our night — Terima kasih telah menerangi malam kami',
    ornamentEmoji: '◈',
    cornerMotif: 'geometric',
    dividerStyle: 'diamond',
    borderStyle: 'double',
    fontAccent: 'serif',
    culturalMotifs: ['◈', '✧', '◇'],
    backgroundPattern: 'radial-gradient(circle at 50% 50%, rgba(212,175,55,0.06) 0%, transparent 50%)',
    sectionRadius: '0.25rem',
    animationPreset: 'chromatic',
    culturalIcons: [
      { emoji: '🌑', label: 'Midnight' },
      { emoji: '✨', label: 'Shimmer' },
      { emoji: '💎', label: 'Diamond' },
    ],
  },

  'wedding-rose-quartz': {
    ...defaultStyle,
    greeting: 'Love heals, love grows\nCinta menyembuhkan, cinta bertumbuh',
    closingText: 'With crystalized love — Dengan cinta yang mengkristal, kami menanti kehadiran Anda',
    ornamentEmoji: '💎',
    cornerMotif: 'floral',
    dividerStyle: 'wave',
    borderStyle: 'solid',
    fontAccent: 'serif',
    culturalMotifs: ['💎', '✿', '❀'],
    backgroundPattern: 'radial-gradient(circle at 30% 30%, rgba(196,139,159,0.06) 0%, transparent 40%), radial-gradient(circle at 70% 70%, rgba(196,139,159,0.04) 0%, transparent 40%)',
    sectionRadius: '1rem',
    animationPreset: 'chromatic',
    culturalIcons: [
      { emoji: '💎', label: 'Rose Quartz' },
      { emoji: '🌸', label: 'Cherry Blossom' },
      { emoji: '🦋', label: 'Kupu-kupu' },
    ],
  },

  'wedding-emerald-dream': {
    ...defaultStyle,
    greeting: 'Precious as emeralds, eternal as love\nBerharga seperti zamrud, abadi seperti cinta',
    closingText: 'A gem of a celebration — Perayaan seindah permata, terima kasih atas kehadiran Anda',
    ornamentEmoji: '💚',
    cornerMotif: 'royal',
    dividerStyle: 'ornate',
    borderStyle: 'double',
    fontAccent: 'serif',
    culturalMotifs: ['💚', '◈', '✦'],
    backgroundPattern: 'radial-gradient(circle at 50% 0%, rgba(4,99,7,0.05) 0%, transparent 50%), radial-gradient(circle at 50% 100%, rgba(4,99,7,0.03) 0%, transparent 50%)',
    sectionRadius: '0.5rem',
    animationPreset: 'chromatic',
    culturalIcons: [
      { emoji: '💚', label: 'Emerald' },
      { emoji: '🌿', label: 'Daun Hijau' },
      { emoji: '👑', label: 'Crown Jewel' },
    ],
  },

  'wedding-copper-luxe': {
    ...defaultStyle,
    greeting: 'Forged in love, polished by time\nDitempa oleh cinta, dipoles oleh waktu',
    closingText: 'Your presence adds luster to our celebration — Kehadiran Anda menambah kilau perayaan kami',
    ornamentEmoji: '⚙',
    cornerMotif: 'geometric',
    dividerStyle: 'simple',
    borderStyle: 'solid',
    fontAccent: 'sans',
    culturalMotifs: ['⚙', '◇', '·'],
    backgroundPattern: 'repeating-linear-gradient(135deg, transparent, transparent 40px, rgba(184,115,51,0.03) 40px, rgba(184,115,51,0.03) 41px)',
    sectionRadius: '0.5rem',
    animationPreset: 'chromatic',
    culturalIcons: [
      { emoji: '🔶', label: 'Copper' },
      { emoji: '⚙', label: 'Metalwork' },
      { emoji: '✨', label: 'Shimmer' },
    ],
  },

  'wedding-lavender-mist': {
    ...defaultStyle,
    greeting: 'In fields of lavender, love blooms\nDi ladang lavender, cinta bermekaran',
    closingText: 'Fragrant with joy — Harum dengan kebahagiaan, terima kasih atas kehadiran Anda',
    ornamentEmoji: '💜',
    cornerMotif: 'floral',
    dividerStyle: 'leaf',
    borderStyle: 'none',
    fontAccent: 'serif',
    culturalMotifs: ['💜', '❀', '🌿'],
    backgroundPattern: 'radial-gradient(ellipse at 20% 80%, rgba(150,123,182,0.05) 0%, transparent 50%), radial-gradient(ellipse at 80% 20%, rgba(150,123,182,0.03) 0%, transparent 50%)',
    sectionRadius: '1rem',
    animationPreset: 'chromatic',
    culturalIcons: [
      { emoji: '💜', label: 'Lavender' },
      { emoji: '🦋', label: 'Kupu-kupu' },
      { emoji: '🌿', label: 'Herbal' },
    ],
  },

  // ══════════════════ NEW BATCH 2: MUSIM & FENOMENA ALAM ══════════════════

  'wedding-spring-blossom': {
    ...defaultStyle,
    greeting: 'Love blooms in spring\nCinta bermekaran di musim semi',
    closingText: 'Like flowers in spring — Seperti bunga di musim semi, cinta kami terus bermekaran',
    ornamentEmoji: '🌷',
    cornerMotif: 'floral',
    dividerStyle: 'leaf',
    borderStyle: 'none',
    fontAccent: 'serif',
    culturalMotifs: ['🌷', '🌸', '🌼'],
    backgroundPattern: 'radial-gradient(circle at 20% 20%, rgba(232,139,165,0.06) 0%, transparent 40%), radial-gradient(circle at 80% 80%, rgba(232,139,165,0.04) 0%, transparent 40%)',
    sectionRadius: '1rem',
    animationPreset: 'elemental',
    culturalIcons: [
      { emoji: '🌷', label: 'Tulip' },
      { emoji: '🌸', label: 'Bunga Mekar' },
      { emoji: '🐝', label: 'Lebah' },
    ],
  },

  'wedding-monsoon-rain': {
    ...defaultStyle,
    greeting: 'Dancing in the rain, together\nMenari dalam hujan, bersama',
    closingText: 'After the rain, sunshine — Setelah hujan, matahari bersinar, seperti cinta kami',
    ornamentEmoji: '🌧',
    cornerMotif: 'wave',
    dividerStyle: 'wave',
    borderStyle: 'solid',
    fontAccent: 'sans',
    culturalMotifs: ['🌧', '💧', '☂'],
    backgroundPattern: 'repeating-linear-gradient(180deg, transparent, transparent 15px, rgba(70,130,180,0.03) 15px, rgba(70,130,180,0.03) 16px)',
    sectionRadius: '0.75rem',
    animationPreset: 'elemental',
    culturalIcons: [
      { emoji: '🌧', label: 'Hujan' },
      { emoji: '💧', label: 'Tetesan' },
      { emoji: '🌈', label: 'Pelangi' },
    ],
  },

  'wedding-desert-mirage': {
    ...defaultStyle,
    greeting: 'An oasis of love\nOase cinta di tengah gurun',
    closingText: 'Like a desert rose — Seperti mawar gurun, cinta kami tumbuh di tempat tak terduga',
    ornamentEmoji: '🏜',
    cornerMotif: 'geometric',
    dividerStyle: 'diamond',
    borderStyle: 'double',
    fontAccent: 'serif',
    culturalMotifs: ['🏜', '✦', '◈'],
    backgroundPattern: 'linear-gradient(180deg, rgba(218,165,32,0.05) 0%, transparent 30%), linear-gradient(0deg, rgba(218,165,32,0.03) 0%, transparent 30%)',
    sectionRadius: '0.5rem',
    animationPreset: 'elemental',
    culturalIcons: [
      { emoji: '🏜', label: 'Gurun' },
      { emoji: '🌵', label: 'Kaktus' },
      { emoji: '🐪', label: 'Unta' },
    ],
  },

  'wedding-northern-lights': {
    ...defaultStyle,
    greeting: 'Under the dancing lights\nDi bawah cahaya menari',
    closingText: 'Like the aurora — Seperti aurora, cinta kami mewarnai langit dengan keindahan',
    ornamentEmoji: '🌌',
    cornerMotif: 'wave',
    dividerStyle: 'wave',
    borderStyle: 'double',
    fontAccent: 'sans',
    culturalMotifs: ['🌌', '✧', '◇'],
    backgroundPattern: 'linear-gradient(135deg, rgba(0,212,170,0.06) 0%, rgba(155,89,182,0.04) 50%, rgba(0,212,170,0.02) 100%)',
    sectionRadius: '0.75rem',
    animationPreset: 'elemental',
    culturalIcons: [
      { emoji: '🌌', label: 'Aurora' },
      { emoji: '❄', label: 'Salju' },
      { emoji: '🌲', label: 'Pinus' },
    ],
  },

  'wedding-tropical-storm': {
    ...defaultStyle,
    greeting: 'Through every storm, love endures\nMelewati setiap badai, cinta bertahan',
    closingText: 'The calm after the storm — Ketenangan setelah badai, itulah cinta kami',
    ornamentEmoji: '⚡',
    cornerMotif: 'geometric',
    dividerStyle: 'arrow',
    borderStyle: 'double',
    fontAccent: 'serif',
    culturalMotifs: ['⚡', '🌩', '✦'],
    backgroundPattern: 'repeating-linear-gradient(45deg, transparent, transparent 25px, rgba(255,215,0,0.03) 25px, rgba(255,215,0,0.03) 26px), repeating-linear-gradient(-45deg, transparent, transparent 25px, rgba(255,215,0,0.02) 25px, rgba(255,215,0,0.02) 26px)',
    sectionRadius: '0.25rem',
    animationPreset: 'elemental',
    culturalIcons: [
      { emoji: '⚡', label: 'Petir' },
      { emoji: '🌩', label: 'Badai' },
      { emoji: '🌊', label: 'Gelombang' },
    ],
  },

  'full-custom': {
    ...defaultStyle,
    greeting: 'Dengan memohon rahmat Tuhan Yang Maha Esa',
    closingText: 'Merupakan kehormatan bagi kami apabila Bapak/Ibu/Saudara/i berkenan hadir',
    ornamentEmoji: '✦',
    cornerMotif: 'none',
    dividerStyle: 'ornate',
    borderStyle: 'none',
    fontAccent: 'serif',
    culturalMotifs: ['✦', '❖', '✦'],
    backgroundPattern: null,
    sectionRadius: '0',
    patternOverlay: null,
  },
};

export function getTemplateCulturalStyle(templateId: string): TemplateCulturalStyle {
  return templateCulturalStyles[templateId] || defaultStyle;
}
