import { EventType } from './event-types';
import royalGoldBg from '@/assets/template-bg/royal-gold.jpg';
import floralRomanceBg from '@/assets/template-bg/floral-romance.jpg';
import islamicEmeraldBg from '@/assets/template-bg/islamic-emerald.jpg';
import pastelCelebrationBg from '@/assets/template-bg/pastel-celebration.jpg';
import babyCloudBg from '@/assets/template-bg/baby-cloud.jpg';
import rusticBurgundyBg from '@/assets/template-bg/rustic-burgundy.jpg';
import tropicalParadiseBg from '@/assets/template-bg/tropical-paradise.jpg';
import ottomanSapphireBg from '@/assets/template-bg/ottoman-sapphire.jpg';
import academicLaurelBg from '@/assets/template-bg/academic-laurel.jpg';
import vintageBotanicalBg from '@/assets/template-bg/vintage-botanical.jpg';

import type { CustomBackgrounds } from './invitation';

export interface TemplateSection {
  id: string;
  type: 'cover' | 'names' | 'datetime' | 'location' | 'gallery' | 'message' | 'countdown';
  enabled: boolean;
}

export interface Template {
  id: string;
  name: string;
  description: string;
  eventTypes: EventType[];
  previewImage: string;
  isPremium: boolean;
  colorScheme: {
    primary: string;
    secondary: string;
    background: string;
    text: string;
  };
  sections: TemplateSection[];
  style: 'classic' | 'modern' | 'minimalist' | 'elegant' | 'rustic' | 'custom';
  isFullCustom?: boolean;
  /**
   * Built-in background images per section. When the template is rendered and
   * the user has not uploaded their own backgrounds, these are used as fallback.
   * Templates that ship with `defaultBackgrounds` behave like Full Custom
   * (background images per section) but require zero setup from the user.
   */
  defaultBackgrounds?: CustomBackgrounds;
}

const defaultSections: TemplateSection[] = [
  { id: 'cover', type: 'cover', enabled: true },
  { id: 'names', type: 'names', enabled: true },
  { id: 'countdown', type: 'countdown', enabled: true },
  { id: 'datetime', type: 'datetime', enabled: true },
  { id: 'location', type: 'location', enabled: true },
  { id: 'gallery', type: 'gallery', enabled: true },
  { id: 'message', type: 'message', enabled: true },
];

const simpleSections: TemplateSection[] = [
  { id: 'cover', type: 'cover', enabled: true },
  { id: 'names', type: 'names', enabled: true },
  { id: 'datetime', type: 'datetime', enabled: true },
  { id: 'location', type: 'location', enabled: true },
  { id: 'message', type: 'message', enabled: true },
];

const _templates: Template[] = [
  // ── Wedding Templates (1 free, 4 premium) ──
  {
    id: 'wedding-classic-gold',
    name: 'Emas Klasik',
    description: 'Desain klasik dengan sentuhan emas yang elegan',
    eventTypes: ['wedding'],
    previewImage: '/templates/wedding-classic.jpg',
    isPremium: false,
    colorScheme: { primary: '#c9a962', secondary: '#f5e6d3', background: '#faf8f5', text: '#3d3d3d' },
    sections: defaultSections,
    style: 'classic',
  },
  {
    id: 'wedding-modern-blush',
    name: 'Blush Modern',
    description: 'Desain modern dengan warna pink lembut',
    eventTypes: ['wedding'],
    previewImage: '/templates/wedding-modern.jpg',
    isPremium: false,
    colorScheme: { primary: '#d4a5a5', secondary: '#f8e8e8', background: '#ffffff', text: '#4a4a4a' },
    sections: defaultSections,
    style: 'modern',
  },
  {
    id: 'wedding-elegant-navy',
    name: 'Navy Elegan',
    description: 'Desain elegan dengan warna navy dan emas',
    eventTypes: ['wedding'],
    previewImage: '/templates/wedding-elegant.jpg',
    isPremium: false,
    colorScheme: { primary: '#1e3a5f', secondary: '#c9a962', background: '#f8f9fa', text: '#1e3a5f' },
    sections: defaultSections,
    style: 'elegant',
  },
  {
    id: 'wedding-rustic-sage',
    name: 'Sage Rustic',
    description: 'Nuansa alam dengan warna sage yang menenangkan',
    eventTypes: ['wedding'],
    previewImage: '/templates/wedding-rustic.jpg',
    isPremium: false,
    colorScheme: { primary: '#7a9e7e', secondary: '#e8f0e8', background: '#fafdf9', text: '#3d4f3d' },
    sections: defaultSections,
    style: 'rustic',
  },
  {
    id: 'wedding-minimalist-mono',
    name: 'Mono Minimalis',
    description: 'Desain minimalis hitam putih yang timeless',
    eventTypes: ['wedding'],
    previewImage: '/templates/wedding-minimalist.jpg',
    isPremium: false,
    colorScheme: { primary: '#2c2c2c', secondary: '#e8e8e8', background: '#ffffff', text: '#1a1a1a' },
    sections: defaultSections,
    style: 'minimalist',
  },
  {
    id: 'wedding-jawa-classic',
    name: 'Jawa Klasik',
    description: 'Tema pernikahan adat Jawa dengan nuansa coklat dan emas keraton',
    eventTypes: ['wedding'],
    previewImage: '/templates/wedding-jawa.jpg',
    isPremium: false,
    colorScheme: { primary: '#8B6914', secondary: '#F5E6C8', background: '#FDF8F0', text: '#4A3728' },
    sections: defaultSections,
    style: 'classic',
  },
  {
    id: 'wedding-sunda-elegant',
    name: 'Sunda Elegan',
    description: 'Tema pernikahan adat Sunda dengan nuansa hijau dan emas khas Parahyangan',
    eventTypes: ['wedding'],
    previewImage: '/templates/wedding-sunda.jpg',
    isPremium: false,
    colorScheme: { primary: '#2E7D32', secondary: '#E8F5E9', background: '#FAFDF7', text: '#1B5E20' },
    sections: defaultSections,
    style: 'elegant',
  },
  {
    id: 'wedding-madura-bold',
    name: 'Madura Berani',
    description: 'Tema pernikahan adat Madura dengan warna merah dan kuning yang khas',
    eventTypes: ['wedding'],
    previewImage: '/templates/wedding-madura.jpg',
    isPremium: false,
    colorScheme: { primary: '#B71C1C', secondary: '#FFECB3', background: '#FFF8F0', text: '#6D1010' },
    sections: defaultSections,
    style: 'classic',
  },
  {
    id: 'wedding-batak-megah',
    name: 'Batak Megah',
    description: 'Tema pernikahan adat Batak dengan nuansa merah tua dan emas ulos',
    eventTypes: ['wedding'],
    previewImage: '/templates/wedding-batak.jpg',
    isPremium: false,
    colorScheme: { primary: '#8B0000', secondary: '#FFD700', background: '#FFF9F0', text: '#5C0000' },
    sections: defaultSections,
    style: 'elegant',
  },
  {
    id: 'wedding-minang-indah',
    name: 'Minangkabau Indah',
    description: 'Tema pernikahan adat Minangkabau dengan nuansa merah dan emas Rumah Gadang',
    eventTypes: ['wedding'],
    previewImage: '/templates/wedding-minang.jpg',
    isPremium: false,
    colorScheme: { primary: '#C62828', secondary: '#FFF8E1', background: '#FFFDF5', text: '#7F1616' },
    sections: defaultSections,
    style: 'elegant',
  },
  {
    id: 'wedding-betawi-meriah',
    name: 'Betawi Meriah',
    description: 'Tema pernikahan adat Betawi dengan warna cerah khas ondel-ondel',
    eventTypes: ['wedding'],
    previewImage: '/templates/wedding-betawi.jpg',
    isPremium: false,
    colorScheme: { primary: '#E65100', secondary: '#FFF3E0', background: '#FFFBF5', text: '#BF360C' },
    sections: defaultSections,
    style: 'modern',
  },
  {
    id: 'wedding-bugis-megah',
    name: 'Bugis Megah',
    description: 'Tema pernikahan adat Bugis dengan nuansa merah marun dan emas songket',
    eventTypes: ['wedding'],
    previewImage: '/templates/wedding-bugis.jpg',
    isPremium: false,
    colorScheme: { primary: '#880E4F', secondary: '#FCE4EC', background: '#FFF8FA', text: '#560027' },
    sections: defaultSections,
    style: 'elegant',
  },
  {
    id: 'wedding-banten-klasik',
    name: 'Banten Klasik',
    description: 'Tema pernikahan adat Banten dengan nuansa putih dan emas debus',
    eventTypes: ['wedding'],
    previewImage: '/templates/wedding-banten.jpg',
    isPremium: false,
    colorScheme: { primary: '#5D4037', secondary: '#EFEBE9', background: '#FAF8F5', text: '#3E2723' },
    sections: defaultSections,
    style: 'classic',
  },
  {
    id: 'wedding-banjar-indah',
    name: 'Banjar Indah',
    description: 'Tema pernikahan adat Banjar dengan nuansa kuning dan hijau khas Kalimantan Selatan',
    eventTypes: ['wedding'],
    previewImage: '/templates/wedding-banjar.jpg',
    isPremium: false,
    colorScheme: { primary: '#F9A825', secondary: '#FFF9C4', background: '#FFFDE7', text: '#F57F17' },
    sections: defaultSections,
    style: 'elegant',
  },
  {
    id: 'wedding-bali-sakral',
    name: 'Bali Sakral',
    description: 'Tema pernikahan adat Bali dengan nuansa hitam putih dan emas pura',
    eventTypes: ['wedding'],
    previewImage: '/templates/wedding-bali.jpg',
    isPremium: false,
    colorScheme: { primary: '#4E342E', secondary: '#D7CCC8', background: '#FAF5F0', text: '#3E2723' },
    sections: defaultSections,
    style: 'classic',
  },
  {
    id: 'wedding-sasak-anggun',
    name: 'Sasak Anggun',
    description: 'Tema pernikahan adat Sasak Lombok dengan nuansa songket tenun',
    eventTypes: ['wedding'],
    previewImage: '/templates/wedding-sasak.jpg',
    isPremium: false,
    colorScheme: { primary: '#6A1B9A', secondary: '#F3E5F5', background: '#FDF5FF', text: '#4A148C' },
    sections: defaultSections,
    style: 'elegant',
  },
  {
    id: 'wedding-aceh-mulia',
    name: 'Aceh Mulia',
    description: 'Tema pernikahan adat Aceh dengan nuansa hijau islami dan emas',
    eventTypes: ['wedding'],
    previewImage: '/templates/wedding-aceh.jpg',
    isPremium: false,
    colorScheme: { primary: '#1B5E20', secondary: '#E8F5E9', background: '#F1F8E9', text: '#0D3B0F' },
    sections: defaultSections,
    style: 'classic',
  },
  {
    id: 'wedding-dayak-agung',
    name: 'Dayak Agung',
    description: 'Tema pernikahan adat Dayak dengan nuansa merah bata dan motif mandau',
    eventTypes: ['wedding'],
    previewImage: '/templates/wedding-dayak.jpg',
    isPremium: false,
    colorScheme: { primary: '#D84315', secondary: '#FFCCBC', background: '#FFF5F0', text: '#BF360C' },
    sections: defaultSections,
    style: 'rustic',
  },
  {
    id: 'wedding-makassar-gagah',
    name: 'Makassar Gagah',
    description: 'Tema pernikahan adat Makassar dengan nuansa merah dan emas baju bodo',
    eventTypes: ['wedding'],
    previewImage: '/templates/wedding-makassar.jpg',
    isPremium: false,
    colorScheme: { primary: '#C62828', secondary: '#FFCDD2', background: '#FFF5F5', text: '#B71C1C' },
    sections: defaultSections,
    style: 'elegant',
  },
  {
    id: 'wedding-melayu-pesona',
    name: 'Melayu Pesona',
    description: 'Tema pernikahan adat Melayu dengan nuansa kuning kerajaan dan songket',
    eventTypes: ['wedding'],
    previewImage: '/templates/wedding-melayu.jpg',
    isPremium: false,
    colorScheme: { primary: '#FBC02D', secondary: '#FFF9C4', background: '#FFFDE7', text: '#F57F17' },
    sections: defaultSections,
    style: 'elegant',
  },
  {
    id: 'wedding-toraja-sakral',
    name: 'Toraja Sakral',
    description: 'Tema pernikahan adat Toraja dengan nuansa merah hitam tongkonan',
    eventTypes: ['wedding'],
    previewImage: '/templates/wedding-toraja.jpg',
    isPremium: false,
    colorScheme: { primary: '#B71C1C', secondary: '#212121', background: '#FFF8F5', text: '#4E0000' },
    sections: defaultSections,
    style: 'rustic',
  },
  {
    id: 'wedding-ambon-cerah',
    name: 'Ambon Cerah',
    description: 'Tema pernikahan adat Ambon/Maluku dengan nuansa biru laut dan putih pela gandong',
    eventTypes: ['wedding'],
    previewImage: '/templates/wedding-ambon.jpg',
    isPremium: false,
    colorScheme: { primary: '#0277BD', secondary: '#E1F5FE', background: '#F5FBFF', text: '#01579B' },
    sections: defaultSections,
    style: 'modern',
  },
  {
    id: 'wedding-papua-mulia',
    name: 'Papua Mulia',
    description: 'Tema pernikahan adat Papua dengan nuansa coklat tanah dan motif tifa',
    eventTypes: ['wedding'],
    previewImage: '/templates/wedding-papua.jpg',
    isPremium: false,
    colorScheme: { primary: '#6D4C41', secondary: '#D7CCC8', background: '#FAF3EF', text: '#4E342E' },
    sections: defaultSections,
    style: 'rustic',
  },
  {
    id: 'wedding-tionghoa-harmoni',
    name: 'Tionghoa Harmoni',
    description: 'Tema pernikahan Tionghoa Indonesia dengan nuansa merah keberuntungan dan emas',
    eventTypes: ['wedding'],
    previewImage: '/templates/wedding-tionghoa.jpg',
    isPremium: false,
    colorScheme: { primary: '#D32F2F', secondary: '#FFD54F', background: '#FFF8F0', text: '#B71C1C' },
    sections: defaultSections,
    style: 'elegant',
  },
  {
    id: 'wedding-lampung-agung',
    name: 'Lampung Agung',
    description: 'Tema pernikahan adat Lampung dengan nuansa tapis emas dan merah',
    eventTypes: ['wedding'],
    previewImage: '/templates/wedding-lampung.jpg',
    isPremium: false,
    colorScheme: { primary: '#8D6E63', secondary: '#FFE0B2', background: '#FFF8F0', text: '#5D4037' },
    sections: defaultSections,
    style: 'classic',
  },

  // ── NEW: Religion-themed Wedding Templates ──
  {
    id: 'wedding-islami-mewah',
    name: 'Islami Mewah',
    description: 'Undangan pernikahan islami dengan kaligrafi Arab dan motif bulan sabit emas',
    eventTypes: ['wedding'],
    previewImage: '/templates/wedding-islami.jpg',
    isPremium: false,
    colorScheme: { primary: '#1B5E20', secondary: '#FFF8E1', background: '#F5FBF0', text: '#0D3B0F' },
    sections: defaultSections,
    style: 'elegant',
  },
  {
    id: 'wedding-kristen-sakral',
    name: 'Kristen Sakral',
    description: 'Undangan pernikahan Kristen dengan motif salib dan lonceng gereja',
    eventTypes: ['wedding'],
    previewImage: '/templates/wedding-kristen.jpg',
    isPremium: false,
    colorScheme: { primary: '#5C6BC0', secondary: '#E8EAF6', background: '#FAFBFF', text: '#283593' },
    sections: defaultSections,
    style: 'classic',
  },
  {
    id: 'wedding-katolik-agung',
    name: 'Katolik Agung',
    description: 'Undangan pernikahan Katolik dengan motif katedral dan rosario emas',
    eventTypes: ['wedding'],
    previewImage: '/templates/wedding-katolik.jpg',
    isPremium: false,
    colorScheme: { primary: '#6D4C41', secondary: '#D7CCC8', background: '#FAF5F0', text: '#3E2723' },
    sections: defaultSections,
    style: 'elegant',
  },
  {
    id: 'wedding-hindu-suci',
    name: 'Hindu Suci',
    description: 'Undangan pernikahan Hindu dengan motif mandala dan simbol Om sakral',
    eventTypes: ['wedding'],
    previewImage: '/templates/wedding-hindu.jpg',
    isPremium: false,
    colorScheme: { primary: '#E65100', secondary: '#FFF3E0', background: '#FFFBF5', text: '#BF360C' },
    sections: defaultSections,
    style: 'classic',
  },
  {
    id: 'wedding-buddha-harmoni',
    name: 'Buddha Harmoni',
    description: 'Undangan pernikahan Buddhis dengan motif teratai dan roda dharma',
    eventTypes: ['wedding'],
    previewImage: '/templates/wedding-buddha.jpg',
    isPremium: false,
    colorScheme: { primary: '#F9A825', secondary: '#FFF8E1', background: '#FFFDE7', text: '#F57F17' },
    sections: defaultSections,
    style: 'elegant',
  },

  // ── NEW: Famous City-themed Wedding Templates ──
  {
    id: 'wedding-paris-romantis',
    name: 'Paris Romantis',
    description: 'Undangan pernikahan bertema kota cinta Paris dengan nuansa lavender dan emas',
    eventTypes: ['wedding'],
    previewImage: '/templates/wedding-paris.jpg',
    isPremium: false,
    colorScheme: { primary: '#7E57C2', secondary: '#EDE7F6', background: '#FAF5FF', text: '#4527A0' },
    sections: defaultSections,
    style: 'elegant',
  },
  {
    id: 'wedding-tokyo-sakura',
    name: 'Tokyo Sakura',
    description: 'Undangan pernikahan bertema Jepang dengan motif bunga sakura dan pola tradisional',
    eventTypes: ['wedding'],
    previewImage: '/templates/wedding-tokyo.jpg',
    isPremium: false,
    colorScheme: { primary: '#E91E63', secondary: '#FCE4EC', background: '#FFF8FA', text: '#880E4F' },
    sections: defaultSections,
    style: 'minimalist',
  },
  {
    id: 'wedding-istanbul-megah',
    name: 'Istanbul Megah',
    description: 'Undangan pernikahan bertema Turki dengan pola arabesque dan kubah masjid',
    eventTypes: ['wedding'],
    previewImage: '/templates/wedding-istanbul.jpg',
    isPremium: false,
    colorScheme: { primary: '#00838F', secondary: '#E0F7FA', background: '#F5FDFF', text: '#006064' },
    sections: defaultSections,
    style: 'elegant',
  },
  {
    id: 'wedding-jogja-heritage',
    name: 'Jogja Heritage',
    description: 'Undangan pernikahan bertema keraton Yogyakarta dengan batik parang dan wayang',
    eventTypes: ['wedding'],
    previewImage: '/templates/wedding-jogja.jpg',
    isPremium: false,
    colorScheme: { primary: '#795548', secondary: '#EFEBE9', background: '#FAF8F5', text: '#4E342E' },
    sections: defaultSections,
    style: 'classic',
  },
  {
    id: 'wedding-venice-elegan',
    name: 'Venice Elegan',
    description: 'Undangan pernikahan bertema Venesia dengan nuansa biru air dan emas gondola',
    eventTypes: ['wedding'],
    previewImage: '/templates/wedding-venice.jpg',
    isPremium: false,
    colorScheme: { primary: '#1565C0', secondary: '#E3F2FD', background: '#F5F9FF', text: '#0D47A1' },
    sections: defaultSections,
    style: 'elegant',
  },

  // ── NEW: Climate/Nature-themed Wedding Templates ──
  {
    id: 'wedding-garden-boho',
    name: 'Garden Boho',
    description: 'Undangan pernikahan bohemian dengan bunga liar dan nuansa earthy alami',
    eventTypes: ['wedding'],
    previewImage: '/templates/wedding-garden.jpg',
    isPremium: false,
    colorScheme: { primary: '#8D6E63', secondary: '#EFEBE9', background: '#FBF8F4', text: '#5D4037' },
    sections: defaultSections,
    style: 'rustic',
  },
  {
    id: 'wedding-pantai-sunset',
    name: 'Pantai Sunset',
    description: 'Undangan pernikahan bertema pantai matahari terbenam dengan gradasi oranye dan biru',
    eventTypes: ['wedding'],
    previewImage: '/templates/wedding-pantai.jpg',
    isPremium: false,
    colorScheme: { primary: '#E65100', secondary: '#FFE0B2', background: '#FFF8F0', text: '#BF360C' },
    sections: defaultSections,
    style: 'modern',
  },
  {
    id: 'wedding-winter-frost',
    name: 'Winter Frost',
    description: 'Undangan pernikahan bertema musim dingin dengan motif kristal es dan warna biru es',
    eventTypes: ['wedding'],
    previewImage: '/templates/wedding-winter.jpg',
    isPremium: false,
    colorScheme: { primary: '#4FC3F7', secondary: '#E1F5FE', background: '#F5FCFF', text: '#0277BD' },
    sections: defaultSections,
    style: 'minimalist',
  },
  {
    id: 'wedding-autumn-warm',
    name: 'Autumn Warmth',
    description: 'Undangan pernikahan bertema musim gugur dengan daun maple dan nuansa amber hangat',
    eventTypes: ['wedding'],
    previewImage: '/templates/wedding-autumn.jpg',
    isPremium: false,
    colorScheme: { primary: '#E64A19', secondary: '#FBE9E7', background: '#FFF5F0', text: '#BF360C' },
    sections: defaultSections,
    style: 'rustic',
  },

  // ── NEW: Identity/Culture-themed Wedding Templates ──
  {
    id: 'wedding-nusantara-fusion',
    name: 'Nusantara Fusion',
    description: 'Undangan pernikahan lintas budaya Indonesia dengan motif multi-etnis nusantara',
    eventTypes: ['wedding'],
    previewImage: '/templates/wedding-nusantara.jpg',
    isPremium: false,
    colorScheme: { primary: '#C62828', secondary: '#FFE082', background: '#FFF8F0', text: '#8E0000' },
    sections: defaultSections,
    style: 'elegant',
  },
  {
    id: 'wedding-arab-luxury',
    name: 'Arab Luxury',
    description: 'Undangan pernikahan mewah bergaya Arab dengan pola geometris arabesque emas',
    eventTypes: ['wedding'],
    previewImage: '/templates/wedding-arab.jpg',
    isPremium: false,
    colorScheme: { primary: '#C9A962', secondary: '#FFF8E1', background: '#1A1A2E', text: '#E0D5B7' },
    sections: defaultSections,
    style: 'elegant',
  },
  {
    id: 'wedding-india-bollywood',
    name: 'India Bollywood',
    description: 'Undangan pernikahan bergaya Bollywood dengan motif paisley, henna, dan warna vibrant',
    eventTypes: ['wedding'],
    previewImage: '/templates/wedding-india.jpg',
    isPremium: false,
    colorScheme: { primary: '#AD1457', secondary: '#FCE4EC', background: '#FFF5F8', text: '#880E4F' },
    sections: defaultSections,
    style: 'elegant',
  },
  {
    id: 'wedding-korea-hanbok',
    name: 'Korea Hanbok',
    description: 'Undangan pernikahan bertema Korea dengan nuansa pastel hanbok dan motif dancheong',
    eventTypes: ['wedding'],
    previewImage: '/templates/wedding-korea.jpg',
    isPremium: false,
    colorScheme: { primary: '#D81B60', secondary: '#F8BBD0', background: '#FFF8FA', text: '#AD1457' },
    sections: defaultSections,
    style: 'minimalist',
  },

  // ── NEW: Modern Lifestyle Wedding Templates ──
  {
    id: 'wedding-industrial-chic',
    name: 'Industrial Chic',
    description: 'Undangan pernikahan bergaya industrial dengan aksen tembaga dan tekstur beton',
    eventTypes: ['wedding'],
    previewImage: '/templates/wedding-industrial.jpg',
    isPremium: false,
    colorScheme: { primary: '#795548', secondary: '#D7CCC8', background: '#EFEBE9', text: '#3E2723' },
    sections: defaultSections,
    style: 'modern',
  },
  {
    id: 'wedding-art-deco-gatsby',
    name: 'Art Deco Gatsby',
    description: 'Undangan pernikahan bergaya Art Deco era 1920-an dengan pola geometris emas mewah',
    eventTypes: ['wedding'],
    previewImage: '/templates/wedding-gatsby.jpg',
    isPremium: false,
    colorScheme: { primary: '#C9A962', secondary: '#212121', background: '#1A1A1A', text: '#E8DCC8' },
    sections: defaultSections,
    style: 'elegant',
  },

  // ── Khitanan Templates (1 free, 3 premium) ──
  {
    id: 'khitanan-festive-blue',
    name: 'Biru Ceria',
    description: 'Desain ceria dengan warna biru yang menyegarkan',
    eventTypes: ['khitanan'],
    previewImage: '/templates/khitanan-blue.jpg',
    isPremium: false,
    colorScheme: { primary: '#2196f3', secondary: '#e3f2fd', background: '#ffffff', text: '#1565c0' },
    sections: defaultSections,
    style: 'modern',
  },
  {
    id: 'khitanan-islamic-green',
    name: 'Hijau Islami',
    description: 'Desain islami dengan nuansa hijau yang tenang',
    eventTypes: ['khitanan'],
    previewImage: '/templates/khitanan-green.jpg',
    isPremium: false,
    colorScheme: { primary: '#2e7d32', secondary: '#e8f5e9', background: '#fafafa', text: '#1b5e20' },
    sections: defaultSections,
    style: 'classic',
  },
  {
    id: 'khitanan-golden-festive',
    name: 'Emas Meriah',
    description: 'Desain meriah dengan aksen emas dan biru tua',
    eventTypes: ['khitanan'],
    previewImage: '/templates/khitanan-golden.jpg',
    isPremium: false,
    colorScheme: { primary: '#d4a017', secondary: '#fff8e1', background: '#fffef5', text: '#5d4e0e' },
    sections: defaultSections,
    style: 'elegant',
  },
  {
    id: 'khitanan-playful-teal',
    name: 'Teal Playful',
    description: 'Desain playful dengan warna teal yang segar',
    eventTypes: ['khitanan'],
    previewImage: '/templates/khitanan-teal.jpg',
    isPremium: false,
    colorScheme: { primary: '#00897b', secondary: '#e0f2f1', background: '#ffffff', text: '#004d40' },
    sections: defaultSections,
    style: 'modern',
  },
  {
    id: 'khitanan-orange-meriah',
    name: 'Oranye Meriah',
    description: 'Desain ceria dengan warna oranye yang semangat',
    eventTypes: ['khitanan'],
    previewImage: '/templates/khitanan-orange.jpg',
    isPremium: false,
    colorScheme: { primary: '#ef6c00', secondary: '#fff3e0', background: '#fffbf5', text: '#e65100' },
    sections: defaultSections,
    style: 'modern',
  },
  {
    id: 'khitanan-purple-joyful',
    name: 'Ungu Gembira',
    description: 'Nuansa ungu penuh kegembiraan untuk khitanan',
    eventTypes: ['khitanan'],
    previewImage: '/templates/khitanan-purple.jpg',
    isPremium: false,
    colorScheme: { primary: '#7b1fa2', secondary: '#f3e5f5', background: '#fdf5ff', text: '#4a148c' },
    sections: defaultSections,
    style: 'elegant',
  },

  // ── Hajatan Templates ──
  {
    id: 'hajatan-warm-earth',
    name: 'Hangat Bumi',
    description: 'Desain hangat dengan warna tanah yang menenangkan',
    eventTypes: ['hajatan'],
    previewImage: '/templates/hajatan-earth.jpg',
    isPremium: false,
    colorScheme: { primary: '#8d6e63', secondary: '#efebe9', background: '#fafaf9', text: '#5d4037' },
    sections: simpleSections,
    style: 'rustic',
  },
  {
    id: 'hajatan-simple-sage',
    name: 'Sage Sederhana',
    description: 'Desain minimalis dengan warna sage yang elegan',
    eventTypes: ['hajatan'],
    previewImage: '/templates/hajatan-sage.jpg',
    isPremium: false,
    colorScheme: { primary: '#6b8e6b', secondary: '#e8f0e8', background: '#ffffff', text: '#4a5d4a' },
    sections: simpleSections,
    style: 'minimalist',
  },
  {
    id: 'hajatan-classic-maroon',
    name: 'Maroon Klasik',
    description: 'Nuansa maroon klasik yang hangat dan bermartabat',
    eventTypes: ['hajatan'],
    previewImage: '/templates/hajatan-maroon.jpg',
    isPremium: false,
    colorScheme: { primary: '#7b1f3a', secondary: '#fce4ec', background: '#fff8f9', text: '#5a1028' },
    sections: simpleSections,
    style: 'classic',
  },
  {
    id: 'hajatan-modern-teal',
    name: 'Teal Modern',
    description: 'Desain modern dengan warna teal yang segar',
    eventTypes: ['hajatan'],
    previewImage: '/templates/hajatan-teal.jpg',
    isPremium: false,
    colorScheme: { primary: '#00796b', secondary: '#e0f2f1', background: '#ffffff', text: '#004d40' },
    sections: simpleSections,
    style: 'modern',
  },
  {
    id: 'hajatan-navy-formal',
    name: 'Navy Formal',
    description: 'Desain formal dengan nuansa navy yang elegan',
    eventTypes: ['hajatan'],
    previewImage: '/templates/hajatan-navy.jpg',
    isPremium: false,
    colorScheme: { primary: '#1a237e', secondary: '#c5cae9', background: '#f5f5ff', text: '#0d1257' },
    sections: simpleSections,
    style: 'elegant',
  },
  {
    id: 'hajatan-gold-berkah',
    name: 'Emas Berkah',
    description: 'Nuansa emas penuh berkah untuk syukuran hajatan',
    eventTypes: ['hajatan'],
    previewImage: '/templates/hajatan-gold.jpg',
    isPremium: false,
    colorScheme: { primary: '#c9a962', secondary: '#fff8e1', background: '#fffef5', text: '#5d4e0e' },
    sections: simpleSections,
    style: 'classic',
  },

  // ── Birthday Templates ──
  {
    id: 'birthday-colorful-party',
    name: 'Pesta Warna',
    description: 'Desain penuh warna untuk pesta yang meriah',
    eventTypes: ['birthday'],
    previewImage: '/templates/birthday-colorful.jpg',
    isPremium: false,
    colorScheme: { primary: '#9c27b0', secondary: '#f3e5f5', background: '#ffffff', text: '#6a1b9a' },
    sections: defaultSections,
    style: 'modern',
  },
  {
    id: 'birthday-elegant-rose',
    name: 'Mawar Elegan',
    description: 'Desain elegan untuk ulang tahun dewasa',
    eventTypes: ['birthday'],
    previewImage: '/templates/birthday-rose.jpg',
    isPremium: false,
    colorScheme: { primary: '#c2185b', secondary: '#fce4ec', background: '#fff8fa', text: '#880e4f' },
    sections: defaultSections,
    style: 'elegant',
  },
  {
    id: 'birthday-tropical-fun',
    name: 'Tropical Fun',
    description: 'Desain tropis yang ceria dan penuh semangat',
    eventTypes: ['birthday'],
    previewImage: '/templates/birthday-tropical.jpg',
    isPremium: false,
    colorScheme: { primary: '#ff6f00', secondary: '#fff3e0', background: '#fffdf5', text: '#e65100' },
    sections: defaultSections,
    style: 'modern',
  },
  {
    id: 'birthday-pastel-dream',
    name: 'Pastel Dream',
    description: 'Nuansa pastel yang lembut dan bermimpi',
    eventTypes: ['birthday'],
    previewImage: '/templates/birthday-pastel.jpg',
    isPremium: false,
    colorScheme: { primary: '#ab47bc', secondary: '#f3e5f5', background: '#fef9ff', text: '#7b1fa2' },
    sections: defaultSections,
    style: 'minimalist',
  },
  {
    id: 'birthday-blue-party',
    name: 'Biru Pesta',
    description: 'Nuansa biru ceria untuk pesta ulang tahun',
    eventTypes: ['birthday'],
    previewImage: '/templates/birthday-blue.jpg',
    isPremium: false,
    colorScheme: { primary: '#1976d2', secondary: '#bbdefb', background: '#f5f9ff', text: '#0d47a1' },
    sections: defaultSections,
    style: 'modern',
  },
  {
    id: 'birthday-gold-glamour',
    name: 'Emas Glamor',
    description: 'Desain glamor dengan sentuhan emas mewah',
    eventTypes: ['birthday'],
    previewImage: '/templates/birthday-gold.jpg',
    isPremium: false,
    colorScheme: { primary: '#c9a962', secondary: '#fff8e1', background: '#fffef5', text: '#5d4e0e' },
    sections: defaultSections,
    style: 'elegant',
  },

  // ── Family Gathering Templates ──
  {
    id: 'family-warm-orange',
    name: 'Oranye Hangat',
    description: 'Desain hangat untuk pertemuan keluarga',
    eventTypes: ['family'],
    previewImage: '/templates/family-orange.jpg',
    isPremium: false,
    colorScheme: { primary: '#e65100', secondary: '#fff3e0', background: '#fffbf5', text: '#bf360c' },
    sections: simpleSections,
    style: 'modern',
  },
  {
    id: 'family-classic-brown',
    name: 'Coklat Klasik',
    description: 'Desain klasik yang hangat dan nyaman',
    eventTypes: ['family'],
    previewImage: '/templates/family-brown.jpg',
    isPremium: false,
    colorScheme: { primary: '#795548', secondary: '#efebe9', background: '#faf8f5', text: '#4e342e' },
    sections: simpleSections,
    style: 'classic',
  },
  {
    id: 'family-garden-green',
    name: 'Hijau Taman',
    description: 'Nuansa taman hijau yang menyegarkan',
    eventTypes: ['family'],
    previewImage: '/templates/family-green.jpg',
    isPremium: false,
    colorScheme: { primary: '#388e3c', secondary: '#e8f5e9', background: '#f9fdf9', text: '#1b5e20' },
    sections: simpleSections,
    style: 'rustic',
  },
  {
    id: 'family-sunset-gold',
    name: 'Emas Senja',
    description: 'Warna senja keemasan yang hangat dan indah',
    eventTypes: ['family'],
    previewImage: '/templates/family-sunset.jpg',
    isPremium: false,
    colorScheme: { primary: '#f57c00', secondary: '#ffe0b2', background: '#fffcf5', text: '#e65100' },
    sections: simpleSections,
    style: 'elegant',
  },
  {
    id: 'family-blue-harmony',
    name: 'Biru Harmoni',
    description: 'Nuansa biru yang harmonis untuk kebersamaan keluarga',
    eventTypes: ['family'],
    previewImage: '/templates/family-blue.jpg',
    isPremium: false,
    colorScheme: { primary: '#1565c0', secondary: '#e3f2fd', background: '#f5f9ff', text: '#0d47a1' },
    sections: simpleSections,
    style: 'modern',
  },
  {
    id: 'family-cream-hangat',
    name: 'Krem Hangat',
    description: 'Desain krem yang nyaman dan penuh kehangatan',
    eventTypes: ['family'],
    previewImage: '/templates/family-cream.jpg',
    isPremium: false,
    colorScheme: { primary: '#8d6e63', secondary: '#efebe9', background: '#faf8f5', text: '#5d4037' },
    sections: simpleSections,
    style: 'classic',
  },

  // ── Aqiqah Templates ──
  {
    id: 'aqiqah-soft-pink',
    name: 'Pink Lembut',
    description: 'Desain lembut untuk menyambut buah hati',
    eventTypes: ['aqiqah'],
    previewImage: '/templates/aqiqah-pink.jpg',
    isPremium: false,
    colorScheme: { primary: '#e91e63', secondary: '#fce4ec', background: '#fff8fa', text: '#880e4f' },
    sections: simpleSections,
    style: 'modern',
  },
  {
    id: 'aqiqah-islamic-teal',
    name: 'Teal Islami',
    description: 'Nuansa islami yang tenang untuk aqiqah',
    eventTypes: ['aqiqah'],
    previewImage: '/templates/aqiqah-teal.jpg',
    isPremium: false,
    colorScheme: { primary: '#00695c', secondary: '#e0f2f1', background: '#fafffe', text: '#004d40' },
    sections: simpleSections,
    style: 'classic',
  },
  {
    id: 'aqiqah-sky-blue',
    name: 'Biru Langit',
    description: 'Nuansa biru langit cerah untuk menyambut si kecil',
    eventTypes: ['aqiqah'],
    previewImage: '/templates/aqiqah-blue.jpg',
    isPremium: false,
    colorScheme: { primary: '#039be5', secondary: '#e1f5fe', background: '#f5fbff', text: '#01579b' },
    sections: simpleSections,
    style: 'modern',
  },
  {
    id: 'aqiqah-lavender-sweet',
    name: 'Lavender Manis',
    description: 'Warna lavender yang manis untuk aqiqah',
    eventTypes: ['aqiqah'],
    previewImage: '/templates/aqiqah-lavender.jpg',
    isPremium: false,
    colorScheme: { primary: '#7e57c2', secondary: '#ede7f6', background: '#faf5ff', text: '#4527a0' },
    sections: simpleSections,
    style: 'elegant',
  },
  {
    id: 'aqiqah-green-berkah',
    name: 'Hijau Berkah',
    description: 'Nuansa hijau penuh berkah untuk aqiqah',
    eventTypes: ['aqiqah'],
    previewImage: '/templates/aqiqah-green.jpg',
    isPremium: false,
    colorScheme: { primary: '#2e7d32', secondary: '#e8f5e9', background: '#f5faf5', text: '#1b5e20' },
    sections: simpleSections,
    style: 'classic',
  },
  {
    id: 'aqiqah-cream-warm',
    name: 'Krem Hangat',
    description: 'Desain krem hangat untuk momen bahagia',
    eventTypes: ['aqiqah'],
    previewImage: '/templates/aqiqah-cream.jpg',
    isPremium: false,
    colorScheme: { primary: '#a1887f', secondary: '#efebe9', background: '#faf8f5', text: '#5d4037' },
    sections: simpleSections,
    style: 'minimalist',
  },

  // ── Tahlilan Templates ──
  {
    id: 'tahlilan-serene-green',
    name: 'Hijau Khusyuk',
    description: 'Desain tenang dan khusyuk untuk acara tahlilan',
    eventTypes: ['tahlilan'],
    previewImage: '/templates/tahlilan-green.jpg',
    isPremium: false,
    colorScheme: { primary: '#2e7d32', secondary: '#e8f5e9', background: '#f5faf5', text: '#1b5e20' },
    sections: simpleSections,
    style: 'classic',
  },
  {
    id: 'tahlilan-calm-grey',
    name: 'Abu Tenang',
    description: 'Nuansa abu-abu yang tenang dan bermartabat',
    eventTypes: ['tahlilan'],
    previewImage: '/templates/tahlilan-grey.jpg',
    isPremium: false,
    colorScheme: { primary: '#546e7a', secondary: '#eceff1', background: '#fafafa', text: '#37474f' },
    sections: simpleSections,
    style: 'minimalist',
  },
  {
    id: 'tahlilan-navy-solemn',
    name: 'Navy Khidmat',
    description: 'Nuansa navy yang khidmat dan bermartabat',
    eventTypes: ['tahlilan'],
    previewImage: '/templates/tahlilan-navy.jpg',
    isPremium: false,
    colorScheme: { primary: '#1a237e', secondary: '#c5cae9', background: '#f5f5ff', text: '#0d1257' },
    sections: simpleSections,
    style: 'elegant',
  },
  {
    id: 'tahlilan-brown-warm',
    name: 'Coklat Hangat',
    description: 'Nuansa coklat hangat penuh kehangatan',
    eventTypes: ['tahlilan'],
    previewImage: '/templates/tahlilan-brown.jpg',
    isPremium: false,
    colorScheme: { primary: '#5d4037', secondary: '#efebe9', background: '#faf8f5', text: '#3e2723' },
    sections: simpleSections,
    style: 'classic',
  },
  {
    id: 'tahlilan-teal-damai',
    name: 'Teal Damai',
    description: 'Warna teal yang menenangkan untuk tahlilan',
    eventTypes: ['tahlilan'],
    previewImage: '/templates/tahlilan-teal.jpg',
    isPremium: false,
    colorScheme: { primary: '#00695c', secondary: '#e0f2f1', background: '#fafffe', text: '#004d40' },
    sections: simpleSections,
    style: 'modern',
  },
  {
    id: 'tahlilan-cream-simple',
    name: 'Krem Sederhana',
    description: 'Desain krem sederhana dan bermartabat',
    eventTypes: ['tahlilan'],
    previewImage: '/templates/tahlilan-cream.jpg',
    isPremium: false,
    colorScheme: { primary: '#8d6e63', secondary: '#efebe9', background: '#faf8f5', text: '#5d4037' },
    sections: simpleSections,
    style: 'minimalist',
  },

  // ── Pengajian Templates ──
  {
    id: 'pengajian-green-gold',
    name: 'Hijau Emas',
    description: 'Nuansa islami hijau dan emas untuk pengajian',
    eventTypes: ['pengajian'],
    previewImage: '/templates/pengajian-green.jpg',
    isPremium: false,
    colorScheme: { primary: '#1b5e20', secondary: '#fff8e1', background: '#f9fdf5', text: '#0d3b0f' },
    sections: simpleSections,
    style: 'classic',
  },
  {
    id: 'pengajian-royal-blue',
    name: 'Biru Masjid',
    description: 'Warna biru masjid yang elegan',
    eventTypes: ['pengajian'],
    previewImage: '/templates/pengajian-blue.jpg',
    isPremium: false,
    colorScheme: { primary: '#1565c0', secondary: '#e3f2fd', background: '#f5f9ff', text: '#0d47a1' },
    sections: simpleSections,
    style: 'elegant',
  },
  {
    id: 'pengajian-teal-islami',
    name: 'Teal Islami',
    description: 'Nuansa teal islami yang sejuk',
    eventTypes: ['pengajian'],
    previewImage: '/templates/pengajian-teal.jpg',
    isPremium: false,
    colorScheme: { primary: '#00695c', secondary: '#e0f2f1', background: '#fafffe', text: '#004d40' },
    sections: simpleSections,
    style: 'modern',
  },
  {
    id: 'pengajian-gold-masjid',
    name: 'Emas Masjid',
    description: 'Nuansa emas masjid yang megah',
    eventTypes: ['pengajian'],
    previewImage: '/templates/pengajian-gold.jpg',
    isPremium: false,
    colorScheme: { primary: '#c9a962', secondary: '#fff8e1', background: '#fffef5', text: '#5d4e0e' },
    sections: simpleSections,
    style: 'elegant',
  },
  {
    id: 'pengajian-brown-classic',
    name: 'Coklat Klasik',
    description: 'Desain klasik coklat untuk pengajian',
    eventTypes: ['pengajian'],
    previewImage: '/templates/pengajian-brown.jpg',
    isPremium: false,
    colorScheme: { primary: '#5d4037', secondary: '#efebe9', background: '#faf8f5', text: '#3e2723' },
    sections: simpleSections,
    style: 'classic',
  },
  {
    id: 'pengajian-white-clean',
    name: 'Putih Bersih',
    description: 'Desain putih bersih yang minimalis',
    eventTypes: ['pengajian'],
    previewImage: '/templates/pengajian-white.jpg',
    isPremium: false,
    colorScheme: { primary: '#455a64', secondary: '#eceff1', background: '#ffffff', text: '#263238' },
    sections: simpleSections,
    style: 'minimalist',
  },

  // ── Wisuda Templates ──
  {
    id: 'wisuda-navy-gold',
    name: 'Navy & Emas',
    description: 'Desain formal wisuda dengan navy dan emas',
    eventTypes: ['wisuda'],
    previewImage: '/templates/wisuda-navy.jpg',
    isPremium: false,
    colorScheme: { primary: '#1a237e', secondary: '#c5cae9', background: '#f5f5ff', text: '#1a237e' },
    sections: defaultSections,
    style: 'elegant',
  },
  {
    id: 'wisuda-maroon-classic',
    name: 'Maroon Wisuda',
    description: 'Nuansa maroon akademis yang bermartabat',
    eventTypes: ['wisuda'],
    previewImage: '/templates/wisuda-maroon.jpg',
    isPremium: false,
    colorScheme: { primary: '#7b1f3a', secondary: '#fce4ec', background: '#fff8f9', text: '#5a1028' },
    sections: defaultSections,
    style: 'classic',
  },
  {
    id: 'wisuda-green-campus',
    name: 'Hijau Kampus',
    description: 'Nuansa hijau kampus yang segar',
    eventTypes: ['wisuda'],
    previewImage: '/templates/wisuda-green.jpg',
    isPremium: false,
    colorScheme: { primary: '#2e7d32', secondary: '#e8f5e9', background: '#f5faf5', text: '#1b5e20' },
    sections: defaultSections,
    style: 'modern',
  },
  {
    id: 'wisuda-black-gold',
    name: 'Hitam Emas',
    description: 'Desain mewah hitam dan emas untuk wisuda',
    eventTypes: ['wisuda'],
    previewImage: '/templates/wisuda-black.jpg',
    isPremium: false,
    colorScheme: { primary: '#212121', secondary: '#c9a962', background: '#faf8f5', text: '#1a1a1a' },
    sections: defaultSections,
    style: 'elegant',
  },
  {
    id: 'wisuda-blue-academic',
    name: 'Biru Akademik',
    description: 'Nuansa biru akademik yang formal',
    eventTypes: ['wisuda'],
    previewImage: '/templates/wisuda-blue.jpg',
    isPremium: false,
    colorScheme: { primary: '#1565c0', secondary: '#e3f2fd', background: '#f5f9ff', text: '#0d47a1' },
    sections: defaultSections,
    style: 'modern',
  },
  {
    id: 'wisuda-purple-toga',
    name: 'Ungu Toga',
    description: 'Warna ungu toga yang megah',
    eventTypes: ['wisuda'],
    previewImage: '/templates/wisuda-purple.jpg',
    isPremium: false,
    colorScheme: { primary: '#6a1b9a', secondary: '#e1bee7', background: '#fdf5ff', text: '#4a148c' },
    sections: defaultSections,
    style: 'classic',
  },

  // ── Lamaran Templates ──
  {
    id: 'lamaran-rose-gold',
    name: 'Rose Gold',
    description: 'Desain romantis dengan nuansa rose gold',
    eventTypes: ['lamaran'],
    previewImage: '/templates/lamaran-rose.jpg',
    isPremium: false,
    colorScheme: { primary: '#b76e79', secondary: '#fce4ec', background: '#fff8fa', text: '#6d3a42' },
    sections: defaultSections,
    style: 'elegant',
  },
  {
    id: 'lamaran-sage-romantic',
    name: 'Sage Romantis',
    description: 'Nuansa sage hijau lembut yang romantis',
    eventTypes: ['lamaran'],
    previewImage: '/templates/lamaran-sage.jpg',
    isPremium: false,
    colorScheme: { primary: '#7a9e7e', secondary: '#e8f0e8', background: '#fafdf9', text: '#3d4f3d' },
    sections: defaultSections,
    style: 'rustic',
  },
  {
    id: 'lamaran-blush-pink',
    name: 'Blush Romantis',
    description: 'Nuansa pink blush yang lembut dan romantis',
    eventTypes: ['lamaran'],
    previewImage: '/templates/lamaran-blush.jpg',
    isPremium: false,
    colorScheme: { primary: '#d4a5a5', secondary: '#f8e8e8', background: '#ffffff', text: '#4a4a4a' },
    sections: defaultSections,
    style: 'modern',
  },
  {
    id: 'lamaran-navy-classic',
    name: 'Navy Klasik',
    description: 'Desain klasik navy untuk lamaran formal',
    eventTypes: ['lamaran'],
    previewImage: '/templates/lamaran-navy.jpg',
    isPremium: false,
    colorScheme: { primary: '#1e3a5f', secondary: '#c5cae9', background: '#f5f5ff', text: '#0d1257' },
    sections: defaultSections,
    style: 'classic',
  },
  {
    id: 'lamaran-gold-mewah',
    name: 'Emas Mewah',
    description: 'Nuansa emas mewah untuk momen lamaran',
    eventTypes: ['lamaran'],
    previewImage: '/templates/lamaran-gold.jpg',
    isPremium: false,
    colorScheme: { primary: '#c9a962', secondary: '#fff8e1', background: '#fffef5', text: '#5d4e0e' },
    sections: defaultSections,
    style: 'elegant',
  },
  {
    id: 'lamaran-lavender-dream',
    name: 'Lavender Impian',
    description: 'Warna lavender yang penuh impian romantis',
    eventTypes: ['lamaran'],
    previewImage: '/templates/lamaran-lavender.jpg',
    isPremium: false,
    colorScheme: { primary: '#7e57c2', secondary: '#ede7f6', background: '#faf5ff', text: '#4527a0' },
    sections: defaultSections,
    style: 'modern',
  },

  // ── Syukuran Rumah Templates ──
  {
    id: 'syukuran-rumah-warm',
    name: 'Hangat Rumah',
    description: 'Desain hangat untuk syukuran rumah baru',
    eventTypes: ['syukuran_rumah'],
    previewImage: '/templates/syukuran-warm.jpg',
    isPremium: false,
    colorScheme: { primary: '#bf360c', secondary: '#fbe9e7', background: '#fffbf5', text: '#8d3010' },
    sections: simpleSections,
    style: 'modern',
  },
  {
    id: 'syukuran-rumah-green',
    name: 'Hijau Berkah',
    description: 'Nuansa hijau penuh berkah untuk syukuran',
    eventTypes: ['syukuran_rumah'],
    previewImage: '/templates/syukuran-green.jpg',
    isPremium: false,
    colorScheme: { primary: '#388e3c', secondary: '#e8f5e9', background: '#f5faf5', text: '#1b5e20' },
    sections: simpleSections,
    style: 'classic',
  },
  {
    id: 'syukuran-rumah-gold',
    name: 'Emas Syukur',
    description: 'Nuansa emas penuh rasa syukur',
    eventTypes: ['syukuran_rumah'],
    previewImage: '/templates/syukuran-gold.jpg',
    isPremium: false,
    colorScheme: { primary: '#c9a962', secondary: '#fff8e1', background: '#fffef5', text: '#5d4e0e' },
    sections: simpleSections,
    style: 'elegant',
  },
  {
    id: 'syukuran-rumah-blue',
    name: 'Biru Rumah',
    description: 'Warna biru yang tenang untuk rumah baru',
    eventTypes: ['syukuran_rumah'],
    previewImage: '/templates/syukuran-blue.jpg',
    isPremium: false,
    colorScheme: { primary: '#1565c0', secondary: '#e3f2fd', background: '#f5f9ff', text: '#0d47a1' },
    sections: simpleSections,
    style: 'modern',
  },
  {
    id: 'syukuran-rumah-brown',
    name: 'Coklat Nyaman',
    description: 'Nuansa coklat nyaman seperti rumah',
    eventTypes: ['syukuran_rumah'],
    previewImage: '/templates/syukuran-brown.jpg',
    isPremium: false,
    colorScheme: { primary: '#795548', secondary: '#efebe9', background: '#faf8f5', text: '#4e342e' },
    sections: simpleSections,
    style: 'classic',
  },
  {
    id: 'syukuran-rumah-cream',
    name: 'Krem Elegan',
    description: 'Desain krem elegan untuk syukuran',
    eventTypes: ['syukuran_rumah'],
    previewImage: '/templates/syukuran-cream.jpg',
    isPremium: false,
    colorScheme: { primary: '#a1887f', secondary: '#efebe9', background: '#faf8f5', text: '#5d4037' },
    sections: simpleSections,
    style: 'minimalist',
  },

  // ── Duka Cita Templates ──
  {
    id: 'duka-cita-sombre',
    name: 'Hitam Duka',
    description: 'Desain penuh penghormatan untuk berita duka',
    eventTypes: ['duka_cita'],
    previewImage: '/templates/duka-sombre.jpg',
    isPremium: false,
    colorScheme: { primary: '#37474f', secondary: '#cfd8dc', background: '#f5f5f5', text: '#263238' },
    sections: simpleSections,
    style: 'minimalist',
  },
  {
    id: 'duka-cita-white',
    name: 'Putih Damai',
    description: 'Nuansa putih dan abu-abu yang tenang',
    eventTypes: ['duka_cita'],
    previewImage: '/templates/duka-white.jpg',
    isPremium: false,
    colorScheme: { primary: '#455a64', secondary: '#eceff1', background: '#fafafa', text: '#37474f' },
    sections: simpleSections,
    style: 'minimalist',
  },
  {
    id: 'duka-cita-navy-hormat',
    name: 'Navy Hormat',
    description: 'Nuansa navy penuh penghormatan',
    eventTypes: ['duka_cita'],
    previewImage: '/templates/duka-navy.jpg',
    isPremium: false,
    colorScheme: { primary: '#1a237e', secondary: '#c5cae9', background: '#f5f5ff', text: '#0d1257' },
    sections: simpleSections,
    style: 'elegant',
  },
  {
    id: 'duka-cita-brown-tenang',
    name: 'Coklat Tenang',
    description: 'Nuansa coklat tenang penuh ketenangan',
    eventTypes: ['duka_cita'],
    previewImage: '/templates/duka-brown.jpg',
    isPremium: false,
    colorScheme: { primary: '#5d4037', secondary: '#efebe9', background: '#faf8f5', text: '#3e2723' },
    sections: simpleSections,
    style: 'classic',
  },
  {
    id: 'duka-cita-green-damai',
    name: 'Hijau Damai',
    description: 'Nuansa hijau tua yang damai dan bermartabat',
    eventTypes: ['duka_cita'],
    previewImage: '/templates/duka-green.jpg',
    isPremium: false,
    colorScheme: { primary: '#2e7d32', secondary: '#e8f5e9', background: '#f5faf5', text: '#1b5e20' },
    sections: simpleSections,
    style: 'classic',
  },
  {
    id: 'duka-cita-grey-formal',
    name: 'Abu Formal',
    description: 'Desain abu-abu formal penuh penghormatan',
    eventTypes: ['duka_cita'],
    previewImage: '/templates/duka-grey.jpg',
    isPremium: false,
    colorScheme: { primary: '#616161', secondary: '#e0e0e0', background: '#f5f5f5', text: '#424242' },
    sections: simpleSections,
    style: 'minimalist',
  },

  // ── Buka Puasa Templates ──
  {
    id: 'bukber-ramadan-gold',
    name: 'Emas Ramadan',
    description: 'Desain bernuansa Ramadan dengan emas dan hijau',
    eventTypes: ['bukber'],
    previewImage: '/templates/bukber-gold.jpg',
    isPremium: false,
    colorScheme: { primary: '#f9a825', secondary: '#e8f5e9', background: '#fffde7', text: '#5d4e0e' },
    sections: simpleSections,
    style: 'elegant',
  },
  {
    id: 'bukber-crescent-blue',
    name: 'Bulan Sabit',
    description: 'Nuansa biru malam dengan sentuhan bulan sabit',
    eventTypes: ['bukber'],
    previewImage: '/templates/bukber-blue.jpg',
    isPremium: false,
    colorScheme: { primary: '#1565c0', secondary: '#e3f2fd', background: '#f0f4ff', text: '#0d47a1' },
    sections: simpleSections,
    style: 'modern',
  },
  {
    id: 'bukber-green-islami',
    name: 'Hijau Islami',
    description: 'Nuansa hijau islami untuk buka puasa bersama',
    eventTypes: ['bukber'],
    previewImage: '/templates/bukber-green.jpg',
    isPremium: false,
    colorScheme: { primary: '#1b5e20', secondary: '#e8f5e9', background: '#f5faf5', text: '#0d3b0f' },
    sections: simpleSections,
    style: 'classic',
  },
  {
    id: 'bukber-purple-night',
    name: 'Ungu Malam',
    description: 'Nuansa ungu malam Ramadan yang syahdu',
    eventTypes: ['bukber'],
    previewImage: '/templates/bukber-purple.jpg',
    isPremium: false,
    colorScheme: { primary: '#4a148c', secondary: '#e1bee7', background: '#faf5ff', text: '#311b92' },
    sections: simpleSections,
    style: 'elegant',
  },
  {
    id: 'bukber-teal-ramadan',
    name: 'Teal Ramadan',
    description: 'Warna teal segar untuk undangan buka puasa',
    eventTypes: ['bukber'],
    previewImage: '/templates/bukber-teal.jpg',
    isPremium: false,
    colorScheme: { primary: '#00695c', secondary: '#e0f2f1', background: '#fafffe', text: '#004d40' },
    sections: simpleSections,
    style: 'modern',
  },
  {
    id: 'bukber-warm-lantern',
    name: 'Lentera Hangat',
    description: 'Nuansa hangat lentera Ramadan',
    eventTypes: ['bukber'],
    previewImage: '/templates/bukber-warm.jpg',
    isPremium: false,
    colorScheme: { primary: '#e65100', secondary: '#fff3e0', background: '#fffbf5', text: '#bf360c' },
    sections: simpleSections,
    style: 'rustic',
  },

  // ── Arisan Templates ──
  {
    id: 'arisan-fun-coral',
    name: 'Coral Ceria',
    description: 'Desain ceria dan santai untuk arisan',
    eventTypes: ['arisan'],
    previewImage: '/templates/arisan-coral.jpg',
    isPremium: false,
    colorScheme: { primary: '#ff5722', secondary: '#fbe9e7', background: '#fffaf8', text: '#bf360c' },
    sections: simpleSections,
    style: 'modern',
  },
  {
    id: 'arisan-soft-purple',
    name: 'Ungu Lembut',
    description: 'Nuansa ungu lembut untuk pertemuan santai',
    eventTypes: ['arisan'],
    previewImage: '/templates/arisan-purple.jpg',
    isPremium: false,
    colorScheme: { primary: '#7b1fa2', secondary: '#f3e5f5', background: '#fdf5ff', text: '#4a148c' },
    sections: simpleSections,
    style: 'minimalist',
  },
  {
    id: 'arisan-teal-santai',
    name: 'Teal Santai',
    description: 'Warna teal yang santai dan menyenangkan',
    eventTypes: ['arisan'],
    previewImage: '/templates/arisan-teal.jpg',
    isPremium: false,
    colorScheme: { primary: '#00897b', secondary: '#e0f2f1', background: '#fafffe', text: '#004d40' },
    sections: simpleSections,
    style: 'modern',
  },
  {
    id: 'arisan-pink-ceria',
    name: 'Pink Ceria',
    description: 'Nuansa pink yang ceria untuk arisan',
    eventTypes: ['arisan'],
    previewImage: '/templates/arisan-pink.jpg',
    isPremium: false,
    colorScheme: { primary: '#e91e63', secondary: '#fce4ec', background: '#fff8fa', text: '#880e4f' },
    sections: simpleSections,
    style: 'modern',
  },
  {
    id: 'arisan-gold-mewah',
    name: 'Emas Mewah',
    description: 'Nuansa emas mewah untuk arisan eksklusif',
    eventTypes: ['arisan'],
    previewImage: '/templates/arisan-gold.jpg',
    isPremium: false,
    colorScheme: { primary: '#c9a962', secondary: '#fff8e1', background: '#fffef5', text: '#5d4e0e' },
    sections: simpleSections,
    style: 'elegant',
  },
  {
    id: 'arisan-blue-fresh',
    name: 'Biru Segar',
    description: 'Warna biru segar untuk arisan yang menyenangkan',
    eventTypes: ['arisan'],
    previewImage: '/templates/arisan-blue.jpg',
    isPremium: false,
    colorScheme: { primary: '#1976d2', secondary: '#bbdefb', background: '#f5f9ff', text: '#0d47a1' },
    sections: simpleSections,
    style: 'modern',
  },

  // ── Acara Umum Templates ──
  {
    id: 'acara-umum-professional',
    name: 'Profesional',
    description: 'Desain profesional untuk acara formal',
    eventTypes: ['acara_umum'],
    previewImage: '/templates/umum-professional.jpg',
    isPremium: false,
    colorScheme: { primary: '#1565c0', secondary: '#e3f2fd', background: '#ffffff', text: '#0d47a1' },
    sections: simpleSections,
    style: 'modern',
  },
  {
    id: 'acara-umum-casual',
    name: 'Kasual',
    description: 'Desain santai untuk acara informal',
    eventTypes: ['acara_umum'],
    previewImage: '/templates/umum-casual.jpg',
    isPremium: false,
    colorScheme: { primary: '#00897b', secondary: '#e0f2f1', background: '#fafffe', text: '#004d40' },
    sections: simpleSections,
    style: 'minimalist',
  },
  {
    id: 'acara-umum-navy-formal',
    name: 'Navy Formal',
    description: 'Desain navy formal untuk seminar dan rapat',
    eventTypes: ['acara_umum'],
    previewImage: '/templates/umum-navy.jpg',
    isPremium: false,
    colorScheme: { primary: '#1a237e', secondary: '#c5cae9', background: '#f5f5ff', text: '#0d1257' },
    sections: simpleSections,
    style: 'elegant',
  },
  {
    id: 'acara-umum-green-fresh',
    name: 'Hijau Segar',
    description: 'Nuansa hijau segar untuk kegiatan outdoor',
    eventTypes: ['acara_umum'],
    previewImage: '/templates/umum-green.jpg',
    isPremium: false,
    colorScheme: { primary: '#2e7d32', secondary: '#e8f5e9', background: '#f5faf5', text: '#1b5e20' },
    sections: simpleSections,
    style: 'modern',
  },
  {
    id: 'acara-umum-maroon-resmi',
    name: 'Maroon Resmi',
    description: 'Nuansa maroon resmi untuk acara penting',
    eventTypes: ['acara_umum'],
    previewImage: '/templates/umum-maroon.jpg',
    isPremium: false,
    colorScheme: { primary: '#7b1f3a', secondary: '#fce4ec', background: '#fff8f9', text: '#5a1028' },
    sections: simpleSections,
    style: 'classic',
  },
  {
    id: 'acara-umum-grey-minimal',
    name: 'Abu Minimalis',
    description: 'Desain minimalis abu-abu yang bersih',
    eventTypes: ['acara_umum'],
    previewImage: '/templates/umum-grey.jpg',
    isPremium: false,
    colorScheme: { primary: '#546e7a', secondary: '#eceff1', background: '#fafafa', text: '#37474f' },
    sections: simpleSections,
    style: 'minimalist',
  },

  // ══════════════════ NEW BATCH 2: 20 MORE WEDDING TEMPLATES ══════════════════

  // ── Niche: Zodiak & Celestial (5) ──
  {
    id: 'wedding-celestial-stars',
    name: 'Celestial Stars',
    description: 'Undangan pernikahan bertema bintang dan rasi bintang dengan nuansa malam yang megah',
    eventTypes: ['wedding'],
    previewImage: '/templates/wedding-celestial.jpg',
    isPremium: false,
    colorScheme: { primary: '#FFD700', secondary: '#1A1A3E', background: '#0D0D2B', text: '#E8E0D0' },
    sections: defaultSections,
    style: 'elegant',
  },
  {
    id: 'wedding-moon-phase',
    name: 'Moon Phase',
    description: 'Undangan pernikahan bertema fase bulan dengan nuansa silver dan midnight blue',
    eventTypes: ['wedding'],
    previewImage: '/templates/wedding-moon.jpg',
    isPremium: false,
    colorScheme: { primary: '#C0C0C0', secondary: '#1A1A3E', background: '#0F0F2D', text: '#D4D0C8' },
    sections: defaultSections,
    style: 'minimalist',
  },
  {
    id: 'wedding-galaxy-nebula',
    name: 'Galaxy Nebula',
    description: 'Undangan pernikahan kosmis dengan gradasi nebula ungu-biru yang memukau',
    eventTypes: ['wedding'],
    previewImage: '/templates/wedding-galaxy.jpg',
    isPremium: false,
    colorScheme: { primary: '#9B59B6', secondary: '#2C3E50', background: '#1A0A2E', text: '#E8D5F5' },
    sections: defaultSections,
    style: 'modern',
  },
  {
    id: 'wedding-constellation',
    name: 'Constellation Map',
    description: 'Undangan pernikahan dengan peta rasi bintang yang menghubungkan dua jiwa',
    eventTypes: ['wedding'],
    previewImage: '/templates/wedding-constellation.jpg',
    isPremium: false,
    colorScheme: { primary: '#87CEEB', secondary: '#1C2541', background: '#0B132B', text: '#D0E8F2' },
    sections: defaultSections,
    style: 'minimalist',
  },
  {
    id: 'wedding-solar-eclipse',
    name: 'Solar Eclipse',
    description: 'Undangan pernikahan bertema gerhana matahari dengan efek corona emas dramatis',
    eventTypes: ['wedding'],
    previewImage: '/templates/wedding-eclipse.jpg',
    isPremium: false,
    colorScheme: { primary: '#FF6B35', secondary: '#1A1A2E', background: '#0A0A1A', text: '#F5E6D3' },
    sections: defaultSections,
    style: 'elegant',
  },

  // ── Niche: Arsitektur Dunia (5) ──
  {
    id: 'wedding-gothic-cathedral',
    name: 'Gothic Cathedral',
    description: 'Undangan pernikahan bergaya katedral gothic dengan detail stained glass dan lengkung pointed',
    eventTypes: ['wedding'],
    previewImage: '/templates/wedding-gothic.jpg',
    isPremium: false,
    colorScheme: { primary: '#8B0000', secondary: '#2C2C54', background: '#1A1A2E', text: '#E8D5C4' },
    sections: defaultSections,
    style: 'elegant',
  },
  {
    id: 'wedding-zen-garden',
    name: 'Zen Garden',
    description: 'Undangan pernikahan bertema taman zen Jepang dengan batu, pasir, dan ketenangan',
    eventTypes: ['wedding'],
    previewImage: '/templates/wedding-zen.jpg',
    isPremium: false,
    colorScheme: { primary: '#6B8E6B', secondary: '#F5F0E8', background: '#FAF8F3', text: '#3D4F3D' },
    sections: defaultSections,
    style: 'minimalist',
  },
  {
    id: 'wedding-mediterranean-villa',
    name: 'Mediterranean Villa',
    description: 'Undangan pernikahan bertema villa Mediterania dengan warna terracotta dan olive',
    eventTypes: ['wedding'],
    previewImage: '/templates/wedding-mediterranean.jpg',
    isPremium: false,
    colorScheme: { primary: '#CC7A3E', secondary: '#F5E6D3', background: '#FFF8F0', text: '#5C3A1E' },
    sections: defaultSections,
    style: 'rustic',
  },
  {
    id: 'wedding-victorian-manor',
    name: 'Victorian Manor',
    description: 'Undangan pernikahan bergaya era Victoria dengan detail ornamen klasik yang rumit',
    eventTypes: ['wedding'],
    previewImage: '/templates/wedding-victorian.jpg',
    isPremium: false,
    colorScheme: { primary: '#722F37', secondary: '#F0E6D8', background: '#FAF5EE', text: '#3D1F24' },
    sections: defaultSections,
    style: 'classic',
  },
  {
    id: 'wedding-moroccan-riad',
    name: 'Moroccan Riad',
    description: 'Undangan pernikahan bertema riad Maroko dengan pola zellige dan warna spice market',
    eventTypes: ['wedding'],
    previewImage: '/templates/wedding-moroccan.jpg',
    isPremium: false,
    colorScheme: { primary: '#C1440E', secondary: '#FFF3E0', background: '#FEF9F0', text: '#6B2D0A' },
    sections: defaultSections,
    style: 'elegant',
  },

  // ── Niche: Warna & Mood (5) ──
  {
    id: 'wedding-midnight-noir',
    name: 'Midnight Noir',
    description: 'Undangan pernikahan all-black yang dramatis dengan aksen emas yang memukau',
    eventTypes: ['wedding'],
    previewImage: '/templates/wedding-noir.jpg',
    isPremium: false,
    colorScheme: { primary: '#D4AF37', secondary: '#2A2A2A', background: '#0A0A0A', text: '#F0E8D8' },
    sections: defaultSections,
    style: 'elegant',
  },
  {
    id: 'wedding-rose-quartz',
    name: 'Rose Quartz',
    description: 'Undangan pernikahan dengan nuansa pink kristal rose quartz yang lembut dan healing',
    eventTypes: ['wedding'],
    previewImage: '/templates/wedding-rosequartz.jpg',
    isPremium: false,
    colorScheme: { primary: '#C48B9F', secondary: '#F8E8EE', background: '#FFF5F8', text: '#6B3A4E' },
    sections: defaultSections,
    style: 'modern',
  },
  {
    id: 'wedding-emerald-dream',
    name: 'Emerald Dream',
    description: 'Undangan pernikahan bertema batu zamrud dengan nuansa hijau permata yang mewah',
    eventTypes: ['wedding'],
    previewImage: '/templates/wedding-emerald.jpg',
    isPremium: false,
    colorScheme: { primary: '#046307', secondary: '#E8F5E9', background: '#F0FAF0', text: '#1B3A1C' },
    sections: defaultSections,
    style: 'elegant',
  },
  {
    id: 'wedding-copper-luxe',
    name: 'Copper Luxe',
    description: 'Undangan pernikahan mewah dengan aksen tembaga berkilau dan background warm grey',
    eventTypes: ['wedding'],
    previewImage: '/templates/wedding-copper.jpg',
    isPremium: false,
    colorScheme: { primary: '#B87333', secondary: '#F0E8DD', background: '#F8F4EE', text: '#4A3520' },
    sections: defaultSections,
    style: 'modern',
  },
  {
    id: 'wedding-lavender-mist',
    name: 'Lavender Mist',
    description: 'Undangan pernikahan dengan kabut lavender yang lembut seperti mimpi',
    eventTypes: ['wedding'],
    previewImage: '/templates/wedding-lavendermist.jpg',
    isPremium: false,
    colorScheme: { primary: '#967BB6', secondary: '#F0E6F6', background: '#FAF5FF', text: '#4A3560' },
    sections: defaultSections,
    style: 'minimalist',
  },

  // ── Niche: Musim & Fenomena Alam (5) ──
  {
    id: 'wedding-spring-blossom',
    name: 'Spring Blossom',
    description: 'Undangan pernikahan bertema musim semi dengan bunga mekar dan warna pastel segar',
    eventTypes: ['wedding'],
    previewImage: '/templates/wedding-spring.jpg',
    isPremium: false,
    colorScheme: { primary: '#E88BA5', secondary: '#FFF0F5', background: '#FFFBFD', text: '#6B3A4E' },
    sections: defaultSections,
    style: 'modern',
  },
  {
    id: 'wedding-monsoon-rain',
    name: 'Monsoon Rain',
    description: 'Undangan pernikahan bertema hujan monsun yang romantis dengan tetesan air dan awan',
    eventTypes: ['wedding'],
    previewImage: '/templates/wedding-monsoon.jpg',
    isPremium: false,
    colorScheme: { primary: '#4682B4', secondary: '#E0ECF5', background: '#F0F5FA', text: '#2C3E50' },
    sections: defaultSections,
    style: 'modern',
  },
  {
    id: 'wedding-desert-mirage',
    name: 'Desert Mirage',
    description: 'Undangan pernikahan bertema gurun pasir dengan nuansa emas dan terracotta yang eksotis',
    eventTypes: ['wedding'],
    previewImage: '/templates/wedding-desert.jpg',
    isPremium: false,
    colorScheme: { primary: '#DAA520', secondary: '#F5E6C8', background: '#FFF8EE', text: '#6B4E1E' },
    sections: defaultSections,
    style: 'elegant',
  },
  {
    id: 'wedding-northern-lights',
    name: 'Northern Lights',
    description: 'Undangan pernikahan bertema aurora borealis dengan gradasi hijau-ungu yang magis',
    eventTypes: ['wedding'],
    previewImage: '/templates/wedding-aurora.jpg',
    isPremium: false,
    colorScheme: { primary: '#00D4AA', secondary: '#1A2940', background: '#0A1628', text: '#D0F0E8' },
    sections: defaultSections,
    style: 'modern',
  },
  {
    id: 'wedding-tropical-storm',
    name: 'Tropical Storm',
    description: 'Undangan pernikahan bertema badai tropis yang dramatis dengan kilatan petir dan hujan emas',
    eventTypes: ['wedding'],
    previewImage: '/templates/wedding-storm.jpg',
    isPremium: false,
    colorScheme: { primary: '#FFD700', secondary: '#1C2833', background: '#0D1B2A', text: '#E0D8C8' },
    sections: defaultSections,
    style: 'elegant',
  },

  // ── Full Custom Template (available for all event types) ──
  // ═══════════════════════════════════════════════════════════
  // PREMIUM BUILT-IN BACKGROUND TEMPLATES (5)
  // High-quality background images, no upload needed
  // ═══════════════════════════════════════════════════════════
  {
    id: 'wedding-royal-gold-luxe',
    name: 'Royal Gold Luxe',
    description: 'Pernikahan ultra mewah hitam emas dengan ornamen baroque & partikel emas',
    eventTypes: ['wedding', 'lamaran'],
    previewImage: royalGoldBg,
    isPremium: false,
    isFullCustom: true,
    colorScheme: { primary: '#D4AF37', secondary: '#1a1410', background: '#0a0a0a', text: '#f5e6c4' },
    sections: defaultSections,
    style: 'elegant',
    defaultBackgrounds: {
      cover: royalGoldBg,
      names: royalGoldBg,
      countdown: royalGoldBg,
      datetime: royalGoldBg,
      location: royalGoldBg,
      gallery: royalGoldBg,
      rsvp: royalGoldBg,
      guestbook: royalGoldBg,
      envelope: royalGoldBg,
      closing: royalGoldBg,
    },
  },
  {
    id: 'wedding-floral-romance',
    name: 'Floral Romance',
    description: 'Pernikahan watercolor mawar putih & peony pink dengan eucalyptus emas',
    eventTypes: ['wedding', 'lamaran'],
    previewImage: floralRomanceBg,
    isPremium: false,
    isFullCustom: true,
    colorScheme: { primary: '#b08968', secondary: '#f5e6d3', background: '#fff8f0', text: '#4a3728' },
    sections: defaultSections,
    style: 'elegant',
    defaultBackgrounds: {
      cover: floralRomanceBg,
      names: floralRomanceBg,
      countdown: floralRomanceBg,
      datetime: floralRomanceBg,
      location: floralRomanceBg,
      gallery: floralRomanceBg,
      rsvp: floralRomanceBg,
      guestbook: floralRomanceBg,
      envelope: floralRomanceBg,
      closing: floralRomanceBg,
    },
  },
  {
    id: 'islamic-emerald-mosque',
    name: 'Emerald Islamic',
    description: 'Tema Islami emerald hijau dengan ornamen arabesque emas, bulan sabit & masjid',
    eventTypes: ['khitanan', 'aqiqah', 'pengajian', 'tahlilan', 'bukber', 'wedding'],
    previewImage: islamicEmeraldBg,
    isPremium: false,
    isFullCustom: true,
    colorScheme: { primary: '#D4AF37', secondary: '#1B4D2E', background: '#0F3522', text: '#F5E6C4' },
    sections: defaultSections,
    style: 'elegant',
    defaultBackgrounds: {
      cover: islamicEmeraldBg,
      names: islamicEmeraldBg,
      countdown: islamicEmeraldBg,
      datetime: islamicEmeraldBg,
      location: islamicEmeraldBg,
      gallery: islamicEmeraldBg,
      rsvp: islamicEmeraldBg,
      guestbook: islamicEmeraldBg,
      envelope: islamicEmeraldBg,
      closing: islamicEmeraldBg,
    },
  },
  {
    id: 'birthday-pastel-celebration',
    name: 'Pastel Celebration',
    description: 'Ulang tahun dreamy gradasi pastel pink-ungu-mint dengan balon emas & confetti',
    eventTypes: ['birthday', 'arisan', 'family', 'wisuda', 'acara_umum'],
    previewImage: pastelCelebrationBg,
    isPremium: false,
    isFullCustom: true,
    colorScheme: { primary: '#C9A961', secondary: '#F5C2E7', background: '#FFF5F8', text: '#5A3D5C' },
    sections: defaultSections,
    style: 'modern',
    defaultBackgrounds: {
      cover: pastelCelebrationBg,
      names: pastelCelebrationBg,
      countdown: pastelCelebrationBg,
      datetime: pastelCelebrationBg,
      location: pastelCelebrationBg,
      gallery: pastelCelebrationBg,
      rsvp: pastelCelebrationBg,
      guestbook: pastelCelebrationBg,
      envelope: pastelCelebrationBg,
      closing: pastelCelebrationBg,
    },
  },
  {
    id: 'baby-cloud-dream',
    name: 'Baby Cloud Dream',
    description: 'Aqiqah & syukuran bayi watercolor langit awan dengan bulan sabit & bintang emas',
    eventTypes: ['aqiqah', 'khitanan', 'birthday', 'family', 'syukuran_rumah'],
    previewImage: babyCloudBg,
    isPremium: false,
    isFullCustom: true,
    colorScheme: { primary: '#D4A574', secondary: '#B8D4E3', background: '#FBF5E9', text: '#4A6B7C' },
    sections: defaultSections,
    style: 'modern',
    defaultBackgrounds: {
      cover: babyCloudBg,
      names: babyCloudBg,
      countdown: babyCloudBg,
      datetime: babyCloudBg,
      location: babyCloudBg,
      gallery: babyCloudBg,
      rsvp: babyCloudBg,
      guestbook: babyCloudBg,
      envelope: babyCloudBg,
      closing: babyCloudBg,
    },
  },
  {
    id: 'wedding-rustic-burgundy',
    name: 'Rustic Burgundy',
    description: 'Pernikahan rustic burgundy & navy dengan eucalyptus, bunga kering & frame geometris emas',
    eventTypes: ['wedding', 'lamaran'],
    previewImage: rusticBurgundyBg,
    isPremium: false,
    isFullCustom: true,
    colorScheme: { primary: '#C9A961', secondary: '#7A1F2B', background: '#2A1820', text: '#F5E6C4' },
    sections: defaultSections,
    style: 'elegant',
    defaultBackgrounds: {
      cover: rusticBurgundyBg,
      names: rusticBurgundyBg,
      countdown: rusticBurgundyBg,
      datetime: rusticBurgundyBg,
      location: rusticBurgundyBg,
      gallery: rusticBurgundyBg,
      rsvp: rusticBurgundyBg,
      guestbook: rusticBurgundyBg,
      envelope: rusticBurgundyBg,
      closing: rusticBurgundyBg,
    },
  },
  {
    id: 'wedding-tropical-paradise',
    name: 'Tropical Paradise',
    description: 'Pernikahan destination tropis dengan daun monstera, pantai & sunset turquoise',
    eventTypes: ['wedding', 'lamaran', 'birthday', 'family'],
    previewImage: tropicalParadiseBg,
    isPremium: false,
    isFullCustom: true,
    colorScheme: { primary: '#0E8A8A', secondary: '#F4A261', background: '#FFF8F0', text: '#1F4747' },
    sections: defaultSections,
    style: 'modern',
    defaultBackgrounds: {
      cover: tropicalParadiseBg,
      names: tropicalParadiseBg,
      countdown: tropicalParadiseBg,
      datetime: tropicalParadiseBg,
      location: tropicalParadiseBg,
      gallery: tropicalParadiseBg,
      rsvp: tropicalParadiseBg,
      guestbook: tropicalParadiseBg,
      envelope: tropicalParadiseBg,
      closing: tropicalParadiseBg,
    },
  },
  {
    id: 'islamic-ottoman-sapphire',
    name: 'Ottoman Sapphire',
    description: 'Tema Islami biru sapphire mewah dengan ornamen Ottoman emas, bulan sabit & masjid',
    eventTypes: ['khitanan', 'aqiqah', 'pengajian', 'tahlilan', 'bukber', 'wedding', 'lamaran'],
    previewImage: ottomanSapphireBg,
    isPremium: false,
    isFullCustom: true,
    colorScheme: { primary: '#D4AF37', secondary: '#1B2A6B', background: '#0D1842', text: '#F5E6C4' },
    sections: defaultSections,
    style: 'elegant',
    defaultBackgrounds: {
      cover: ottomanSapphireBg,
      names: ottomanSapphireBg,
      countdown: ottomanSapphireBg,
      datetime: ottomanSapphireBg,
      location: ottomanSapphireBg,
      gallery: ottomanSapphireBg,
      rsvp: ottomanSapphireBg,
      guestbook: ottomanSapphireBg,
      envelope: ottomanSapphireBg,
      closing: ottomanSapphireBg,
    },
  },
  {
    id: 'graduation-academic-laurel',
    name: 'Academic Laurel',
    description: 'Wisuda elegan maroon dengan laurel emas, toga & gulungan diploma klasik',
    eventTypes: ['wisuda', 'family', 'acara_umum'],
    previewImage: academicLaurelBg,
    isPremium: false,
    isFullCustom: true,
    colorScheme: { primary: '#D4AF37', secondary: '#6B1A2C', background: '#3D0A18', text: '#F5E6C4' },
    sections: defaultSections,
    style: 'elegant',
    defaultBackgrounds: {
      cover: academicLaurelBg,
      names: academicLaurelBg,
      countdown: academicLaurelBg,
      datetime: academicLaurelBg,
      location: academicLaurelBg,
      gallery: academicLaurelBg,
      rsvp: academicLaurelBg,
      guestbook: academicLaurelBg,
      envelope: academicLaurelBg,
      closing: academicLaurelBg,
    },
  },
  {
    id: 'family-vintage-botanical',
    name: 'Vintage Botanical',
    description: 'Reuni keluarga vintage dengan ilustrasi botani lavender, paku & daisy di kertas antik',
    eventTypes: ['family', 'arisan', 'syukuran_rumah', 'birthday', 'acara_umum', 'wisuda'],
    previewImage: vintageBotanicalBg,
    isPremium: false,
    isFullCustom: true,
    colorScheme: { primary: '#8B6F47', secondary: '#A8826A', background: '#FBE8DC', text: '#4A3728' },
    sections: defaultSections,
    style: 'classic',
    defaultBackgrounds: {
      cover: vintageBotanicalBg,
      names: vintageBotanicalBg,
      countdown: vintageBotanicalBg,
      datetime: vintageBotanicalBg,
      location: vintageBotanicalBg,
      gallery: vintageBotanicalBg,
      rsvp: vintageBotanicalBg,
      guestbook: vintageBotanicalBg,
      envelope: vintageBotanicalBg,
      closing: vintageBotanicalBg,
    },
  },
  {
    id: 'full-custom',
    name: 'Full Custom',
    description: 'Desain sepenuhnya kustom — upload gambar background sendiri untuk setiap bagian undangan',
    eventTypes: ['wedding', 'khitanan', 'hajatan', 'birthday', 'lamaran', 'aqiqah', 'family', 'duka_cita', 'tahlilan', 'pengajian', 'bukber', 'acara_umum'],
    previewImage: '/templates/full-custom.jpg',
    isPremium: false,
    isFullCustom: true,
    colorScheme: { primary: '#c9a962', secondary: '#f5e6d3', background: '#1a1a1a', text: '#ffffff' },
    sections: defaultSections,
    style: 'custom',
  },

  // ═══════════════════════════════════════════════════════════
  // NICHE: TROPICAL PARADISE (5 templates – non-wedding)
  // ═══════════════════════════════════════════════════════════
  {
    id: 'birthday-tropical-fiesta',
    name: 'Tropical Fiesta',
    description: 'Pesta ulang tahun tropis penuh warna cerah dan buah eksotis',
    eventTypes: ['birthday'],
    previewImage: '/templates/birthday-tropical.jpg',
    isPremium: false,
    colorScheme: { primary: '#FF6B35', secondary: '#FFC857', background: '#FFF8F0', text: '#2D2D2D' },
    sections: defaultSections,
    style: 'modern',
  },
  {
    id: 'family-pantai-senja',
    name: 'Pantai Senja',
    description: 'Kumpul keluarga dengan nuansa sunset pantai tropis yang hangat',
    eventTypes: ['family'],
    previewImage: '/templates/family-pantai.jpg',
    isPremium: false,
    colorScheme: { primary: '#E07A5F', secondary: '#F2CC8F', background: '#FDF6ED', text: '#3D405B' },
    sections: defaultSections,
    style: 'modern',
  },
  {
    id: 'bukber-kelapa-muda',
    name: 'Kelapa Muda',
    description: 'Undangan bukber segar bernuansa tropis Ramadan yang ceria',
    eventTypes: ['bukber'],
    previewImage: '/templates/bukber-kelapa.jpg',
    isPremium: false,
    colorScheme: { primary: '#2D936C', secondary: '#88D498', background: '#F0FFF4', text: '#1B4332' },
    sections: defaultSections,
    style: 'modern',
  },
  {
    id: 'arisan-paradise-island',
    name: 'Paradise Island',
    description: 'Arisan bernuansa pulau tropis yang menyenangkan',
    eventTypes: ['arisan'],
    previewImage: '/templates/arisan-paradise.jpg',
    isPremium: false,
    colorScheme: { primary: '#00B4D8', secondary: '#90E0EF', background: '#F0FAFF', text: '#023E8A' },
    sections: defaultSections,
    style: 'modern',
  },
  {
    id: 'acara-umum-hawaiian',
    name: 'Hawaiian Luau',
    description: 'Acara umum dengan tema pesta Hawaii yang meriah dan penuh warna',
    eventTypes: ['acara_umum'],
    previewImage: '/templates/acara-hawaiian.jpg',
    isPremium: false,
    colorScheme: { primary: '#FF006E', secondary: '#FFBE0B', background: '#FFF5F7', text: '#370617' },
    sections: defaultSections,
    style: 'modern',
  },

  // ═══════════════════════════════════════════════════════════
  // NICHE: RETRO & VINTAGE (5 templates – non-wedding)
  // ═══════════════════════════════════════════════════════════
  {
    id: 'khitanan-retro-pop',
    name: 'Retro Pop',
    description: 'Undangan khitanan bergaya retro 80-an yang playful dan colorful',
    eventTypes: ['khitanan'],
    previewImage: '/templates/khitanan-retro.jpg',
    isPremium: false,
    colorScheme: { primary: '#E63946', secondary: '#FCA311', background: '#FFFDF5', text: '#1D3557' },
    sections: defaultSections,
    style: 'modern',
  },
  {
    id: 'aqiqah-vintage-rose',
    name: 'Vintage Rose',
    description: 'Aqiqah bernuansa vintage dengan detail mawar klasik yang lembut',
    eventTypes: ['aqiqah'],
    previewImage: '/templates/aqiqah-vintage.jpg',
    isPremium: false,
    colorScheme: { primary: '#C1666B', secondary: '#E8D5B7', background: '#FFF9F4', text: '#4A4A4A' },
    sections: defaultSections,
    style: 'classic',
  },
  {
    id: 'wisuda-classic-scholar',
    name: 'Classic Scholar',
    description: 'Undangan wisuda dengan estetika akademis klasik yang bermartabat',
    eventTypes: ['wisuda'],
    previewImage: '/templates/wisuda-classic.jpg',
    isPremium: false,
    colorScheme: { primary: '#2B2D42', secondary: '#D4A373', background: '#FBF8F1', text: '#2B2D42' },
    sections: defaultSections,
    style: 'classic',
  },
  {
    id: 'hajatan-nostalgia',
    name: 'Nostalgia',
    description: 'Syukuran dengan nuansa nostalgia tempo dulu yang hangat dan familiar',
    eventTypes: ['hajatan'],
    previewImage: '/templates/hajatan-nostalgia.jpg',
    isPremium: false,
    colorScheme: { primary: '#8B5E3C', secondary: '#D4A373', background: '#FDF6EC', text: '#3B2F2F' },
    sections: defaultSections,
    style: 'classic',
  },
  {
    id: 'syukuran-rumah-art-deco',
    name: 'Art Deco',
    description: 'Syukuran rumah baru dengan sentuhan art deco mewah era 1920-an',
    eventTypes: ['syukuran_rumah'],
    previewImage: '/templates/syukuran-artdeco.jpg',
    isPremium: false,
    colorScheme: { primary: '#C9B037', secondary: '#1C1C1C', background: '#0F0F0F', text: '#F5F0E1' },
    sections: defaultSections,
    style: 'elegant',
  },

  // ═══════════════════════════════════════════════════════════
  // NICHE: COSMIC & GALAXY (5 templates – non-wedding)
  // ═══════════════════════════════════════════════════════════
  {
    id: 'birthday-stardust',
    name: 'Stardust',
    description: 'Ulang tahun bertema debu bintang dan galaksi yang memukau',
    eventTypes: ['birthday'],
    previewImage: '/templates/birthday-stardust.jpg',
    isPremium: false,
    colorScheme: { primary: '#9B5DE5', secondary: '#F15BB5', background: '#0D0221', text: '#E8E8E8' },
    sections: defaultSections,
    style: 'modern',
  },
  {
    id: 'lamaran-moonlight',
    name: 'Moonlight',
    description: 'Lamaran romantis di bawah sinar bulan yang lembut dan misterius',
    eventTypes: ['lamaran'],
    previewImage: '/templates/lamaran-moonlight.jpg',
    isPremium: false,
    colorScheme: { primary: '#B8C0FF', secondary: '#E2E8F4', background: '#141428', text: '#E8E8F0' },
    sections: defaultSections,
    style: 'elegant',
  },
  {
    id: 'wisuda-constellation',
    name: 'Constellation',
    description: 'Wisuda dengan peta bintang dan rasi yang inspiratif',
    eventTypes: ['wisuda'],
    previewImage: '/templates/wisuda-constellation.jpg',
    isPremium: false,
    colorScheme: { primary: '#FFD700', secondary: '#4361EE', background: '#0A0A23', text: '#F0F0F0' },
    sections: defaultSections,
    style: 'modern',
  },
  {
    id: 'pengajian-nebula',
    name: 'Nebula Ilahi',
    description: 'Pengajian dengan keindahan nebula sebagai simbol keagungan Ilahi',
    eventTypes: ['pengajian'],
    previewImage: '/templates/pengajian-nebula.jpg',
    isPremium: false,
    colorScheme: { primary: '#48BFE3', secondary: '#7209B7', background: '#10002B', text: '#E0E0E0' },
    sections: defaultSections,
    style: 'modern',
  },
  {
    id: 'family-aurora-borealis',
    name: 'Aurora Borealis',
    description: 'Kumpul keluarga dengan nuansa aurora yang magis dan hangat',
    eventTypes: ['family'],
    previewImage: '/templates/family-aurora.jpg',
    isPremium: false,
    colorScheme: { primary: '#06D6A0', secondary: '#118AB2', background: '#073B4C', text: '#EDF6F9' },
    sections: defaultSections,
    style: 'modern',
  },

  // ═══════════════════════════════════════════════════════════
  // NICHE: BOTANICAL & GARDEN (5 templates – non-wedding)
  // ═══════════════════════════════════════════════════════════
  {
    id: 'tahlilan-zaitun',
    name: 'Daun Zaitun',
    description: 'Tahlilan dengan nuansa daun zaitun yang tenang dan khidmat',
    eventTypes: ['tahlilan'],
    previewImage: '/templates/tahlilan-zaitun.jpg',
    isPremium: false,
    colorScheme: { primary: '#606C38', secondary: '#BCB88A', background: '#FEFAE0', text: '#283618' },
    sections: defaultSections,
    style: 'classic',
  },
  {
    id: 'duka-cita-lily-putih',
    name: 'Lily Putih',
    description: 'Berita duka cita dengan keanggunan bunga lily putih yang syahdu',
    eventTypes: ['duka_cita'],
    previewImage: '/templates/duka-lily.jpg',
    isPremium: false,
    colorScheme: { primary: '#6C757D', secondary: '#ADB5BD', background: '#F8F9FA', text: '#212529' },
    sections: defaultSections,
    style: 'minimalist',
  },
  {
    id: 'aqiqah-garden-party',
    name: 'Garden Party',
    description: 'Aqiqah ceria dengan tema pesta kebun yang segar dan indah',
    eventTypes: ['aqiqah'],
    previewImage: '/templates/aqiqah-garden.jpg',
    isPremium: false,
    colorScheme: { primary: '#57CC99', secondary: '#C7F9CC', background: '#F0FFF0', text: '#22577A' },
    sections: defaultSections,
    style: 'modern',
  },
  {
    id: 'khitanan-bambu-hijau',
    name: 'Bambu Hijau',
    description: 'Khitanan dengan nuansa bambu hijau yang segar dan natural',
    eventTypes: ['khitanan'],
    previewImage: '/templates/khitanan-bambu.jpg',
    isPremium: false,
    colorScheme: { primary: '#344E41', secondary: '#A3B18A', background: '#F5F5F0', text: '#344E41' },
    sections: defaultSections,
    style: 'minimalist',
  },
  {
    id: 'hajatan-lavender-field',
    name: 'Lavender Field',
    description: 'Hajatan dengan aroma lavender yang menenangkan dan elegan',
    eventTypes: ['hajatan'],
    previewImage: '/templates/hajatan-lavender.jpg',
    isPremium: false,
    colorScheme: { primary: '#7B2D8E', secondary: '#D4A5D8', background: '#FAF5FF', text: '#3C1053' },
    sections: defaultSections,
    style: 'elegant',
  },
];

// Auto-mark templates: only the first 2 per event type are free, rest are premium
const FREE_PER_CATEGORY = 2;

function applyPremiumFlags(tpls: Template[]): Template[] {
  const countByEvent: Record<string, number> = {};
  return tpls.map((t) => {
    // Use the first eventType for counting
    const eventKey = t.eventTypes[0];
    countByEvent[eventKey] = (countByEvent[eventKey] || 0) + 1;
    return {
      ...t,
      isPremium: countByEvent[eventKey] > FREE_PER_CATEGORY,
    };
  });
}

const processedTemplates = applyPremiumFlags(_templates);

export const templates = processedTemplates;

export const getTemplatesByEventType = (eventType: EventType): Template[] => {
  const filtered = processedTemplates.filter((t) => t.eventTypes.includes(eventType));
  return filtered.sort((a, b) => (b.isFullCustom ? 1 : 0) - (a.isFullCustom ? 1 : 0));
};

export const getTemplateById = (id: string): Template | undefined => {
  return processedTemplates.find((t) => t.id === id);
};

/**
 * Resolve a template safely. Falls back to the first template of the given
 * event type, or any template, so an unknown/legacy templateId never causes
 * a blank/error screen on a published invitation.
 */
export const resolveTemplate = (id: string, eventType?: EventType): Template => {
  const exact = processedTemplates.find((t) => t.id === id);
  if (exact) return exact;
  if (eventType) {
    const byEvent = processedTemplates.find((t) => t.eventTypes.includes(eventType));
    if (byEvent) {
      console.warn(`[templates] Unknown templateId "${id}" — falling back to "${byEvent.id}" for event "${eventType}"`);
      return byEvent;
    }
  }
  console.warn(`[templates] Unknown templateId "${id}" — falling back to first template`);
  return processedTemplates[0];
};

export const getFreeTemplateCount = (eventType: EventType): number => {
  return processedTemplates.filter((t) => t.eventTypes.includes(eventType) && !t.isPremium).length;
};

export const getPremiumTemplateCount = (eventType: EventType): number => {
  return processedTemplates.filter((t) => t.eventTypes.includes(eventType) && t.isPremium).length;
};
