import { EventType } from './event-types';

export interface TemplateSection {
  id: string;
  type: 'cover' | 'names' | 'datetime' | 'location' | 'gallery' | 'message' | 'countdown';
  enabled: boolean;
}

export interface Template {
  id: string;
  name: string;
  description: string;
  eventTypes: EventType[];
  previewImage: string;
  isPremium: boolean;
  colorScheme: {
    primary: string;
    secondary: string;
    background: string;
    text: string;
  };
  sections: TemplateSection[];
  style: 'classic' | 'modern' | 'minimalist' | 'elegant' | 'rustic';
}

const defaultSections: TemplateSection[] = [
  { id: 'cover', type: 'cover', enabled: true },
  { id: 'names', type: 'names', enabled: true },
  { id: 'countdown', type: 'countdown', enabled: true },
  { id: 'datetime', type: 'datetime', enabled: true },
  { id: 'location', type: 'location', enabled: true },
  { id: 'gallery', type: 'gallery', enabled: true },
  { id: 'message', type: 'message', enabled: true },
];

const simpleSections: TemplateSection[] = [
  { id: 'cover', type: 'cover', enabled: true },
  { id: 'names', type: 'names', enabled: true },
  { id: 'datetime', type: 'datetime', enabled: true },
  { id: 'location', type: 'location', enabled: true },
  { id: 'message', type: 'message', enabled: true },
];

export const templates: Template[] = [
  // ── Wedding Templates (1 free, 4 premium) ──
  {
    id: 'wedding-classic-gold',
    name: 'Emas Klasik',
    description: 'Desain klasik dengan sentuhan emas yang elegan',
    eventTypes: ['wedding'],
    previewImage: '/templates/wedding-classic.jpg',
    isPremium: false,
    colorScheme: { primary: '#c9a962', secondary: '#f5e6d3', background: '#faf8f5', text: '#3d3d3d' },
    sections: defaultSections,
    style: 'classic',
  },
  {
    id: 'wedding-modern-blush',
    name: 'Blush Modern',
    description: 'Desain modern dengan warna pink lembut',
    eventTypes: ['wedding'],
    previewImage: '/templates/wedding-modern.jpg',
    isPremium: false,
    colorScheme: { primary: '#d4a5a5', secondary: '#f8e8e8', background: '#ffffff', text: '#4a4a4a' },
    sections: defaultSections,
    style: 'modern',
  },
  {
    id: 'wedding-elegant-navy',
    name: 'Navy Elegan',
    description: 'Desain elegan dengan warna navy dan emas',
    eventTypes: ['wedding'],
    previewImage: '/templates/wedding-elegant.jpg',
    isPremium: false,
    colorScheme: { primary: '#1e3a5f', secondary: '#c9a962', background: '#f8f9fa', text: '#1e3a5f' },
    sections: defaultSections,
    style: 'elegant',
  },
  {
    id: 'wedding-rustic-sage',
    name: 'Sage Rustic',
    description: 'Nuansa alam dengan warna sage yang menenangkan',
    eventTypes: ['wedding'],
    previewImage: '/templates/wedding-rustic.jpg',
    isPremium: false,
    colorScheme: { primary: '#7a9e7e', secondary: '#e8f0e8', background: '#fafdf9', text: '#3d4f3d' },
    sections: defaultSections,
    style: 'rustic',
  },
  {
    id: 'wedding-minimalist-mono',
    name: 'Mono Minimalis',
    description: 'Desain minimalis hitam putih yang timeless',
    eventTypes: ['wedding'],
    previewImage: '/templates/wedding-minimalist.jpg',
    isPremium: false,
    colorScheme: { primary: '#2c2c2c', secondary: '#e8e8e8', background: '#ffffff', text: '#1a1a1a' },
    sections: defaultSections,
    style: 'minimalist',
  },
  {
    id: 'wedding-jawa-classic',
    name: 'Jawa Klasik',
    description: 'Tema pernikahan adat Jawa dengan nuansa coklat dan emas keraton',
    eventTypes: ['wedding'],
    previewImage: '/templates/wedding-jawa.jpg',
    isPremium: false,
    colorScheme: { primary: '#8B6914', secondary: '#F5E6C8', background: '#FDF8F0', text: '#4A3728' },
    sections: defaultSections,
    style: 'classic',
  },
  {
    id: 'wedding-sunda-elegant',
    name: 'Sunda Elegan',
    description: 'Tema pernikahan adat Sunda dengan nuansa hijau dan emas khas Parahyangan',
    eventTypes: ['wedding'],
    previewImage: '/templates/wedding-sunda.jpg',
    isPremium: false,
    colorScheme: { primary: '#2E7D32', secondary: '#E8F5E9', background: '#FAFDF7', text: '#1B5E20' },
    sections: defaultSections,
    style: 'elegant',
  },
  {
    id: 'wedding-madura-bold',
    name: 'Madura Berani',
    description: 'Tema pernikahan adat Madura dengan warna merah dan kuning yang khas',
    eventTypes: ['wedding'],
    previewImage: '/templates/wedding-madura.jpg',
    isPremium: false,
    colorScheme: { primary: '#B71C1C', secondary: '#FFECB3', background: '#FFF8F0', text: '#6D1010' },
    sections: defaultSections,
    style: 'classic',
  },
  {
    id: 'wedding-batak-megah',
    name: 'Batak Megah',
    description: 'Tema pernikahan adat Batak dengan nuansa merah tua dan emas ulos',
    eventTypes: ['wedding'],
    previewImage: '/templates/wedding-batak.jpg',
    isPremium: false,
    colorScheme: { primary: '#8B0000', secondary: '#FFD700', background: '#FFF9F0', text: '#5C0000' },
    sections: defaultSections,
    style: 'elegant',
  },
  {
    id: 'wedding-minang-indah',
    name: 'Minangkabau Indah',
    description: 'Tema pernikahan adat Minangkabau dengan nuansa merah dan emas Rumah Gadang',
    eventTypes: ['wedding'],
    previewImage: '/templates/wedding-minang.jpg',
    isPremium: false,
    colorScheme: { primary: '#C62828', secondary: '#FFF8E1', background: '#FFFDF5', text: '#7F1616' },
    sections: defaultSections,
    style: 'elegant',
  },
  {
    id: 'wedding-betawi-meriah',
    name: 'Betawi Meriah',
    description: 'Tema pernikahan adat Betawi dengan warna cerah khas ondel-ondel',
    eventTypes: ['wedding'],
    previewImage: '/templates/wedding-betawi.jpg',
    isPremium: false,
    colorScheme: { primary: '#E65100', secondary: '#FFF3E0', background: '#FFFBF5', text: '#BF360C' },
    sections: defaultSections,
    style: 'modern',
  },
  {
    id: 'wedding-bugis-megah',
    name: 'Bugis Megah',
    description: 'Tema pernikahan adat Bugis dengan nuansa merah marun dan emas songket',
    eventTypes: ['wedding'],
    previewImage: '/templates/wedding-bugis.jpg',
    isPremium: false,
    colorScheme: { primary: '#880E4F', secondary: '#FCE4EC', background: '#FFF8FA', text: '#560027' },
    sections: defaultSections,
    style: 'elegant',
  },
  {
    id: 'wedding-banten-klasik',
    name: 'Banten Klasik',
    description: 'Tema pernikahan adat Banten dengan nuansa putih dan emas debus',
    eventTypes: ['wedding'],
    previewImage: '/templates/wedding-banten.jpg',
    isPremium: false,
    colorScheme: { primary: '#5D4037', secondary: '#EFEBE9', background: '#FAF8F5', text: '#3E2723' },
    sections: defaultSections,
    style: 'classic',
  },
  {
    id: 'wedding-banjar-indah',
    name: 'Banjar Indah',
    description: 'Tema pernikahan adat Banjar dengan nuansa kuning dan hijau khas Kalimantan Selatan',
    eventTypes: ['wedding'],
    previewImage: '/templates/wedding-banjar.jpg',
    isPremium: false,
    colorScheme: { primary: '#F9A825', secondary: '#FFF9C4', background: '#FFFDE7', text: '#F57F17' },
    sections: defaultSections,
    style: 'elegant',
  },
  {
    id: 'wedding-bali-sakral',
    name: 'Bali Sakral',
    description: 'Tema pernikahan adat Bali dengan nuansa hitam putih dan emas pura',
    eventTypes: ['wedding'],
    previewImage: '/templates/wedding-bali.jpg',
    isPremium: false,
    colorScheme: { primary: '#4E342E', secondary: '#D7CCC8', background: '#FAF5F0', text: '#3E2723' },
    sections: defaultSections,
    style: 'classic',
  },
  {
    id: 'wedding-sasak-anggun',
    name: 'Sasak Anggun',
    description: 'Tema pernikahan adat Sasak Lombok dengan nuansa songket tenun',
    eventTypes: ['wedding'],
    previewImage: '/templates/wedding-sasak.jpg',
    isPremium: false,
    colorScheme: { primary: '#6A1B9A', secondary: '#F3E5F5', background: '#FDF5FF', text: '#4A148C' },
    sections: defaultSections,
    style: 'elegant',
  },
  {
    id: 'wedding-aceh-mulia',
    name: 'Aceh Mulia',
    description: 'Tema pernikahan adat Aceh dengan nuansa hijau islami dan emas',
    eventTypes: ['wedding'],
    previewImage: '/templates/wedding-aceh.jpg',
    isPremium: false,
    colorScheme: { primary: '#1B5E20', secondary: '#E8F5E9', background: '#F1F8E9', text: '#0D3B0F' },
    sections: defaultSections,
    style: 'classic',
  },
  {
    id: 'wedding-dayak-agung',
    name: 'Dayak Agung',
    description: 'Tema pernikahan adat Dayak dengan nuansa merah bata dan motif mandau',
    eventTypes: ['wedding'],
    previewImage: '/templates/wedding-dayak.jpg',
    isPremium: false,
    colorScheme: { primary: '#D84315', secondary: '#FFCCBC', background: '#FFF5F0', text: '#BF360C' },
    sections: defaultSections,
    style: 'rustic',
  },
  {
    id: 'wedding-makassar-gagah',
    name: 'Makassar Gagah',
    description: 'Tema pernikahan adat Makassar dengan nuansa merah dan emas baju bodo',
    eventTypes: ['wedding'],
    previewImage: '/templates/wedding-makassar.jpg',
    isPremium: false,
    colorScheme: { primary: '#C62828', secondary: '#FFCDD2', background: '#FFF5F5', text: '#B71C1C' },
    sections: defaultSections,
    style: 'elegant',
  },
  {
    id: 'wedding-melayu-pesona',
    name: 'Melayu Pesona',
    description: 'Tema pernikahan adat Melayu dengan nuansa kuning kerajaan dan songket',
    eventTypes: ['wedding'],
    previewImage: '/templates/wedding-melayu.jpg',
    isPremium: false,
    colorScheme: { primary: '#FBC02D', secondary: '#FFF9C4', background: '#FFFDE7', text: '#F57F17' },
    sections: defaultSections,
    style: 'elegant',
  },
  {
    id: 'wedding-toraja-sakral',
    name: 'Toraja Sakral',
    description: 'Tema pernikahan adat Toraja dengan nuansa merah hitam tongkonan',
    eventTypes: ['wedding'],
    previewImage: '/templates/wedding-toraja.jpg',
    isPremium: false,
    colorScheme: { primary: '#B71C1C', secondary: '#212121', background: '#FFF8F5', text: '#4E0000' },
    sections: defaultSections,
    style: 'rustic',
  },
  {
    id: 'wedding-ambon-cerah',
    name: 'Ambon Cerah',
    description: 'Tema pernikahan adat Ambon/Maluku dengan nuansa biru laut dan putih pela gandong',
    eventTypes: ['wedding'],
    previewImage: '/templates/wedding-ambon.jpg',
    isPremium: false,
    colorScheme: { primary: '#0277BD', secondary: '#E1F5FE', background: '#F5FBFF', text: '#01579B' },
    sections: defaultSections,
    style: 'modern',
  },
  {
    id: 'wedding-papua-mulia',
    name: 'Papua Mulia',
    description: 'Tema pernikahan adat Papua dengan nuansa coklat tanah dan motif tifa',
    eventTypes: ['wedding'],
    previewImage: '/templates/wedding-papua.jpg',
    isPremium: false,
    colorScheme: { primary: '#6D4C41', secondary: '#D7CCC8', background: '#FAF3EF', text: '#4E342E' },
    sections: defaultSections,
    style: 'rustic',
  },
  {
    id: 'wedding-tionghoa-harmoni',
    name: 'Tionghoa Harmoni',
    description: 'Tema pernikahan Tionghoa Indonesia dengan nuansa merah keberuntungan dan emas',
    eventTypes: ['wedding'],
    previewImage: '/templates/wedding-tionghoa.jpg',
    isPremium: false,
    colorScheme: { primary: '#D32F2F', secondary: '#FFD54F', background: '#FFF8F0', text: '#B71C1C' },
    sections: defaultSections,
    style: 'elegant',
  },
  {
    id: 'wedding-lampung-agung',
    name: 'Lampung Agung',
    description: 'Tema pernikahan adat Lampung dengan nuansa tapis emas dan merah',
    eventTypes: ['wedding'],
    previewImage: '/templates/wedding-lampung.jpg',
    isPremium: false,
    colorScheme: { primary: '#8D6E63', secondary: '#FFE0B2', background: '#FFF8F0', text: '#5D4037' },
    sections: defaultSections,
    style: 'classic',
  },

  // ── Khitanan Templates (1 free, 3 premium) ──
  {
    id: 'khitanan-festive-blue',
    name: 'Biru Ceria',
    description: 'Desain ceria dengan warna biru yang menyegarkan',
    eventTypes: ['khitanan'],
    previewImage: '/templates/khitanan-blue.jpg',
    isPremium: false,
    colorScheme: { primary: '#2196f3', secondary: '#e3f2fd', background: '#ffffff', text: '#1565c0' },
    sections: defaultSections,
    style: 'modern',
  },
  {
    id: 'khitanan-islamic-green',
    name: 'Hijau Islami',
    description: 'Desain islami dengan nuansa hijau yang tenang',
    eventTypes: ['khitanan'],
    previewImage: '/templates/khitanan-green.jpg',
    isPremium: false,
    colorScheme: { primary: '#2e7d32', secondary: '#e8f5e9', background: '#fafafa', text: '#1b5e20' },
    sections: defaultSections,
    style: 'classic',
  },
  {
    id: 'khitanan-golden-festive',
    name: 'Emas Meriah',
    description: 'Desain meriah dengan aksen emas dan biru tua',
    eventTypes: ['khitanan'],
    previewImage: '/templates/khitanan-golden.jpg',
    isPremium: false,
    colorScheme: { primary: '#d4a017', secondary: '#fff8e1', background: '#fffef5', text: '#5d4e0e' },
    sections: defaultSections,
    style: 'elegant',
  },
  {
    id: 'khitanan-playful-teal',
    name: 'Teal Playful',
    description: 'Desain playful dengan warna teal yang segar',
    eventTypes: ['khitanan'],
    previewImage: '/templates/khitanan-teal.jpg',
    isPremium: false,
    colorScheme: { primary: '#00897b', secondary: '#e0f2f1', background: '#ffffff', text: '#004d40' },
    sections: defaultSections,
    style: 'modern',
  },

  // ── Hajatan Templates (1 free, 3 premium) ──
  {
    id: 'hajatan-warm-earth',
    name: 'Hangat Bumi',
    description: 'Desain hangat dengan warna tanah yang menenangkan',
    eventTypes: ['hajatan'],
    previewImage: '/templates/hajatan-earth.jpg',
    isPremium: false,
    colorScheme: { primary: '#8d6e63', secondary: '#efebe9', background: '#fafaf9', text: '#5d4037' },
    sections: simpleSections,
    style: 'rustic',
  },
  {
    id: 'hajatan-simple-sage',
    name: 'Sage Sederhana',
    description: 'Desain minimalis dengan warna sage yang elegan',
    eventTypes: ['hajatan'],
    previewImage: '/templates/hajatan-sage.jpg',
    isPremium: false,
    colorScheme: { primary: '#6b8e6b', secondary: '#e8f0e8', background: '#ffffff', text: '#4a5d4a' },
    sections: simpleSections,
    style: 'minimalist',
  },
  {
    id: 'hajatan-classic-maroon',
    name: 'Maroon Klasik',
    description: 'Nuansa maroon klasik yang hangat dan bermartabat',
    eventTypes: ['hajatan'],
    previewImage: '/templates/hajatan-maroon.jpg',
    isPremium: false,
    colorScheme: { primary: '#7b1f3a', secondary: '#fce4ec', background: '#fff8f9', text: '#5a1028' },
    sections: simpleSections,
    style: 'classic',
  },
  {
    id: 'hajatan-modern-teal',
    name: 'Teal Modern',
    description: 'Desain modern dengan warna teal yang segar',
    eventTypes: ['hajatan'],
    previewImage: '/templates/hajatan-teal.jpg',
    isPremium: false,
    colorScheme: { primary: '#00796b', secondary: '#e0f2f1', background: '#ffffff', text: '#004d40' },
    sections: simpleSections,
    style: 'modern',
  },

  // ── Birthday Templates (1 free, 3 premium) ──
  {
    id: 'birthday-colorful-party',
    name: 'Pesta Warna',
    description: 'Desain penuh warna untuk pesta yang meriah',
    eventTypes: ['birthday'],
    previewImage: '/templates/birthday-colorful.jpg',
    isPremium: false,
    colorScheme: { primary: '#9c27b0', secondary: '#f3e5f5', background: '#ffffff', text: '#6a1b9a' },
    sections: defaultSections,
    style: 'modern',
  },
  {
    id: 'birthday-elegant-rose',
    name: 'Mawar Elegan',
    description: 'Desain elegan untuk ulang tahun dewasa',
    eventTypes: ['birthday'],
    previewImage: '/templates/birthday-rose.jpg',
    isPremium: false,
    colorScheme: { primary: '#c2185b', secondary: '#fce4ec', background: '#fff8fa', text: '#880e4f' },
    sections: defaultSections,
    style: 'elegant',
  },
  {
    id: 'birthday-tropical-fun',
    name: 'Tropical Fun',
    description: 'Desain tropis yang ceria dan penuh semangat',
    eventTypes: ['birthday'],
    previewImage: '/templates/birthday-tropical.jpg',
    isPremium: false,
    colorScheme: { primary: '#ff6f00', secondary: '#fff3e0', background: '#fffdf5', text: '#e65100' },
    sections: defaultSections,
    style: 'modern',
  },
  {
    id: 'birthday-pastel-dream',
    name: 'Pastel Dream',
    description: 'Nuansa pastel yang lembut dan bermimpi',
    eventTypes: ['birthday'],
    previewImage: '/templates/birthday-pastel.jpg',
    isPremium: false,
    colorScheme: { primary: '#ab47bc', secondary: '#f3e5f5', background: '#fef9ff', text: '#7b1fa2' },
    sections: defaultSections,
    style: 'minimalist',
  },

  // ── Family Gathering Templates (1 free, 3 premium) ──
  {
    id: 'family-warm-orange',
    name: 'Oranye Hangat',
    description: 'Desain hangat untuk pertemuan keluarga',
    eventTypes: ['family'],
    previewImage: '/templates/family-orange.jpg',
    isPremium: false,
    colorScheme: { primary: '#e65100', secondary: '#fff3e0', background: '#fffbf5', text: '#bf360c' },
    sections: simpleSections,
    style: 'modern',
  },
  {
    id: 'family-classic-brown',
    name: 'Coklat Klasik',
    description: 'Desain klasik yang hangat dan nyaman',
    eventTypes: ['family'],
    previewImage: '/templates/family-brown.jpg',
    isPremium: false,
    colorScheme: { primary: '#795548', secondary: '#efebe9', background: '#faf8f5', text: '#4e342e' },
    sections: simpleSections,
    style: 'classic',
  },
  {
    id: 'family-garden-green',
    name: 'Hijau Taman',
    description: 'Nuansa taman hijau yang menyegarkan',
    eventTypes: ['family'],
    previewImage: '/templates/family-green.jpg',
    isPremium: false,
    colorScheme: { primary: '#388e3c', secondary: '#e8f5e9', background: '#f9fdf9', text: '#1b5e20' },
    sections: simpleSections,
    style: 'rustic',
  },
  {
    id: 'family-sunset-gold',
    name: 'Emas Senja',
    description: 'Warna senja keemasan yang hangat dan indah',
    eventTypes: ['family'],
    previewImage: '/templates/family-sunset.jpg',
    isPremium: false,
    colorScheme: { primary: '#f57c00', secondary: '#ffe0b2', background: '#fffcf5', text: '#e65100' },
    sections: simpleSections,
    style: 'elegant',
  },

  // ── Aqiqah Templates ──
  {
    id: 'aqiqah-soft-pink',
    name: 'Pink Lembut',
    description: 'Desain lembut untuk menyambut buah hati',
    eventTypes: ['aqiqah'],
    previewImage: '/templates/aqiqah-pink.jpg',
    isPremium: false,
    colorScheme: { primary: '#e91e63', secondary: '#fce4ec', background: '#fff8fa', text: '#880e4f' },
    sections: simpleSections,
    style: 'modern',
  },
  {
    id: 'aqiqah-islamic-teal',
    name: 'Teal Islami',
    description: 'Nuansa islami yang tenang untuk aqiqah',
    eventTypes: ['aqiqah'],
    previewImage: '/templates/aqiqah-teal.jpg',
    isPremium: false,
    colorScheme: { primary: '#00695c', secondary: '#e0f2f1', background: '#fafffe', text: '#004d40' },
    sections: simpleSections,
    style: 'classic',
  },

  // ── Tahlilan Templates ──
  {
    id: 'tahlilan-serene-green',
    name: 'Hijau Khusyuk',
    description: 'Desain tenang dan khusyuk untuk acara tahlilan',
    eventTypes: ['tahlilan'],
    previewImage: '/templates/tahlilan-green.jpg',
    isPremium: false,
    colorScheme: { primary: '#2e7d32', secondary: '#e8f5e9', background: '#f5faf5', text: '#1b5e20' },
    sections: simpleSections,
    style: 'classic',
  },
  {
    id: 'tahlilan-calm-grey',
    name: 'Abu Tenang',
    description: 'Nuansa abu-abu yang tenang dan bermartabat',
    eventTypes: ['tahlilan'],
    previewImage: '/templates/tahlilan-grey.jpg',
    isPremium: false,
    colorScheme: { primary: '#546e7a', secondary: '#eceff1', background: '#fafafa', text: '#37474f' },
    sections: simpleSections,
    style: 'minimalist',
  },

  // ── Pengajian Templates ──
  {
    id: 'pengajian-green-gold',
    name: 'Hijau Emas',
    description: 'Nuansa islami hijau dan emas untuk pengajian',
    eventTypes: ['pengajian'],
    previewImage: '/templates/pengajian-green.jpg',
    isPremium: false,
    colorScheme: { primary: '#1b5e20', secondary: '#fff8e1', background: '#f9fdf5', text: '#0d3b0f' },
    sections: simpleSections,
    style: 'classic',
  },
  {
    id: 'pengajian-royal-blue',
    name: 'Biru Masjid',
    description: 'Warna biru masjid yang elegan',
    eventTypes: ['pengajian'],
    previewImage: '/templates/pengajian-blue.jpg',
    isPremium: false,
    colorScheme: { primary: '#1565c0', secondary: '#e3f2fd', background: '#f5f9ff', text: '#0d47a1' },
    sections: simpleSections,
    style: 'elegant',
  },

  // ── Wisuda Templates ──
  {
    id: 'wisuda-navy-gold',
    name: 'Navy & Emas',
    description: 'Desain formal wisuda dengan navy dan emas',
    eventTypes: ['wisuda'],
    previewImage: '/templates/wisuda-navy.jpg',
    isPremium: false,
    colorScheme: { primary: '#1a237e', secondary: '#c5cae9', background: '#f5f5ff', text: '#1a237e' },
    sections: defaultSections,
    style: 'elegant',
  },
  {
    id: 'wisuda-maroon-classic',
    name: 'Maroon Wisuda',
    description: 'Nuansa maroon akademis yang bermartabat',
    eventTypes: ['wisuda'],
    previewImage: '/templates/wisuda-maroon.jpg',
    isPremium: false,
    colorScheme: { primary: '#7b1f3a', secondary: '#fce4ec', background: '#fff8f9', text: '#5a1028' },
    sections: defaultSections,
    style: 'classic',
  },

  // ── Lamaran Templates ──
  {
    id: 'lamaran-rose-gold',
    name: 'Rose Gold',
    description: 'Desain romantis dengan nuansa rose gold',
    eventTypes: ['lamaran'],
    previewImage: '/templates/lamaran-rose.jpg',
    isPremium: false,
    colorScheme: { primary: '#b76e79', secondary: '#fce4ec', background: '#fff8fa', text: '#6d3a42' },
    sections: defaultSections,
    style: 'elegant',
  },
  {
    id: 'lamaran-sage-romantic',
    name: 'Sage Romantis',
    description: 'Nuansa sage hijau lembut yang romantis',
    eventTypes: ['lamaran'],
    previewImage: '/templates/lamaran-sage.jpg',
    isPremium: false,
    colorScheme: { primary: '#7a9e7e', secondary: '#e8f0e8', background: '#fafdf9', text: '#3d4f3d' },
    sections: defaultSections,
    style: 'rustic',
  },

  // ── Syukuran Rumah Templates ──
  {
    id: 'syukuran-rumah-warm',
    name: 'Hangat Rumah',
    description: 'Desain hangat untuk syukuran rumah baru',
    eventTypes: ['syukuran_rumah'],
    previewImage: '/templates/syukuran-warm.jpg',
    isPremium: false,
    colorScheme: { primary: '#bf360c', secondary: '#fbe9e7', background: '#fffbf5', text: '#8d3010' },
    sections: simpleSections,
    style: 'modern',
  },
  {
    id: 'syukuran-rumah-green',
    name: 'Hijau Berkah',
    description: 'Nuansa hijau penuh berkah untuk syukuran',
    eventTypes: ['syukuran_rumah'],
    previewImage: '/templates/syukuran-green.jpg',
    isPremium: false,
    colorScheme: { primary: '#388e3c', secondary: '#e8f5e9', background: '#f5faf5', text: '#1b5e20' },
    sections: simpleSections,
    style: 'classic',
  },

  // ── Duka Cita Templates ──
  {
    id: 'duka-cita-sombre',
    name: 'Hitam Duka',
    description: 'Desain penuh penghormatan untuk berita duka',
    eventTypes: ['duka_cita'],
    previewImage: '/templates/duka-sombre.jpg',
    isPremium: false,
    colorScheme: { primary: '#37474f', secondary: '#cfd8dc', background: '#f5f5f5', text: '#263238' },
    sections: simpleSections,
    style: 'minimalist',
  },
  {
    id: 'duka-cita-white',
    name: 'Putih Damai',
    description: 'Nuansa putih dan abu-abu yang tenang',
    eventTypes: ['duka_cita'],
    previewImage: '/templates/duka-white.jpg',
    isPremium: false,
    colorScheme: { primary: '#455a64', secondary: '#eceff1', background: '#fafafa', text: '#37474f' },
    sections: simpleSections,
    style: 'minimalist',
  },

  // ── Buka Puasa Templates ──
  {
    id: 'bukber-ramadan-gold',
    name: 'Emas Ramadan',
    description: 'Desain bernuansa Ramadan dengan emas dan hijau',
    eventTypes: ['bukber'],
    previewImage: '/templates/bukber-gold.jpg',
    isPremium: false,
    colorScheme: { primary: '#f9a825', secondary: '#e8f5e9', background: '#fffde7', text: '#5d4e0e' },
    sections: simpleSections,
    style: 'elegant',
  },
  {
    id: 'bukber-crescent-blue',
    name: 'Bulan Sabit',
    description: 'Nuansa biru malam dengan sentuhan bulan sabit',
    eventTypes: ['bukber'],
    previewImage: '/templates/bukber-blue.jpg',
    isPremium: false,
    colorScheme: { primary: '#1565c0', secondary: '#e3f2fd', background: '#f0f4ff', text: '#0d47a1' },
    sections: simpleSections,
    style: 'modern',
  },

  // ── Arisan Templates ──
  {
    id: 'arisan-fun-coral',
    name: 'Coral Ceria',
    description: 'Desain ceria dan santai untuk arisan',
    eventTypes: ['arisan'],
    previewImage: '/templates/arisan-coral.jpg',
    isPremium: false,
    colorScheme: { primary: '#ff5722', secondary: '#fbe9e7', background: '#fffaf8', text: '#bf360c' },
    sections: simpleSections,
    style: 'modern',
  },
  {
    id: 'arisan-soft-purple',
    name: 'Ungu Lembut',
    description: 'Nuansa ungu lembut untuk pertemuan santai',
    eventTypes: ['arisan'],
    previewImage: '/templates/arisan-purple.jpg',
    isPremium: false,
    colorScheme: { primary: '#7b1fa2', secondary: '#f3e5f5', background: '#fdf5ff', text: '#4a148c' },
    sections: simpleSections,
    style: 'minimalist',
  },

  // ── Acara Umum Templates ──
  {
    id: 'acara-umum-professional',
    name: 'Profesional',
    description: 'Desain profesional untuk acara formal',
    eventTypes: ['acara_umum'],
    previewImage: '/templates/umum-professional.jpg',
    isPremium: false,
    colorScheme: { primary: '#1565c0', secondary: '#e3f2fd', background: '#ffffff', text: '#0d47a1' },
    sections: simpleSections,
    style: 'modern',
  },
  {
    id: 'acara-umum-casual',
    name: 'Kasual',
    description: 'Desain santai untuk acara informal',
    eventTypes: ['acara_umum'],
    previewImage: '/templates/umum-casual.jpg',
    isPremium: false,
    colorScheme: { primary: '#00897b', secondary: '#e0f2f1', background: '#fafffe', text: '#004d40' },
    sections: simpleSections,
    style: 'minimalist',
  },
];

export const getTemplatesByEventType = (eventType: EventType): Template[] => {
  return templates.filter((t) => t.eventTypes.includes(eventType));
};

export const getTemplateById = (id: string): Template | undefined => {
  return templates.find((t) => t.id === id);
};

export const getFreeTemplateCount = (eventType: EventType): number => {
  return templates.filter((t) => t.eventTypes.includes(eventType) && !t.isPremium).length;
};

export const getPremiumTemplateCount = (eventType: EventType): number => {
  return templates.filter((t) => t.eventTypes.includes(eventType) && t.isPremium).length;
};
